{
  "formatVersion": "1.1",
  "component": {
    "group": "kext",
    "module": "kext",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kext-1.0.0.jar",
          "url": "kext-1.0.0.jar",
          "size": 38889,
          "sha512": "ec71e9ed8e13624e02ca46ca5a7171703a0c5a7d9c78d510d8e4d66173aadf72243f4a4de02ec5931be21410bb822cdd5128121e3a1efd9bac477721ef22ee65",
          "sha256": "942dc1b52dca63011966f4bc4d8891f690ac5789aad8b9aa12061f08b84e77a8",
          "sha1": "3efee52b200315bcfca720dc36d8e0e1a8df90e4",
          "md5": "41edfc6ab9fc5924f3af341e3ec08e73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kext-1.0.0.jar",
          "url": "kext-1.0.0.jar",
          "size": 38889,
          "sha512": "ec71e9ed8e13624e02ca46ca5a7171703a0c5a7d9c78d510d8e4d66173aadf72243f4a4de02ec5931be21410bb822cdd5128121e3a1efd9bac477721ef22ee65",
          "sha256": "942dc1b52dca63011966f4bc4d8891f690ac5789aad8b9aa12061f08b84e77a8",
          "sha1": "3efee52b200315bcfca720dc36d8e0e1a8df90e4",
          "md5": "41edfc6ab9fc5924f3af341e3ec08e73"
        }
      ]
    }
  ]
}
