{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.9.jar",
          "url": "api-1.0.9.jar",
          "size": 1291757,
          "sha512": "654f6a2a43556ff723cfca457bc02eaffa392144ed007df0bb39ce69991a2787018c69b9ec35d1dddc468cb0e6245a19158843f6b15d7fb28e1d0ad39cfccf92",
          "sha256": "634cae8d7b2c0323e4012d4716432de7d8d3512a9ee17677176064b8a3f0a4ac",
          "sha1": "e3981a94a08d8a932db8de7386533b6a897af0bc",
          "md5": "b631db249db4d8ba5094087a07f18ff3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.9.jar",
          "url": "api-1.0.9.jar",
          "size": 1291757,
          "sha512": "654f6a2a43556ff723cfca457bc02eaffa392144ed007df0bb39ce69991a2787018c69b9ec35d1dddc468cb0e6245a19158843f6b15d7fb28e1d0ad39cfccf92",
          "sha256": "634cae8d7b2c0323e4012d4716432de7d8d3512a9ee17677176064b8a3f0a4ac",
          "sha1": "e3981a94a08d8a932db8de7386533b6a897af0bc",
          "md5": "b631db249db4d8ba5094087a07f18ff3"
        }
      ]
    }
  ]
}
