{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.4.jar",
          "url": "annotations-1.6.4.jar",
          "size": 8843,
          "sha512": "69affb2d5d4002a83586758586083e1483d9cae107451914e16366c835f95ff31954130385906245ee6d696ea9220b83947f265550a6e2e2436a4eeb053230aa",
          "sha256": "c718f7750cccf33f0006e0451ef33613654df22e893e1f358baea7b27f776e00",
          "sha1": "8d26acbb71e1587e93aba272991607a8b1c249e6",
          "md5": "5f4f3009a5c42997321fe0c33f579b8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.4.jar",
          "url": "annotations-1.6.4.jar",
          "size": 8843,
          "sha512": "69affb2d5d4002a83586758586083e1483d9cae107451914e16366c835f95ff31954130385906245ee6d696ea9220b83947f265550a6e2e2436a4eeb053230aa",
          "sha256": "c718f7750cccf33f0006e0451ef33613654df22e893e1f358baea7b27f776e00",
          "sha1": "8d26acbb71e1587e93aba272991607a8b1c249e6",
          "md5": "5f4f3009a5c42997321fe0c33f579b8b"
        }
      ]
    }
  ]
}
