{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-2.4.0.jar",
          "url": "scripts-2.4.0.jar",
          "size": 31877,
          "sha512": "534db7d13da9884a29d92deaa6a9b9de57ef89bd6f1d3ecc7f24aacb0dd8ff5c54453b983652b80624ed587b45dc537ca52cfb0e2955a3d79bd58f4a94e037f4",
          "sha256": "63ea3a6a342445571e8935760c9c188a99760c5720b00c6fd9d642a3441dde74",
          "sha1": "e7c2a7d832351887852c043f832c18c563b65318",
          "md5": "00c224b61de99496e33b325674ae8a92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-2.4.0.jar",
          "url": "scripts-2.4.0.jar",
          "size": 31877,
          "sha512": "534db7d13da9884a29d92deaa6a9b9de57ef89bd6f1d3ecc7f24aacb0dd8ff5c54453b983652b80624ed587b45dc537ca52cfb0e2955a3d79bd58f4a94e037f4",
          "sha256": "63ea3a6a342445571e8935760c9c188a99760c5720b00c6fd9d642a3441dde74",
          "sha1": "e7c2a7d832351887852c043f832c18c563b65318",
          "md5": "00c224b61de99496e33b325674ae8a92"
        }
      ]
    }
  ]
}
