{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.9.jar",
          "url": "api-1.6.9.jar",
          "size": 1341885,
          "sha512": "aa6eacfe7450634b4bcbf876aa29bab27d6a7a59af9c9251fe46118df40d72ee38a00719dde2c93287431fbabbe9f0d12dc5d7115e879d38804c76225bfdadd0",
          "sha256": "a0197e809284503fa44858c887746d973cb3711895c6eda2f13bad93c13ad0a5",
          "sha1": "eff419de1ba9efeca4101f8d789b2bd80b7ac621",
          "md5": "cce5ff120fa67b684d4ba033332ae2ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.9.jar",
          "url": "api-1.6.9.jar",
          "size": 1341885,
          "sha512": "aa6eacfe7450634b4bcbf876aa29bab27d6a7a59af9c9251fe46118df40d72ee38a00719dde2c93287431fbabbe9f0d12dc5d7115e879d38804c76225bfdadd0",
          "sha256": "a0197e809284503fa44858c887746d973cb3711895c6eda2f13bad93c13ad0a5",
          "sha1": "eff419de1ba9efeca4101f8d789b2bd80b7ac621",
          "md5": "cce5ff120fa67b684d4ba033332ae2ce"
        }
      ]
    }
  ]
}
