{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.0.2.jar",
          "url": "scripts-1.0.2.jar",
          "size": 28990,
          "sha512": "63c9fb181e9918478d171d7bd84f7124b50f5f1eb887e503b7adedb427ef4795e2f836bbadb2281473ba2222cc302b66ae88ba2464b25c7eb9907c9d2aebcdfe",
          "sha256": "132dbeb4ce8b2c0777aa1099f015fe43d5176008ce42f13fcf5b32eeacfea8e0",
          "sha1": "77bef42052adb2f2aabaf1b7c996c03eebc43d77",
          "md5": "45e5b2c525bdc1a58a3a8b18d5228cfd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.0.2.jar",
          "url": "scripts-1.0.2.jar",
          "size": 28990,
          "sha512": "63c9fb181e9918478d171d7bd84f7124b50f5f1eb887e503b7adedb427ef4795e2f836bbadb2281473ba2222cc302b66ae88ba2464b25c7eb9907c9d2aebcdfe",
          "sha256": "132dbeb4ce8b2c0777aa1099f015fe43d5176008ce42f13fcf5b32eeacfea8e0",
          "sha1": "77bef42052adb2f2aabaf1b7c996c03eebc43d77",
          "md5": "45e5b2c525bdc1a58a3a8b18d5228cfd"
        }
      ]
    }
  ]
}
