{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.4.5.jar",
          "url": "logger-1.4.5.jar",
          "size": 8658,
          "sha512": "4daca05eca7337647aaa6f9da18a17d58bb773588fb64ee58e2b410590084ad41e292d9615b504d6c248be104cc78cd537a044eb7750480f9ef875e20303f3df",
          "sha256": "95f722199243e6628ff417b78eed496d7f6a9daf3a459a2dbc3794d785eecb3f",
          "sha1": "40ae5104fbc9ada78019f584e26d688f19d05feb",
          "md5": "cebd929539bc8b2cfbe73f340ca96a1c"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.4.5.jar",
          "url": "logger-1.4.5.jar",
          "size": 8658,
          "sha512": "4daca05eca7337647aaa6f9da18a17d58bb773588fb64ee58e2b410590084ad41e292d9615b504d6c248be104cc78cd537a044eb7750480f9ef875e20303f3df",
          "sha256": "95f722199243e6628ff417b78eed496d7f6a9daf3a459a2dbc3794d785eecb3f",
          "sha1": "40ae5104fbc9ada78019f584e26d688f19d05feb",
          "md5": "cebd929539bc8b2cfbe73f340ca96a1c"
        }
      ]
    }
  ]
}
