{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.3.0.jar",
          "url": "api-1.3.0.jar",
          "size": 1338056,
          "sha512": "c3e40f700253bf43d6e5ea38caec877b306cdf840652a794a184766217b87d42a9ea9079cf233445a9106d25be285d8a253fbb95053ff39ddba3342b51620a8f",
          "sha256": "f0f8ba5dee232beb328d192c8b13e8994fdf4a0da9f5a5e7fb14baa90594108d",
          "sha1": "7ff57d6db36f8872f3bf1bb630a04f6dff73b7d2",
          "md5": "bd2b8f8341a7526a81f6840d69387e5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.3.0.jar",
          "url": "api-1.3.0.jar",
          "size": 1338056,
          "sha512": "c3e40f700253bf43d6e5ea38caec877b306cdf840652a794a184766217b87d42a9ea9079cf233445a9106d25be285d8a253fbb95053ff39ddba3342b51620a8f",
          "sha256": "f0f8ba5dee232beb328d192c8b13e8994fdf4a0da9f5a5e7fb14baa90594108d",
          "sha1": "7ff57d6db36f8872f3bf1bb630a04f6dff73b7d2",
          "md5": "bd2b8f8341a7526a81f6840d69387e5a"
        }
      ]
    }
  ]
}
