{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.0.3.jar",
          "url": "api-rs-1.0.3.jar",
          "size": 116824,
          "sha512": "ca512fbfbb6d7b1ec7339f61dcc2f9f6ee8cf653a4646cc770e73b3389a2ecbca1f75a07c1066ed7b7ead9c2fbf5da529c8c0263bd97d402d0042af18b6c7227",
          "sha256": "52f8fc54656d4511b3725fab5db59cdf6ebb7846e5f2158de999b8760d692a1f",
          "sha1": "7c77d82758093d4065bfe39c6e63ab55ef12faca",
          "md5": "02f9e8b6e01f04d719cfa02c3f95c0ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.0.3.jar",
          "url": "api-rs-1.0.3.jar",
          "size": 116824,
          "sha512": "ca512fbfbb6d7b1ec7339f61dcc2f9f6ee8cf653a4646cc770e73b3389a2ecbca1f75a07c1066ed7b7ead9c2fbf5da529c8c0263bd97d402d0042af18b6c7227",
          "sha256": "52f8fc54656d4511b3725fab5db59cdf6ebb7846e5f2158de999b8760d692a1f",
          "sha1": "7c77d82758093d4065bfe39c6e63ab55ef12faca",
          "md5": "02f9e8b6e01f04d719cfa02c3f95c0ed"
        }
      ]
    }
  ]
}
