{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.0.4.jar",
          "url": "annotations-1.0.4.jar",
          "size": 7290,
          "sha512": "b9827954e5799fe3ca089ca2376b45145edcf9644e715b5dd29b96fe06671dcb449dd51b0a2b553c07eb8d5d5264a2aa00651c4352ca8fae56a2f174b6fa8612",
          "sha256": "563f0d0f762e2c23dc5564ac3c32137470563bf2c95e720ee4d5695bb26516dd",
          "sha1": "8e89cd0885b9a5f433a150c4b9209b137835ff23",
          "md5": "5645b9088b0a2761def63b92ebca06e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.4.jar",
          "url": "annotations-1.0.4.jar",
          "size": 7290,
          "sha512": "b9827954e5799fe3ca089ca2376b45145edcf9644e715b5dd29b96fe06671dcb449dd51b0a2b553c07eb8d5d5264a2aa00651c4352ca8fae56a2f174b6fa8612",
          "sha256": "563f0d0f762e2c23dc5564ac3c32137470563bf2c95e720ee4d5695bb26516dd",
          "sha1": "8e89cd0885b9a5f433a150c4b9209b137835ff23",
          "md5": "5645b9088b0a2761def63b92ebca06e7"
        }
      ]
    }
  ]
}
