{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-4.0.0.jar",
          "url": "logger-4.0.0.jar",
          "size": 8658,
          "sha512": "e28ff4a4e36cb1d5f31cd459ffb76c86843cdb2a71a0c38bcd92b0b7aa1dd8eebfbc1a786744e28ed1fc51df669a07867e9a158030e613bc96b6c677f534eb8b",
          "sha256": "4867f23a0ea7ce9e46d4ec766567da6957083deaf5bb29f10e32cc4bb03088e4",
          "sha1": "75386d6fb0e50472af58a654c01a417f8c05f51e",
          "md5": "8ef68f67147a727fc6171516c54ac33f"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-4.0.0.jar",
          "url": "logger-4.0.0.jar",
          "size": 8658,
          "sha512": "e28ff4a4e36cb1d5f31cd459ffb76c86843cdb2a71a0c38bcd92b0b7aa1dd8eebfbc1a786744e28ed1fc51df669a07867e9a158030e613bc96b6c677f534eb8b",
          "sha256": "4867f23a0ea7ce9e46d4ec766567da6957083deaf5bb29f10e32cc4bb03088e4",
          "sha1": "75386d6fb0e50472af58a654c01a417f8c05f51e",
          "md5": "8ef68f67147a727fc6171516c54ac33f"
        }
      ]
    }
  ]
}
