{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.0.14.jar",
          "url": "http-1.0.14.jar",
          "size": 104389,
          "sha512": "4b6634fa3cca73d5f1c806112719f786c72c9a20b0e3e3f122f984e0fc6b676abe5256382854af536392c8cbc2159bc01eab6d0ca028a0e8f41e286d248a0a8b",
          "sha256": "ce2737a79e0a4a045f359e02d30dd0621ebb2c16cd2640efb8b79cbcc683c92e",
          "sha1": "e4cfebfcbf130291ace427dc6638485361f1332c",
          "md5": "6c0b27cdc5461c19c32b7a81891b0d16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.0.14.jar",
          "url": "http-1.0.14.jar",
          "size": 104389,
          "sha512": "4b6634fa3cca73d5f1c806112719f786c72c9a20b0e3e3f122f984e0fc6b676abe5256382854af536392c8cbc2159bc01eab6d0ca028a0e8f41e286d248a0a8b",
          "sha256": "ce2737a79e0a4a045f359e02d30dd0621ebb2c16cd2640efb8b79cbcc683c92e",
          "sha1": "e4cfebfcbf130291ace427dc6638485361f1332c",
          "md5": "6c0b27cdc5461c19c32b7a81891b0d16"
        }
      ]
    }
  ]
}
