{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 1337216,
          "sha512": "3943498f1e89099b93fb6787dff70dbebc4a58d4a9751fa82b0cb30d3b494f627bbbd04c32ec13f0beb9b7191dd685efe7d6057115bd1b3b140d4492b1ddff31",
          "sha256": "8eed8777e46a01f717d2dc3b9d0d10176dbdf9877990a9a12e2e7403166b732d",
          "sha1": "ed8000b9efc2e66625d6e933b1837250bff77a6f",
          "md5": "dc3486a4c6c7c181d571ab0cf0a6c409"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 1337216,
          "sha512": "3943498f1e89099b93fb6787dff70dbebc4a58d4a9751fa82b0cb30d3b494f627bbbd04c32ec13f0beb9b7191dd685efe7d6057115bd1b3b140d4492b1ddff31",
          "sha256": "8eed8777e46a01f717d2dc3b9d0d10176dbdf9877990a9a12e2e7403166b732d",
          "sha1": "ed8000b9efc2e66625d6e933b1837250bff77a6f",
          "md5": "dc3486a4c6c7c181d571ab0cf0a6c409"
        }
      ]
    }
  ]
}
