{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.12.jar",
          "url": "annotations-1.6.12.jar",
          "size": 8843,
          "sha512": "489840955d354103065e39bfb9c0a416d603c9a6e7fa919eba38aa4de733bedaca98e1d85766066a40216885c8f802f3d39261647ad63b824b6c3d2d5ec0a5e6",
          "sha256": "49f5f25eada15616167b3245ce691bb324c46e1590721db4e9c2cc48d4a5ee70",
          "sha1": "7773952c7c95fdfd8fdd523b496a7122764b3eb0",
          "md5": "75fc20fedf2261db0450d966c757cd3a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.12.jar",
          "url": "annotations-1.6.12.jar",
          "size": 8843,
          "sha512": "489840955d354103065e39bfb9c0a416d603c9a6e7fa919eba38aa4de733bedaca98e1d85766066a40216885c8f802f3d39261647ad63b824b6c3d2d5ec0a5e6",
          "sha256": "49f5f25eada15616167b3245ce691bb324c46e1590721db4e9c2cc48d4a5ee70",
          "sha1": "7773952c7c95fdfd8fdd523b496a7122764b3eb0",
          "md5": "75fc20fedf2261db0450d966c757cd3a"
        }
      ]
    }
  ]
}
