{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.12.jar",
          "url": "annotations-1.6.12.jar",
          "size": 8843,
          "sha512": "6753b4e34f8e3d5a4feeb1abced312df526ebafd37b7247b5983eba4c9aa88177f70d72f5dec99677f8d43bc79f8a03f8832fb2aeca9e42928e3539fd8ccd335",
          "sha256": "b9e13db0e65d047f2cc8523820c4598febd2030df80cdb37321ade8c0bc28d18",
          "sha1": "83d6129da6ab489b55b2947ff37d8ef18566a9f7",
          "md5": "e80180f055d0aa7c97228ad51e301612"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.12.jar",
          "url": "annotations-1.6.12.jar",
          "size": 8843,
          "sha512": "6753b4e34f8e3d5a4feeb1abced312df526ebafd37b7247b5983eba4c9aa88177f70d72f5dec99677f8d43bc79f8a03f8832fb2aeca9e42928e3539fd8ccd335",
          "sha256": "b9e13db0e65d047f2cc8523820c4598febd2030df80cdb37321ade8c0bc28d18",
          "sha1": "83d6129da6ab489b55b2947ff37d8ef18566a9f7",
          "md5": "e80180f055d0aa7c97228ad51e301612"
        }
      ]
    }
  ]
}
