{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.15.jar",
          "url": "scripts-1.6.15.jar",
          "size": 28428,
          "sha512": "f1ef7befaf57a2e2b0ae601915a9250ce8d654f53b3bba3f6ac8fa886eb685734a21d704502d11cfe623152c2dd1ac7ef1134ebaeebbe8319b7107f42078dc67",
          "sha256": "e6801c6310e1fcd23a362a9d2ed672998ea6a41f033da4c0b9de29ead2ffde6f",
          "sha1": "0705740df4888d22d939ca06f837ab9df0249583",
          "md5": "b4d9eef3a1b68ea799d94a21a22fe48c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.15.jar",
          "url": "scripts-1.6.15.jar",
          "size": 28428,
          "sha512": "f1ef7befaf57a2e2b0ae601915a9250ce8d654f53b3bba3f6ac8fa886eb685734a21d704502d11cfe623152c2dd1ac7ef1134ebaeebbe8319b7107f42078dc67",
          "sha256": "e6801c6310e1fcd23a362a9d2ed672998ea6a41f033da4c0b9de29ead2ffde6f",
          "sha1": "0705740df4888d22d939ca06f837ab9df0249583",
          "md5": "b4d9eef3a1b68ea799d94a21a22fe48c"
        }
      ]
    }
  ]
}
