{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.9.jar",
          "url": "annotations-1.6.9.jar",
          "size": 8843,
          "sha512": "36ab246dc02c6c2089a2cb2e270147a94eaad525dd55afae5cc4164a91ea34a8c549620136b01e87301fffb65352769f883bdc63e40eef54a660c44d56f93b16",
          "sha256": "37f4998a0e17651552c6f8dc9cbb586cb2ab43582cdd226d7a9a7bf5001997fc",
          "sha1": "865e8ab9df41db46402a5d2daa8840421236b762",
          "md5": "4a315a3182978b8869e3f72bf77c078c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.9.jar",
          "url": "annotations-1.6.9.jar",
          "size": 8843,
          "sha512": "36ab246dc02c6c2089a2cb2e270147a94eaad525dd55afae5cc4164a91ea34a8c549620136b01e87301fffb65352769f883bdc63e40eef54a660c44d56f93b16",
          "sha256": "37f4998a0e17651552c6f8dc9cbb586cb2ab43582cdd226d7a9a7bf5001997fc",
          "sha1": "865e8ab9df41db46402a5d2daa8840421236b762",
          "md5": "4a315a3182978b8869e3f72bf77c078c"
        }
      ]
    }
  ]
}
