{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.1.jar",
          "url": "api-1.5.1.jar",
          "size": 1338096,
          "sha512": "05a2d0bae52cac8f580c911626584019afc5f28889b1840e998537922b46291d9bb1bf8bbf913c74c0c304c3169eaeccf16e56b40b6424ee8b362dd4197cc2f0",
          "sha256": "5cbc2e61e31be5676c1a23dd0a29a81b98bce970ed6cd324ca13398607a29f51",
          "sha1": "bace77b8b3eef2c92a18d95f64c70a5c6320a723",
          "md5": "9cf3f024e02d81ad24b5845aa1b26cef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.1.jar",
          "url": "api-1.5.1.jar",
          "size": 1338096,
          "sha512": "05a2d0bae52cac8f580c911626584019afc5f28889b1840e998537922b46291d9bb1bf8bbf913c74c0c304c3169eaeccf16e56b40b6424ee8b362dd4197cc2f0",
          "sha256": "5cbc2e61e31be5676c1a23dd0a29a81b98bce970ed6cd324ca13398607a29f51",
          "sha1": "bace77b8b3eef2c92a18d95f64c70a5c6320a723",
          "md5": "9cf3f024e02d81ad24b5845aa1b26cef"
        }
      ]
    }
  ]
}
