{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.5.jar",
          "url": "api-rs-1.5.5.jar",
          "size": 123367,
          "sha512": "8e99d6224d1169f559dd649d376e4ef11f96f9ebbd21a4b78564391e301dabe798633d607328680eb7d0ad00aecd3479764a0fc4938217e471a8661822a329ee",
          "sha256": "1844c8403562e5efad975b44f8081c42f645d6db162c8190cc2b8e9a58568689",
          "sha1": "9427da3711610e28fd2a673d8b7c0f3090b46215",
          "md5": "4e3ba7d6fd813cbe64ca51fc9a269764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.5.jar",
          "url": "api-rs-1.5.5.jar",
          "size": 123367,
          "sha512": "8e99d6224d1169f559dd649d376e4ef11f96f9ebbd21a4b78564391e301dabe798633d607328680eb7d0ad00aecd3479764a0fc4938217e471a8661822a329ee",
          "sha256": "1844c8403562e5efad975b44f8081c42f645d6db162c8190cc2b8e9a58568689",
          "sha1": "9427da3711610e28fd2a673d8b7c0f3090b46215",
          "md5": "4e3ba7d6fd813cbe64ca51fc9a269764"
        }
      ]
    }
  ]
}
