{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.1.7.jar",
          "url": "annotations-1.1.7.jar",
          "size": 9006,
          "sha512": "b3b090c2025e9f7e42a6d80de89fdda11d34a67fc7e1bd0c923f248901e3e159435d2ddfbbcd078c0c27cc11d6d67b23b1c56cb3a877c0aa2e3eed068e053a97",
          "sha256": "34d13405b1fded02260b546d08e0c460fc6bf4f666f3ab13a8b7be32a727b1f5",
          "sha1": "5d600adda7c97347b7c401f63c4cb52810b71947",
          "md5": "f221e89db84e856819236eaf96011977"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.1.7.jar",
          "url": "annotations-1.1.7.jar",
          "size": 9006,
          "sha512": "b3b090c2025e9f7e42a6d80de89fdda11d34a67fc7e1bd0c923f248901e3e159435d2ddfbbcd078c0c27cc11d6d67b23b1c56cb3a877c0aa2e3eed068e053a97",
          "sha256": "34d13405b1fded02260b546d08e0c460fc6bf4f666f3ab13a8b7be32a727b1f5",
          "sha1": "5d600adda7c97347b7c401f63c4cb52810b71947",
          "md5": "f221e89db84e856819236eaf96011977"
        }
      ]
    }
  ]
}
