{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.1.jar",
          "url": "scripts-1.6.1.jar",
          "size": 31942,
          "sha512": "cd21f10666835bbed5b655e975649bf5047e6538119d2d142b25f2bdfae30eb933a3196deae4cb1f6973330b03d9dda77c04c68ea144130f9d92a3baf179f962",
          "sha256": "6abf3d93d732679670dcd0abc8a8f129c7901a6fcf193fec42d6f4d04d138b02",
          "sha1": "4367395e4dce35a20062125938fa2b78ec0f46cb",
          "md5": "9fe62d4c561e7eb4a2fa34802edd83ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.1.jar",
          "url": "scripts-1.6.1.jar",
          "size": 31942,
          "sha512": "cd21f10666835bbed5b655e975649bf5047e6538119d2d142b25f2bdfae30eb933a3196deae4cb1f6973330b03d9dda77c04c68ea144130f9d92a3baf179f962",
          "sha256": "6abf3d93d732679670dcd0abc8a8f129c7901a6fcf193fec42d6f4d04d138b02",
          "sha1": "4367395e4dce35a20062125938fa2b78ec0f46cb",
          "md5": "9fe62d4c561e7eb4a2fa34802edd83ea"
        }
      ]
    }
  ]
}
