{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 1397796,
          "sha512": "90e6cc6bc1045e0b0e08873d2a53a68e79b3f21a3e03e3f9fc97b906f9da4c5d530ccb5fa3c53e1b0233725ce90e43e7e172a657bb21465d8a873abbe066fc64",
          "sha256": "2672979bf97ebef2a6a968a3d006b85275dbf4ffb9a0f463ab8763775270cdcf",
          "sha1": "015985c96e8427d44db99278213314a1a14db7f1",
          "md5": "fd65c9dbb63f3b54efc5d1e93bb5da7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 1397796,
          "sha512": "90e6cc6bc1045e0b0e08873d2a53a68e79b3f21a3e03e3f9fc97b906f9da4c5d530ccb5fa3c53e1b0233725ce90e43e7e172a657bb21465d8a873abbe066fc64",
          "sha256": "2672979bf97ebef2a6a968a3d006b85275dbf4ffb9a0f463ab8763775270cdcf",
          "sha1": "015985c96e8427d44db99278213314a1a14db7f1",
          "md5": "fd65c9dbb63f3b54efc5d1e93bb5da7b"
        }
      ]
    }
  ]
}
