{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 1397796,
          "sha512": "4f945140a11e6b0d80a36850794a2617c195d4ec67eaaeacfdd36211f94e4252c62b59c664454ad7195fa4ac47dbdf420aada8cc4d507f118efcd75bc0457405",
          "sha256": "2be118bdcba54f9f7bfb64d2e4045d3c8eb26eb4d2ace438da162fe0cb4a61d4",
          "sha1": "05a5927dfe26944a3b7b12bcc178887cf754c8cf",
          "md5": "ad27467fb2b113d7aab0fb208891b7ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.0.jar",
          "url": "api-1.0.0.jar",
          "size": 1397796,
          "sha512": "4f945140a11e6b0d80a36850794a2617c195d4ec67eaaeacfdd36211f94e4252c62b59c664454ad7195fa4ac47dbdf420aada8cc4d507f118efcd75bc0457405",
          "sha256": "2be118bdcba54f9f7bfb64d2e4045d3c8eb26eb4d2ace438da162fe0cb4a61d4",
          "sha1": "05a5927dfe26944a3b7b12bcc178887cf754c8cf",
          "md5": "ad27467fb2b113d7aab0fb208891b7ea"
        }
      ]
    }
  ]
}
