{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.5.0.jar",
          "url": "scripts-1.5.0.jar",
          "size": 31947,
          "sha512": "9e1f399c65f5afd045dbb135a19df724410f26f7d6bff1f2729c58a53ea25924e6cbef165ae3682e6468ea299cc0d35c090fb211f3334436d169dc68cf938be6",
          "sha256": "729d73cd2c32d2aa254c0b77f8969c69a9e116a3761d587a88757ee7255d6a03",
          "sha1": "de36bfc229a822f7b48ad147d918b3d517cb5d74",
          "md5": "f0a20e94d93a3e44d2830f9cab84cbec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.5.0.jar",
          "url": "scripts-1.5.0.jar",
          "size": 31947,
          "sha512": "9e1f399c65f5afd045dbb135a19df724410f26f7d6bff1f2729c58a53ea25924e6cbef165ae3682e6468ea299cc0d35c090fb211f3334436d169dc68cf938be6",
          "sha256": "729d73cd2c32d2aa254c0b77f8969c69a9e116a3761d587a88757ee7255d6a03",
          "sha1": "de36bfc229a822f7b48ad147d918b3d517cb5d74",
          "md5": "f0a20e94d93a3e44d2830f9cab84cbec"
        }
      ]
    }
  ]
}
