{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.2.jar",
          "url": "scripts-1.6.2.jar",
          "size": 28428,
          "sha512": "6a139e17247122453dbff917c955304e91c893d88d23435b3fa917b94d8f7d327fa17118a64a82f861dc3a2c37e402bb2d1c46ab718621e0d5f5fd7e8381f213",
          "sha256": "2c71dada7f796f65dc24ef8aff21d5219de30c10312ae38a11797df106765a79",
          "sha1": "e88cc3872e21c5307b0e98a5e3e1a661c1f00e14",
          "md5": "464d0c573a5022c83499a4e0e6126f87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.2.jar",
          "url": "scripts-1.6.2.jar",
          "size": 28428,
          "sha512": "6a139e17247122453dbff917c955304e91c893d88d23435b3fa917b94d8f7d327fa17118a64a82f861dc3a2c37e402bb2d1c46ab718621e0d5f5fd7e8381f213",
          "sha256": "2c71dada7f796f65dc24ef8aff21d5219de30c10312ae38a11797df106765a79",
          "sha1": "e88cc3872e21c5307b0e98a5e3e1a661c1f00e14",
          "md5": "464d0c573a5022c83499a4e0e6126f87"
        }
      ]
    }
  ]
}
