{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.2.jar",
          "url": "scripts-1.6.2.jar",
          "size": 28428,
          "sha512": "d2bfe0013b449f07d89aa73483f6787d617d968f160f979967ba377b1f50770474882df3cca91ad417f887a53260fa51ccfa7eec5e132d4e6ebb4c94fb155886",
          "sha256": "1265dd82b50f715f3c2615915b96e9ebf115aaa4af90affd7b785e616d4d1428",
          "sha1": "9067075f4ac99ec38951f4eac07139f8e2fd80fb",
          "md5": "f92f803356ba6f8dcd018d1f87553bf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.2.jar",
          "url": "scripts-1.6.2.jar",
          "size": 28428,
          "sha512": "d2bfe0013b449f07d89aa73483f6787d617d968f160f979967ba377b1f50770474882df3cca91ad417f887a53260fa51ccfa7eec5e132d4e6ebb4c94fb155886",
          "sha256": "1265dd82b50f715f3c2615915b96e9ebf115aaa4af90affd7b785e616d4d1428",
          "sha1": "9067075f4ac99ec38951f4eac07139f8e2fd80fb",
          "md5": "f92f803356ba6f8dcd018d1f87553bf3"
        }
      ]
    }
  ]
}
