{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-2.0.0.jar",
          "url": "api-rs-2.0.0.jar",
          "size": 122412,
          "sha512": "d97dd2b908573b646b820493dcbbb50fc7b18f81768b5b8a057a815af3df6714a5ee87ebe4bfef34e2fce60c9bafcf49f25936d2c6754323ccdf0c0816991e7d",
          "sha256": "49341d00ce67aa3f42a700dd2f291c3c49c8103cec80ab5e7f8ab98810e34ec7",
          "sha1": "2e4ea24d562c8f9df4cef502da8f08213a438629",
          "md5": "7c6d325a4f253bcd8a008916ad50fae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-2.0.0.jar",
          "url": "api-rs-2.0.0.jar",
          "size": 122412,
          "sha512": "d97dd2b908573b646b820493dcbbb50fc7b18f81768b5b8a057a815af3df6714a5ee87ebe4bfef34e2fce60c9bafcf49f25936d2c6754323ccdf0c0816991e7d",
          "sha256": "49341d00ce67aa3f42a700dd2f291c3c49c8103cec80ab5e7f8ab98810e34ec7",
          "sha1": "2e4ea24d562c8f9df4cef502da8f08213a438629",
          "md5": "7c6d325a4f253bcd8a008916ad50fae6"
        }
      ]
    }
  ]
}
