{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.1.jar",
          "url": "api-rs-1.6.1.jar",
          "size": 123317,
          "sha512": "6c636158daef28b59c343ae6887dd2ae7637e371c90c39453f2a11ac550da3f6d17a73d3c7daab7197fa1e1f078e3d060efe41a7fdfa525fe43e1f75ce36434f",
          "sha256": "28b6e7d65ee8f7689a462ceae8c979725c6175cfc554b07faa6532c57f4d806f",
          "sha1": "8ce1bdb01ae2bbef85707265a0dd4dbf15f77753",
          "md5": "5a52dfbce06431cea517809df2b9a30b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.1.jar",
          "url": "api-rs-1.6.1.jar",
          "size": 123317,
          "sha512": "6c636158daef28b59c343ae6887dd2ae7637e371c90c39453f2a11ac550da3f6d17a73d3c7daab7197fa1e1f078e3d060efe41a7fdfa525fe43e1f75ce36434f",
          "sha256": "28b6e7d65ee8f7689a462ceae8c979725c6175cfc554b07faa6532c57f4d806f",
          "sha1": "8ce1bdb01ae2bbef85707265a0dd4dbf15f77753",
          "md5": "5a52dfbce06431cea517809df2b9a30b"
        }
      ]
    }
  ]
}
