{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.6.jar",
          "url": "api-rs-1.5.6.jar",
          "size": 123367,
          "sha512": "3f961f9f6d89cd91538780559e646e05d227b5f1429b2ed38414d3939e26adaebd7fe3b309a9357d1552ce1124d1234d7e1264642882f40813aef34ed49ade42",
          "sha256": "26f4a92ae9b5d071509f478e9cbc3192985f31a9304a00b5ca1d56d719d3fc77",
          "sha1": "2d73d67800a025a65e1361ebcc5ff03eec4f7afb",
          "md5": "a0c9d4007d5a469f6734f758359c4e7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.6.jar",
          "url": "api-rs-1.5.6.jar",
          "size": 123367,
          "sha512": "3f961f9f6d89cd91538780559e646e05d227b5f1429b2ed38414d3939e26adaebd7fe3b309a9357d1552ce1124d1234d7e1264642882f40813aef34ed49ade42",
          "sha256": "26f4a92ae9b5d071509f478e9cbc3192985f31a9304a00b5ca1d56d719d3fc77",
          "sha1": "2d73d67800a025a65e1361ebcc5ff03eec4f7afb",
          "md5": "a0c9d4007d5a469f6734f758359c4e7e"
        }
      ]
    }
  ]
}
