{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.7.jar",
          "url": "annotations-1.6.7.jar",
          "size": 8843,
          "sha512": "e521011f1fa156b5d821b1bcef9400a9071012cc8a6c0b0395664169209771de964e0dabeafc3d0096552889c07dac99a9cce4c83ae60d6936ac9075a22f4101",
          "sha256": "10f0b886b23bf3fc6a2fa28decb4154f1fbb2e2ddb9382ec4554e3ceed2197f0",
          "sha1": "b77ed17864431910bf497e68e1f49c3e4e4816de",
          "md5": "14ac252227bbc124be6df3143121a9ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.7.jar",
          "url": "annotations-1.6.7.jar",
          "size": 8843,
          "sha512": "e521011f1fa156b5d821b1bcef9400a9071012cc8a6c0b0395664169209771de964e0dabeafc3d0096552889c07dac99a9cce4c83ae60d6936ac9075a22f4101",
          "sha256": "10f0b886b23bf3fc6a2fa28decb4154f1fbb2e2ddb9382ec4554e3ceed2197f0",
          "sha1": "b77ed17864431910bf497e68e1f49c3e4e4816de",
          "md5": "14ac252227bbc124be6df3143121a9ce"
        }
      ]
    }
  ]
}
