{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.6.jar",
          "url": "api-rs-1.6.6.jar",
          "size": 123365,
          "sha512": "b61140d40d4ec8ebacdc52b38d10709b196ee6e72aba01f1094f0f236f0aa701c25c6f4d1b1ad72b61a363e5a0e23981fa80b95c52ccf9fd80843f54d045dd1f",
          "sha256": "fe8ea14405fe3f35c26ed0e1bc73ecac91574701a0fc624da8384849754acf9f",
          "sha1": "6e1aeffc77ff324e893b78ca31ff87cd5a1a9dc9",
          "md5": "ef3b575b1c3347fe4183331041e3f349"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.6.jar",
          "url": "api-rs-1.6.6.jar",
          "size": 123365,
          "sha512": "b61140d40d4ec8ebacdc52b38d10709b196ee6e72aba01f1094f0f236f0aa701c25c6f4d1b1ad72b61a363e5a0e23981fa80b95c52ccf9fd80843f54d045dd1f",
          "sha256": "fe8ea14405fe3f35c26ed0e1bc73ecac91574701a0fc624da8384849754acf9f",
          "sha1": "6e1aeffc77ff324e893b78ca31ff87cd5a1a9dc9",
          "md5": "ef3b575b1c3347fe4183331041e3f349"
        }
      ]
    }
  ]
}
