{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.9.jar",
          "url": "api-1.2.9.jar",
          "size": 1339677,
          "sha512": "5e87c118768412a1a00b59dd1e434931a3c0efdc8ed49b99167aa4f158f18af7f128835a0e288af70d8f4c1249baec6378570ab40fd6a327b04c0d1f1ca672e1",
          "sha256": "59ad8eb94c6f3840c8a73f4786514bea331e8de21569c1de0ef6eea6d05cda14",
          "sha1": "55b2452189dbf57e0244f42f54b2cb007bd0a6de",
          "md5": "8de2d2ed1672b66a12113216f588fa32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.9.jar",
          "url": "api-1.2.9.jar",
          "size": 1339677,
          "sha512": "5e87c118768412a1a00b59dd1e434931a3c0efdc8ed49b99167aa4f158f18af7f128835a0e288af70d8f4c1249baec6378570ab40fd6a327b04c0d1f1ca672e1",
          "sha256": "59ad8eb94c6f3840c8a73f4786514bea331e8de21569c1de0ef6eea6d05cda14",
          "sha1": "55b2452189dbf57e0244f42f54b2cb007bd0a6de",
          "md5": "8de2d2ed1672b66a12113216f588fa32"
        }
      ]
    }
  ]
}
