{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.10.jar",
          "url": "api-rs-1.6.10.jar",
          "size": 123830,
          "sha512": "d1595e9bc6107c6969a445a91b8891f79cadca80d0df9a2591169cc6a6d03fbf4a57c7e408ea436b08bb7c5c2fe23e3bb06ae6a948686fd1f30d2932010e4f8b",
          "sha256": "c3f60879ca3dcd9c5342504db0e3334966c59df2bfe290087f06ae09eb7c184b",
          "sha1": "5446b4a6bf836aa2edbdf121f610b41e247e5db5",
          "md5": "c224faef850225857b48133ea6d53077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.10.jar",
          "url": "api-rs-1.6.10.jar",
          "size": 123830,
          "sha512": "d1595e9bc6107c6969a445a91b8891f79cadca80d0df9a2591169cc6a6d03fbf4a57c7e408ea436b08bb7c5c2fe23e3bb06ae6a948686fd1f30d2932010e4f8b",
          "sha256": "c3f60879ca3dcd9c5342504db0e3334966c59df2bfe290087f06ae09eb7c184b",
          "sha1": "5446b4a6bf836aa2edbdf121f610b41e247e5db5",
          "md5": "c224faef850225857b48133ea6d53077"
        }
      ]
    }
  ]
}
