{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-0.0.0.jar",
          "url": "api-rs-0.0.0.jar",
          "size": 122412,
          "sha512": "7db3bd4f9e0cf652c3522de0e861c13075f95303e9052b03ca8f7d526d4d6fdbafca9ed3a585d8f0c3b5f395538925b2db9da98debbf1aad040f9608d4eb63db",
          "sha256": "863fea8d3af5e5e2c3022a6978a6521b9c4b09806e6c67866bd7a50693e2efc3",
          "sha1": "b911ac84e1175796495eec10235fe3a16de874a9",
          "md5": "3de2b6c7226cafb75ee3104ee33d5995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-0.0.0.jar",
          "url": "api-rs-0.0.0.jar",
          "size": 122412,
          "sha512": "7db3bd4f9e0cf652c3522de0e861c13075f95303e9052b03ca8f7d526d4d6fdbafca9ed3a585d8f0c3b5f395538925b2db9da98debbf1aad040f9608d4eb63db",
          "sha256": "863fea8d3af5e5e2c3022a6978a6521b9c4b09806e6c67866bd7a50693e2efc3",
          "sha1": "b911ac84e1175796495eec10235fe3a16de874a9",
          "md5": "3de2b6c7226cafb75ee3104ee33d5995"
        }
      ]
    }
  ]
}
