{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-0.0.0.jar",
          "url": "api-rs-0.0.0.jar",
          "size": 122412,
          "sha512": "8adb06d5f517051965341eaee51d20c99ebb976874d5da31044c2923450151ce8bf4916165e20414d260c9155ea0d2385d1b110443b98326cbab9466b21f2c8c",
          "sha256": "1ff8bc893e97ee7e70872a57a2bbd2e273509896590d84dcc8a96db734a328da",
          "sha1": "4aec543453c609015c089e085e3e6f1722638709",
          "md5": "c7d4514b293dc1921c017afe5987b6f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-0.0.0.jar",
          "url": "api-rs-0.0.0.jar",
          "size": 122412,
          "sha512": "8adb06d5f517051965341eaee51d20c99ebb976874d5da31044c2923450151ce8bf4916165e20414d260c9155ea0d2385d1b110443b98326cbab9466b21f2c8c",
          "sha256": "1ff8bc893e97ee7e70872a57a2bbd2e273509896590d84dcc8a96db734a328da",
          "sha1": "4aec543453c609015c089e085e3e6f1722638709",
          "md5": "c7d4514b293dc1921c017afe5987b6f7"
        }
      ]
    }
  ]
}
