{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.8.jar",
          "url": "api-1.6.8.jar",
          "size": 1338276,
          "sha512": "1a3224d2d76a6b9745e83cbaf434d59b411b7f800640e870294446c9b4197ae3b773df6c5fa5b8335444a23864ab3dd81bdd63240c40ebc8cc258ce8fa030fd2",
          "sha256": "b1b180ffaf2a88064c611880dae146e8f1b65a391c0fd2d25560cb93f52bbed1",
          "sha1": "3b71b85a06efd8491fb2bf2fbcc67d706be8dc49",
          "md5": "bbf25c4bdba123349d193cad32c7ced8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.8.jar",
          "url": "api-1.6.8.jar",
          "size": 1338276,
          "sha512": "1a3224d2d76a6b9745e83cbaf434d59b411b7f800640e870294446c9b4197ae3b773df6c5fa5b8335444a23864ab3dd81bdd63240c40ebc8cc258ce8fa030fd2",
          "sha256": "b1b180ffaf2a88064c611880dae146e8f1b65a391c0fd2d25560cb93f52bbed1",
          "sha1": "3b71b85a06efd8491fb2bf2fbcc67d706be8dc49",
          "md5": "bbf25c4bdba123349d193cad32c7ced8"
        }
      ]
    }
  ]
}
