{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.2.7.jar",
          "url": "api-rs-1.2.7.jar",
          "size": 122508,
          "sha512": "b3b7ebf63ee19b7ca63a60e7547bb5159bb541167359bc7f89d58c5b6bbb4af26e51cfce9e7688810c2fcefc71f0f64ce0163c04ec3cd26e9f73519729e00100",
          "sha256": "16e507649871201708c01dec8af1ffa18914b3662e515ef4b66d510582bb0f81",
          "sha1": "225ced6010f468016c8d333c54fa263f6071eac1",
          "md5": "cfa82c46d4fb95a75714520992378233"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.7.jar",
          "url": "api-rs-1.2.7.jar",
          "size": 122508,
          "sha512": "b3b7ebf63ee19b7ca63a60e7547bb5159bb541167359bc7f89d58c5b6bbb4af26e51cfce9e7688810c2fcefc71f0f64ce0163c04ec3cd26e9f73519729e00100",
          "sha256": "16e507649871201708c01dec8af1ffa18914b3662e515ef4b66d510582bb0f81",
          "sha1": "225ced6010f468016c8d333c54fa263f6071eac1",
          "md5": "cfa82c46d4fb95a75714520992378233"
        }
      ]
    }
  ]
}
