{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.2.12.jar",
          "url": "api-rs-1.2.12.jar",
          "size": 122394,
          "sha512": "3803ddd89d049583d8e50f8f576cb59f0f8725c779eae13c6f73f7a55bde5fbf09e495a194fb68d537e0c00f55605583df54a84606b9c95685e68639c749d294",
          "sha256": "dee6d93e68111f2515c059984afd1729c115adbd4404de21d5570e0e0e71cda9",
          "sha1": "7a622e2e4d384a88ecccb046a3017034cbb0d2c6",
          "md5": "928f3eeb41a279e1ead3d731cf8fb3eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.12.jar",
          "url": "api-rs-1.2.12.jar",
          "size": 122394,
          "sha512": "3803ddd89d049583d8e50f8f576cb59f0f8725c779eae13c6f73f7a55bde5fbf09e495a194fb68d537e0c00f55605583df54a84606b9c95685e68639c749d294",
          "sha256": "dee6d93e68111f2515c059984afd1729c115adbd4404de21d5570e0e0e71cda9",
          "sha1": "7a622e2e4d384a88ecccb046a3017034cbb0d2c6",
          "md5": "928f3eeb41a279e1ead3d731cf8fb3eb"
        }
      ]
    }
  ]
}
