{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.6.jar",
          "url": "api-rs-1.4.6.jar",
          "size": 122412,
          "sha512": "534d4106c4600ac1ff8402d4d271eef81f899236b28ecbf73306098da0831f22f8b02ebe74e4269f1a2f1788bf610faa005fb916041abec2097fdf743aa2de8e",
          "sha256": "9d9fc8e856b894becf7f5703437ac90b1b27fdacd655ef894f3d46224b7b5032",
          "sha1": "6d98ed4dfbddfed86629a0187fd342bbe590555c",
          "md5": "329143529ddf0fac7272d75c35b7071c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.6.jar",
          "url": "api-rs-1.4.6.jar",
          "size": 122412,
          "sha512": "534d4106c4600ac1ff8402d4d271eef81f899236b28ecbf73306098da0831f22f8b02ebe74e4269f1a2f1788bf610faa005fb916041abec2097fdf743aa2de8e",
          "sha256": "9d9fc8e856b894becf7f5703437ac90b1b27fdacd655ef894f3d46224b7b5032",
          "sha1": "6d98ed4dfbddfed86629a0187fd342bbe590555c",
          "md5": "329143529ddf0fac7272d75c35b7071c"
        }
      ]
    }
  ]
}
