{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.5.6.jar",
          "url": "annotations-1.5.6.jar",
          "size": 8843,
          "sha512": "33ebb1894ecab85b27862f04788e2f2663badb4f96b9286ce11c48993b03708fd99c21747485113000dbd70c5f9350afebb6a838fd8314cf6c09989fb6bed987",
          "sha256": "64a22f01367dbcffd5216463e01e503ea1f42302d4aec1881b998502b2b5c8e6",
          "sha1": "7296d3e93382139740ea3497df64642b2b38d452",
          "md5": "52e504602f38bad8cceba2908fadeb16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.5.6.jar",
          "url": "annotations-1.5.6.jar",
          "size": 8843,
          "sha512": "33ebb1894ecab85b27862f04788e2f2663badb4f96b9286ce11c48993b03708fd99c21747485113000dbd70c5f9350afebb6a838fd8314cf6c09989fb6bed987",
          "sha256": "64a22f01367dbcffd5216463e01e503ea1f42302d4aec1881b998502b2b5c8e6",
          "sha1": "7296d3e93382139740ea3497df64642b2b38d452",
          "md5": "52e504602f38bad8cceba2908fadeb16"
        }
      ]
    }
  ]
}
