{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.12.jar",
          "url": "scripts-1.6.12.jar",
          "size": 28428,
          "sha512": "7033cddffcbf457c7614744ebbb3c0b69faca069548b88e811edf830bd2731a717e040a507e069e3d093faa50f76843bc7ed408b952e6a4bbceea65e4f41d922",
          "sha256": "12a357098fcbb42b4145622732755348db6c98cd66b7e7056304ea3fab5f0771",
          "sha1": "0eec86c74b7f3da796bc77bd223ae7844ce2449b",
          "md5": "2fb6346e3bcf22dfe9c807925db42377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.12.jar",
          "url": "scripts-1.6.12.jar",
          "size": 28428,
          "sha512": "7033cddffcbf457c7614744ebbb3c0b69faca069548b88e811edf830bd2731a717e040a507e069e3d093faa50f76843bc7ed408b952e6a4bbceea65e4f41d922",
          "sha256": "12a357098fcbb42b4145622732755348db6c98cd66b7e7056304ea3fab5f0771",
          "sha1": "0eec86c74b7f3da796bc77bd223ae7844ce2449b",
          "md5": "2fb6346e3bcf22dfe9c807925db42377"
        }
      ]
    }
  ]
}
