{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.8.jar",
          "url": "api-1.4.8.jar",
          "size": 1338096,
          "sha512": "02ce8c5e51f987d62b9d131cf9dfa1d73036f9d497e0fdd3ef563b4f16714593c181dc0e8f60173042c75828ae3d428f97a9c087ba5859611a16bfc4c66224b0",
          "sha256": "f266cf824f4a7ea8d344c0f3ac7d4f2c6917b19a2d380a415fe24b38dd20e35f",
          "sha1": "8d0c8eea4c8f57e440b5cac27b316acdf81e028c",
          "md5": "705a8fb0380f5891c1f8848e768bfee7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.8.jar",
          "url": "api-1.4.8.jar",
          "size": 1338096,
          "sha512": "02ce8c5e51f987d62b9d131cf9dfa1d73036f9d497e0fdd3ef563b4f16714593c181dc0e8f60173042c75828ae3d428f97a9c087ba5859611a16bfc4c66224b0",
          "sha256": "f266cf824f4a7ea8d344c0f3ac7d4f2c6917b19a2d380a415fe24b38dd20e35f",
          "sha1": "8d0c8eea4c8f57e440b5cac27b316acdf81e028c",
          "md5": "705a8fb0380f5891c1f8848e768bfee7"
        }
      ]
    }
  ]
}
