{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.8.jar",
          "url": "api-1.4.8.jar",
          "size": 1338053,
          "sha512": "b31989ffbc3699ec91c3cf0d7723ebe268fce8db709b4112c15b6a6a121133a1ebcf3be63666bcfbbad31d593b508b1db129dc9800262a7dcfe7141c915cf07f",
          "sha256": "f8b6c35194ed0580a7cdbb155b8b1e81cdf96599f1898aa69b67519b4b0e2df9",
          "sha1": "81f0779f70de0b27c855164fb3644f530e05fb8f",
          "md5": "99bcef54ba08a4e63c74f7fc87043e2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.8.jar",
          "url": "api-1.4.8.jar",
          "size": 1338053,
          "sha512": "b31989ffbc3699ec91c3cf0d7723ebe268fce8db709b4112c15b6a6a121133a1ebcf3be63666bcfbbad31d593b508b1db129dc9800262a7dcfe7141c915cf07f",
          "sha256": "f8b6c35194ed0580a7cdbb155b8b1e81cdf96599f1898aa69b67519b4b0e2df9",
          "sha1": "81f0779f70de0b27c855164fb3644f530e05fb8f",
          "md5": "99bcef54ba08a4e63c74f7fc87043e2b"
        }
      ]
    }
  ]
}
