{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-2.0.0.jar",
          "url": "http-2.0.0.jar",
          "size": 104410,
          "sha512": "989799a099566d33f176931350d8350d6eed2c5054cf7357679a81b4ac6cb54d8d8eee0afe9a1fc7aa5030cee84266cb413215edda8a106a64b339d52ce8f0e5",
          "sha256": "8f12453a60a18162612ac72870da79f24fe323ca27fe92fb1ddfaa1ff9c809c6",
          "sha1": "64ff859f31381c31fe5027638b9b15431010e5e5",
          "md5": "db67ab70a5ad687597276321b0ded181"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-2.0.0.jar",
          "url": "http-2.0.0.jar",
          "size": 104410,
          "sha512": "989799a099566d33f176931350d8350d6eed2c5054cf7357679a81b4ac6cb54d8d8eee0afe9a1fc7aa5030cee84266cb413215edda8a106a64b339d52ce8f0e5",
          "sha256": "8f12453a60a18162612ac72870da79f24fe323ca27fe92fb1ddfaa1ff9c809c6",
          "sha1": "64ff859f31381c31fe5027638b9b15431010e5e5",
          "md5": "db67ab70a5ad687597276321b0ded181"
        }
      ]
    }
  ]
}
