{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.2.13.jar",
          "url": "annotations-1.2.13.jar",
          "size": 8843,
          "sha512": "2e65e5af7794ed45976d7324d9bdf18e7b28b55a19cfd72bcc6dc150a091a0d51f6a65a47a34b90b73aa72efc801b3e29d6b80a928af9d48345e8bd9d0ddcbbb",
          "sha256": "6ca8bbb5ae7a9392ef3e59ebab1d1d230c6aee68ace0bdfd58e9011bc1fdb5fa",
          "sha1": "0743e7566773229daf713ed815dbbf18eadf9874",
          "md5": "94cbda0a5d1202cb4c8ac6513c3ad43b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.2.13.jar",
          "url": "annotations-1.2.13.jar",
          "size": 8843,
          "sha512": "2e65e5af7794ed45976d7324d9bdf18e7b28b55a19cfd72bcc6dc150a091a0d51f6a65a47a34b90b73aa72efc801b3e29d6b80a928af9d48345e8bd9d0ddcbbb",
          "sha256": "6ca8bbb5ae7a9392ef3e59ebab1d1d230c6aee68ace0bdfd58e9011bc1fdb5fa",
          "sha1": "0743e7566773229daf713ed815dbbf18eadf9874",
          "md5": "94cbda0a5d1202cb4c8ac6513c3ad43b"
        }
      ]
    }
  ]
}
