{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.14.jar",
          "url": "scripts-1.6.14.jar",
          "size": 28428,
          "sha512": "ea834d3b000fb5baa4db8b6739e7df65d129d3751cfa07ca9b00209362be730429fcf8b7266d08de454c15bff475e12e81e7b6e25134ce74e07f41ef28f753a1",
          "sha256": "d1888325f06d8b498327ce708eb3c72e8fd4ddc1005487b9420f2bb791690d33",
          "sha1": "748f61afdce8d21ec234f196e79a9b3502a863f9",
          "md5": "a4a0efa8e380efab16cecd01ff689611"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.14.jar",
          "url": "scripts-1.6.14.jar",
          "size": 28428,
          "sha512": "ea834d3b000fb5baa4db8b6739e7df65d129d3751cfa07ca9b00209362be730429fcf8b7266d08de454c15bff475e12e81e7b6e25134ce74e07f41ef28f753a1",
          "sha256": "d1888325f06d8b498327ce708eb3c72e8fd4ddc1005487b9420f2bb791690d33",
          "sha1": "748f61afdce8d21ec234f196e79a9b3502a863f9",
          "md5": "a4a0efa8e380efab16cecd01ff689611"
        }
      ]
    }
  ]
}
