{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.0.6.jar",
          "url": "api-rs-1.0.6.jar",
          "size": 116671,
          "sha512": "8a60c0c5040bfd64eb3e01c4f40b4c36707ad2f1c1c7b62bf03924602824a9061d3aca6d7ddb346cc6a532032a44000be1453be68c73e9886afc18fa5795194f",
          "sha256": "606326a9076dbd84348347bffb4833ee3c43640c6dbf590b79b2d845e5ca55f8",
          "sha1": "0453bb720c3139ad50ade44dcda5731a4c4a80c8",
          "md5": "a24d9f3f92fcffdb696973478496eb5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.0.6.jar",
          "url": "api-rs-1.0.6.jar",
          "size": 116671,
          "sha512": "8a60c0c5040bfd64eb3e01c4f40b4c36707ad2f1c1c7b62bf03924602824a9061d3aca6d7ddb346cc6a532032a44000be1453be68c73e9886afc18fa5795194f",
          "sha256": "606326a9076dbd84348347bffb4833ee3c43640c6dbf590b79b2d845e5ca55f8",
          "sha1": "0453bb720c3139ad50ade44dcda5731a4c4a80c8",
          "md5": "a24d9f3f92fcffdb696973478496eb5a"
        }
      ]
    }
  ]
}
