{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.1.jar",
          "url": "annotations-1.6.1.jar",
          "size": 8843,
          "sha512": "dae9f60a79fdf6ed1a75676695d1006d2bdd559425e1bf634c37a9a2eeb83174f25a8249233af5c548b29afcb984ed1c4ad8127631df80fa5d3c4db13b994ddc",
          "sha256": "8d66fe63f7fc8fb751570cf9f118d627cb0da9bdf74a1707336ebfe356ae6d5b",
          "sha1": "99a117d8fcd4ee77877f399b87c3f5d10efbdcdb",
          "md5": "c44b2af83bdac176909a3ea49f324f75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.1.jar",
          "url": "annotations-1.6.1.jar",
          "size": 8843,
          "sha512": "dae9f60a79fdf6ed1a75676695d1006d2bdd559425e1bf634c37a9a2eeb83174f25a8249233af5c548b29afcb984ed1c4ad8127631df80fa5d3c4db13b994ddc",
          "sha256": "8d66fe63f7fc8fb751570cf9f118d627cb0da9bdf74a1707336ebfe356ae6d5b",
          "sha1": "99a117d8fcd4ee77877f399b87c3f5d10efbdcdb",
          "md5": "c44b2af83bdac176909a3ea49f324f75"
        }
      ]
    }
  ]
}
