{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.4.8.jar",
          "url": "logger-1.4.8.jar",
          "size": 8658,
          "sha512": "6cd3987293bcf4166f0f0c55652c63007a1e598e7f7ddca4f627cc1c60cd1ffa6116d8aed230dc4a82ebdd64387bb7c735c88f95d00d72288fd32abd3278c3f4",
          "sha256": "019e74f5ffcb8770e6fccd6a2a08ac51cb7c59941f1fce661d96a1a8656a2db6",
          "sha1": "c152f490da1b164456705f076e8b894cee1df590",
          "md5": "cdce58f03bdcad902bc5deb6bb8247c0"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.4.8.jar",
          "url": "logger-1.4.8.jar",
          "size": 8658,
          "sha512": "6cd3987293bcf4166f0f0c55652c63007a1e598e7f7ddca4f627cc1c60cd1ffa6116d8aed230dc4a82ebdd64387bb7c735c88f95d00d72288fd32abd3278c3f4",
          "sha256": "019e74f5ffcb8770e6fccd6a2a08ac51cb7c59941f1fce661d96a1a8656a2db6",
          "sha1": "c152f490da1b164456705f076e8b894cee1df590",
          "md5": "cdce58f03bdcad902bc5deb6bb8247c0"
        }
      ]
    }
  ]
}
