{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.4.0.jar",
          "url": "http-1.4.0.jar",
          "size": 104410,
          "sha512": "f003da264709798af7824c1290a32347f3f70d59e525db96f9cbc5f6759185b68ae00213dae993d876f426d70bbf77267dbf49331292cc6ce613b27e3cd3abbe",
          "sha256": "d213a251b08b6caffd33cbdd8a3e861c44dcacc5afc054e2628da205e07c47e7",
          "sha1": "c0c5556c4880b84b1be1bc59a51c61931e88e8a1",
          "md5": "6538967f116bf1bcffc5e56a591d788f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.4.0.jar",
          "url": "http-1.4.0.jar",
          "size": 104410,
          "sha512": "f003da264709798af7824c1290a32347f3f70d59e525db96f9cbc5f6759185b68ae00213dae993d876f426d70bbf77267dbf49331292cc6ce613b27e3cd3abbe",
          "sha256": "d213a251b08b6caffd33cbdd8a3e861c44dcacc5afc054e2628da205e07c47e7",
          "sha1": "c0c5556c4880b84b1be1bc59a51c61931e88e8a1",
          "md5": "6538967f116bf1bcffc5e56a591d788f"
        }
      ]
    }
  ]
}
