{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.13.jar",
          "url": "api-1.0.13.jar",
          "size": 1292395,
          "sha512": "f5ddca04bb8d969a3c669c3f1f766a9d02b32f7cf96c552f297e5da898025daa672be5f40384ac2cb49c9a82db11d530a84129ad1c2674b6456306a23f9fdca3",
          "sha256": "9bd708d96e0ba79847c9998c4c1bf3307cf7228ef135699e7c4bcb2fba5e6b48",
          "sha1": "a5d7979836c494a3ca0ff4e4fcc5640d8f6f4d7d",
          "md5": "089d12bd518ee94d7abf49d3a150eae0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.13"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.13"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.13.jar",
          "url": "api-1.0.13.jar",
          "size": 1292395,
          "sha512": "f5ddca04bb8d969a3c669c3f1f766a9d02b32f7cf96c552f297e5da898025daa672be5f40384ac2cb49c9a82db11d530a84129ad1c2674b6456306a23f9fdca3",
          "sha256": "9bd708d96e0ba79847c9998c4c1bf3307cf7228ef135699e7c4bcb2fba5e6b48",
          "sha1": "a5d7979836c494a3ca0ff4e4fcc5640d8f6f4d7d",
          "md5": "089d12bd518ee94d7abf49d3a150eae0"
        }
      ]
    }
  ]
}
