{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.7.jar",
          "url": "api-1.4.7.jar",
          "size": 1338053,
          "sha512": "2e42cf67d13435720447c8763f6f14eef8d6d0b3f8b3ca1e659cd9918d7cddad8548635e39eeb5e347fcc54f53fdcb993726615be2fb9920ac29734542e46826",
          "sha256": "b7336d55998abaec0a08e2b956db07a3203f9c33127f6c20bf82733cec82b7c1",
          "sha1": "cdf08a71428c431321fa5c4deb9f0755d04eb1fc",
          "md5": "6af88d65de38219680cf2534ca81bff3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.7.jar",
          "url": "api-1.4.7.jar",
          "size": 1338053,
          "sha512": "2e42cf67d13435720447c8763f6f14eef8d6d0b3f8b3ca1e659cd9918d7cddad8548635e39eeb5e347fcc54f53fdcb993726615be2fb9920ac29734542e46826",
          "sha256": "b7336d55998abaec0a08e2b956db07a3203f9c33127f6c20bf82733cec82b7c1",
          "sha1": "cdf08a71428c431321fa5c4deb9f0755d04eb1fc",
          "md5": "6af88d65de38219680cf2534ca81bff3"
        }
      ]
    }
  ]
}
