{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-2.4.0.jar",
          "url": "api-2.4.0.jar",
          "size": 1338056,
          "sha512": "5f30eb09c067017cbfddc10df44aac4bfe13e25a60904cc026d673aa1244552df40634a708d5d2f8bc3fcbb43c500965ffadeadc96c1d1d15fd869d1124b37eb",
          "sha256": "94b5575a56f361133d0c41e8479704785770ebc04d48240fad295e0b59d04966",
          "sha1": "eb0f522b8e2ff523e86f6c5e4d151f061b012789",
          "md5": "9a76f31ba0da38156d62292f3d85773b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-2.4.0.jar",
          "url": "api-2.4.0.jar",
          "size": 1338056,
          "sha512": "5f30eb09c067017cbfddc10df44aac4bfe13e25a60904cc026d673aa1244552df40634a708d5d2f8bc3fcbb43c500965ffadeadc96c1d1d15fd869d1124b37eb",
          "sha256": "94b5575a56f361133d0c41e8479704785770ebc04d48240fad295e0b59d04966",
          "sha1": "eb0f522b8e2ff523e86f6c5e4d151f061b012789",
          "md5": "9a76f31ba0da38156d62292f3d85773b"
        }
      ]
    }
  ]
}
