{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.8.jar",
          "url": "api-1.0.8.jar",
          "size": 1291030,
          "sha512": "e1d9414e444d7894d49e13c64a599da433a874cd9b21c0c4c74600ec1889becbed3dfd2e954d3fa308d077b3c90c21f1851f8b546abf0fcc64d57ad286631d01",
          "sha256": "5a9d6765355442d810cbaec03b33cd391d1de82020950822a2a83fc7b5809e63",
          "sha1": "2defee9d4c7ce3800a29e0a743339d8eaaefb40d",
          "md5": "49ade5bd04191629d0a3d9e98ce6ee32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.8.jar",
          "url": "api-1.0.8.jar",
          "size": 1291030,
          "sha512": "e1d9414e444d7894d49e13c64a599da433a874cd9b21c0c4c74600ec1889becbed3dfd2e954d3fa308d077b3c90c21f1851f8b546abf0fcc64d57ad286631d01",
          "sha256": "5a9d6765355442d810cbaec03b33cd391d1de82020950822a2a83fc7b5809e63",
          "sha1": "2defee9d4c7ce3800a29e0a743339d8eaaefb40d",
          "md5": "49ade5bd04191629d0a3d9e98ce6ee32"
        }
      ]
    }
  ]
}
