{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-0.0.0.jar",
          "url": "scripts-0.0.0.jar",
          "size": 31877,
          "sha512": "7e505311cff36e9152f84a6e4d0b429e7c5c266ca834f06ba99c9e91c755e24756a2f3f6dc3af6bf2a6d53578d7b5f18badb7856b65f31b486d7c5e6eb239136",
          "sha256": "8694cf37950759d0fa83e2b56e8f3633447436117d84fde239838340c0157bef",
          "sha1": "5dce0f5ac8784f9b1cfa09774625c3dfe6ec0825",
          "md5": "5788aa16d12e796030e44eb40f0cd715"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-0.0.0.jar",
          "url": "scripts-0.0.0.jar",
          "size": 31877,
          "sha512": "7e505311cff36e9152f84a6e4d0b429e7c5c266ca834f06ba99c9e91c755e24756a2f3f6dc3af6bf2a6d53578d7b5f18badb7856b65f31b486d7c5e6eb239136",
          "sha256": "8694cf37950759d0fa83e2b56e8f3633447436117d84fde239838340c0157bef",
          "sha1": "5dce0f5ac8784f9b1cfa09774625c3dfe6ec0825",
          "md5": "5788aa16d12e796030e44eb40f0cd715"
        }
      ]
    }
  ]
}
