{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "9.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-9.9.9.jar",
          "url": "annotations-9.9.9.jar",
          "size": 7290,
          "sha512": "5568208ecbada06a98c602556e2421063d6289afb8f71feca9a9da3795e9663dcb77c83978832fe01dbe8ba6621186f28d12c18f6b93972cbf4c8177d43b49aa",
          "sha256": "90df281deb6c94a8c06a057e0ffa838a1fe5613d1219eeafc0240959ecef6345",
          "sha1": "4056c63834d23416938232ab448f9d9f29094fa7",
          "md5": "6125a90483bbe2d6b4ab2217de2f21ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-9.9.9.jar",
          "url": "annotations-9.9.9.jar",
          "size": 7290,
          "sha512": "5568208ecbada06a98c602556e2421063d6289afb8f71feca9a9da3795e9663dcb77c83978832fe01dbe8ba6621186f28d12c18f6b93972cbf4c8177d43b49aa",
          "sha256": "90df281deb6c94a8c06a057e0ffa838a1fe5613d1219eeafc0240959ecef6345",
          "sha1": "4056c63834d23416938232ab448f9d9f29094fa7",
          "md5": "6125a90483bbe2d6b4ab2217de2f21ed"
        }
      ]
    }
  ]
}
