{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.12.jar",
          "url": "api-rs-1.6.12.jar",
          "size": 123892,
          "sha512": "79eca6a6e88012a1508201c26e67d7ef2b2879927c3c7178fe1a7eca431cec7725d33d5977c944c9df920de196fea01fff5e16e8cfc148aeb1af32b46945e4bd",
          "sha256": "fa6e0e7ac15516d3d40dabcfeae0ba68aff6741b381439bc1c33a5b71e87ac9d",
          "sha1": "d12a406bc72edeb1656bc133d486f8e379bc7eea",
          "md5": "4be9710ac1f3bfe43a44b2cbf26c9ef4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.12.jar",
          "url": "api-rs-1.6.12.jar",
          "size": 123892,
          "sha512": "79eca6a6e88012a1508201c26e67d7ef2b2879927c3c7178fe1a7eca431cec7725d33d5977c944c9df920de196fea01fff5e16e8cfc148aeb1af32b46945e4bd",
          "sha256": "fa6e0e7ac15516d3d40dabcfeae0ba68aff6741b381439bc1c33a5b71e87ac9d",
          "sha1": "d12a406bc72edeb1656bc133d486f8e379bc7eea",
          "md5": "4be9710ac1f3bfe43a44b2cbf26c9ef4"
        }
      ]
    }
  ]
}
