{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.4.jar",
          "url": "api-rs-1.4.4.jar",
          "size": 122758,
          "sha512": "982963522e053fa47afcfe62d4495d0e60dee856e61ff6c1c5d5ccb17ea76b646fd87a85efc2d28c55c227215a480bead71a96d3d77f192d66b52a62412b6631",
          "sha256": "787db2c4107308d54c77c85173d150f9ecc642788e75d7a1755f5d2bb75cb66e",
          "sha1": "bc328beb1d82c8aa1fcd14b76acfbb808a5011a2",
          "md5": "15c23552914f26987f15c57518ff821a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.4.jar",
          "url": "api-rs-1.4.4.jar",
          "size": 122758,
          "sha512": "982963522e053fa47afcfe62d4495d0e60dee856e61ff6c1c5d5ccb17ea76b646fd87a85efc2d28c55c227215a480bead71a96d3d77f192d66b52a62412b6631",
          "sha256": "787db2c4107308d54c77c85173d150f9ecc642788e75d7a1755f5d2bb75cb66e",
          "sha1": "bc328beb1d82c8aa1fcd14b76acfbb808a5011a2",
          "md5": "15c23552914f26987f15c57518ff821a"
        }
      ]
    }
  ]
}
