{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.4.jar",
          "url": "api-rs-1.4.4.jar",
          "size": 122412,
          "sha512": "19f9e9752971357d3fc3056e8482ff038f44dd662aa6818ed53cae616d4380b526f2e74e9b65f5ec7c714af22470817f3c1de0ecdca4d9d5cae024c211113025",
          "sha256": "697edad5aabd7012bbaac9ba7312b4d8c51f065c7035b4ac59bcffbad00cbac4",
          "sha1": "665980c83df4fc873cf353a1f6acbd8b41c323f6",
          "md5": "3d8c057da2bd136d676f1c6ac047aa95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.4.jar",
          "url": "api-rs-1.4.4.jar",
          "size": 122412,
          "sha512": "19f9e9752971357d3fc3056e8482ff038f44dd662aa6818ed53cae616d4380b526f2e74e9b65f5ec7c714af22470817f3c1de0ecdca4d9d5cae024c211113025",
          "sha256": "697edad5aabd7012bbaac9ba7312b4d8c51f065c7035b4ac59bcffbad00cbac4",
          "sha1": "665980c83df4fc873cf353a1f6acbd8b41c323f6",
          "md5": "3d8c057da2bd136d676f1c6ac047aa95"
        }
      ]
    }
  ]
}
