{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.4.jar",
          "url": "api-rs-1.4.4.jar",
          "size": 122412,
          "sha512": "7fd98a2e79cb6a4d2674817b3b00835ac3c1fc9a56631969d7a565f05e5c66ea5614b6719235a832e042e99657dc2319b9552792a03f82daf09e34600fe43956",
          "sha256": "c19fb67d7499b656d5fd6931e56eaf30fad47b2d5c116084e7f4ee884e0258ff",
          "sha1": "baea773a84040078b493f1f7cf3e3ed26c3421cb",
          "md5": "9ef7f243de6f706df16c6dc4ad466d55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.4.jar",
          "url": "api-rs-1.4.4.jar",
          "size": 122412,
          "sha512": "7fd98a2e79cb6a4d2674817b3b00835ac3c1fc9a56631969d7a565f05e5c66ea5614b6719235a832e042e99657dc2319b9552792a03f82daf09e34600fe43956",
          "sha256": "c19fb67d7499b656d5fd6931e56eaf30fad47b2d5c116084e7f4ee884e0258ff",
          "sha1": "baea773a84040078b493f1f7cf3e3ed26c3421cb",
          "md5": "9ef7f243de6f706df16c6dc4ad466d55"
        }
      ]
    }
  ]
}
