{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.10.jar",
          "url": "annotations-1.6.10.jar",
          "size": 8843,
          "sha512": "b0d746afbaef22a1c2b91084406cd51f2ef755dec92d2f38b0c51c6be78b8268e49a3c130bb6367dfc30fc701c53228b26ee95f7d582ab5b70ba79d86c7d02db",
          "sha256": "dc8b18975e455321024012a774874e20ba2f143a0d94dbfc2e48f525fd980d49",
          "sha1": "0356c9743a0717f839674cdabe48fab7850f1a88",
          "md5": "63091939758296a25f200f903145e8c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.10.jar",
          "url": "annotations-1.6.10.jar",
          "size": 8843,
          "sha512": "b0d746afbaef22a1c2b91084406cd51f2ef755dec92d2f38b0c51c6be78b8268e49a3c130bb6367dfc30fc701c53228b26ee95f7d582ab5b70ba79d86c7d02db",
          "sha256": "dc8b18975e455321024012a774874e20ba2f143a0d94dbfc2e48f525fd980d49",
          "sha1": "0356c9743a0717f839674cdabe48fab7850f1a88",
          "md5": "63091939758296a25f200f903145e8c5"
        }
      ]
    }
  ]
}
