{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.5.0.jar",
          "url": "http-1.5.0.jar",
          "size": 104410,
          "sha512": "88cb20b151e2f883597996305c62dc5d04d9b88d3d7cfc6dadf7885d6d17fe32dbac50162cc2c8b0e2552c50ef84ffdc4b25bd9ebf377dcc6e1c65a0d371ea99",
          "sha256": "71271cad4ba59b591d21fe21f1cab80e11420981a562c86b5715508acda6223e",
          "sha1": "578d22c52f826c48a5405c7c4755f62fbdf33370",
          "md5": "31f49f93ff3b4b1574584e98bad67152"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.5.0.jar",
          "url": "http-1.5.0.jar",
          "size": 104410,
          "sha512": "88cb20b151e2f883597996305c62dc5d04d9b88d3d7cfc6dadf7885d6d17fe32dbac50162cc2c8b0e2552c50ef84ffdc4b25bd9ebf377dcc6e1c65a0d371ea99",
          "sha256": "71271cad4ba59b591d21fe21f1cab80e11420981a562c86b5715508acda6223e",
          "sha1": "578d22c52f826c48a5405c7c4755f62fbdf33370",
          "md5": "31f49f93ff3b4b1574584e98bad67152"
        }
      ]
    }
  ]
}
