{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.5.4.jar",
          "url": "scripts-1.5.4.jar",
          "size": 31947,
          "sha512": "f04e23b073f4a50dbc732876ee386c60f2fb01682ba09a9d522dda5ed6bbd53b40f8aaeb9f866e485ba2dc61cee94e46e251841fb55bebfe647eca2c7f2da7d6",
          "sha256": "8ea8795ffd3c962a8c5205e3b20df261128ef15b61278a445fe085da80d3a71b",
          "sha1": "f61c42973d57f85072fd5af9c7df1561bf49f1d8",
          "md5": "ecd2ce94b308b8010a784247538d9d1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.5.4.jar",
          "url": "scripts-1.5.4.jar",
          "size": 31947,
          "sha512": "f04e23b073f4a50dbc732876ee386c60f2fb01682ba09a9d522dda5ed6bbd53b40f8aaeb9f866e485ba2dc61cee94e46e251841fb55bebfe647eca2c7f2da7d6",
          "sha256": "8ea8795ffd3c962a8c5205e3b20df261128ef15b61278a445fe085da80d3a71b",
          "sha1": "f61c42973d57f85072fd5af9c7df1561bf49f1d8",
          "md5": "ecd2ce94b308b8010a784247538d9d1f"
        }
      ]
    }
  ]
}
