{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rationalityfrontline",
    "module": "kevent",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kevent-2.1.4.jar",
          "url": "kevent-2.1.4.jar",
          "size": 52665,
          "sha512": "40a7a3f2123b0b652fff6e5a2c3c505b1154541d844ec0585e9c621ebb18c12003bf585e65d7d6681fa1ad3ad55baecd9929be9a47adf367046cf388abf8a603",
          "sha256": "dcd4228b0e95a9f76303180b4eb2ac4f2b30dd1209750082d82d580b7166fc36",
          "sha1": "a340818a50b8c6be6a04e9fcc750633d9e9910ab",
          "md5": "a6fde2ba2aa913da9f5c16a63c934311"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "kevent-2.1.4.jar",
          "url": "kevent-2.1.4.jar",
          "size": 52665,
          "sha512": "40a7a3f2123b0b652fff6e5a2c3c505b1154541d844ec0585e9c621ebb18c12003bf585e65d7d6681fa1ad3ad55baecd9929be9a47adf367046cf388abf8a603",
          "sha256": "dcd4228b0e95a9f76303180b4eb2ac4f2b30dd1209750082d82d580b7166fc36",
          "sha1": "a340818a50b8c6be6a04e9fcc750633d9e9910ab",
          "md5": "a6fde2ba2aa913da9f5c16a63c934311"
        }
      ]
    }
  ]
}
