{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "runelite-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.0.jar",
          "url": "runelite-api-1.0.0.jar",
          "size": 1398197,
          "sha512": "96c3157cb9afff342f82609be3153f05a44fa69eb0b8f52778936b69b57bcfb8f61bf55f4b90ba6baf6abe523397bfa5c0799c921b07c8310cf2a4b696032faf",
          "sha256": "deeda7c6a543e35a173231c9aca413a52e244b9ee8260d9e52373df39db8bd66",
          "sha1": "97ca00db6d84a42a593050006479e6fed367a986",
          "md5": "c26db711ce21da07a0c53c9e9ca8014b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.0.jar",
          "url": "runelite-api-1.0.0.jar",
          "size": 1398197,
          "sha512": "96c3157cb9afff342f82609be3153f05a44fa69eb0b8f52778936b69b57bcfb8f61bf55f4b90ba6baf6abe523397bfa5c0799c921b07c8310cf2a4b696032faf",
          "sha256": "deeda7c6a543e35a173231c9aca413a52e244b9ee8260d9e52373df39db8bd66",
          "sha1": "97ca00db6d84a42a593050006479e6fed367a986",
          "md5": "c26db711ce21da07a0c53c9e9ca8014b"
        }
      ]
    }
  ]
}
