{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.5.jar",
          "url": "api-1.4.5.jar",
          "size": 1338053,
          "sha512": "5d68d0bac621d81732c69fdefa9799f6773d306ba7724d02e1ee78de037798e8dae9319abf1650d989b9ddfc61d64bca57c4039070b3c2d6373562f526806f32",
          "sha256": "f51ed93aba7543bbd7dd4ae1c37d61ade0fa5ef2af050bac43b506f5b86be1a1",
          "sha1": "7a4d947f7c9901e942fcfe919af8865c60faf90d",
          "md5": "a3b863ec58038cc9c6f9e6d6e5c090db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.5.jar",
          "url": "api-1.4.5.jar",
          "size": 1338053,
          "sha512": "5d68d0bac621d81732c69fdefa9799f6773d306ba7724d02e1ee78de037798e8dae9319abf1650d989b9ddfc61d64bca57c4039070b3c2d6373562f526806f32",
          "sha256": "f51ed93aba7543bbd7dd4ae1c37d61ade0fa5ef2af050bac43b506f5b86be1a1",
          "sha1": "7a4d947f7c9901e942fcfe919af8865c60faf90d",
          "md5": "a3b863ec58038cc9c6f9e6d6e5c090db"
        }
      ]
    }
  ]
}
