{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.2.jar",
          "url": "api-rs-1.6.2.jar",
          "size": 123317,
          "sha512": "f4c37539358215a6907bf6c5b0c1f0e11e6fb74af5eb12db41884db5848b132b5225a799635331082d39f7c3f4dcf07e0d08075cc9f0496cd2d5ae591f0b7010",
          "sha256": "97dda668fa49831c93ccefe3bfdea3c1093aa79e0db910ef56d5dd0b7ddd0b9d",
          "sha1": "c327795fc63926c020adf854b09605fcb44729aa",
          "md5": "0650af97b85a172fc172c5aefae58b2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.2.jar",
          "url": "api-rs-1.6.2.jar",
          "size": 123317,
          "sha512": "f4c37539358215a6907bf6c5b0c1f0e11e6fb74af5eb12db41884db5848b132b5225a799635331082d39f7c3f4dcf07e0d08075cc9f0496cd2d5ae591f0b7010",
          "sha256": "97dda668fa49831c93ccefe3bfdea3c1093aa79e0db910ef56d5dd0b7ddd0b9d",
          "sha1": "c327795fc63926c020adf854b09605fcb44729aa",
          "md5": "0650af97b85a172fc172c5aefae58b2b"
        }
      ]
    }
  ]
}
