{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.2.jar",
          "url": "api-rs-1.6.2.jar",
          "size": 123317,
          "sha512": "67be8020ba852edbe7c8f51db34b5a397dfa1651a354ab0e624dc9d75ba60698932a0cfa9b12c0fa1861293467751186195bdfa25bd241fb528f17a56804d7b4",
          "sha256": "f38c48a5dc908a0a8354e0ee91d59311247fa0823f6485e2f06d4e39ec2c0c3b",
          "sha1": "f3ef7d349eb44271d50d7f087752b5be1de60693",
          "md5": "8eff44458d4aeb33aa6a4cd19aaca646"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.2.jar",
          "url": "api-rs-1.6.2.jar",
          "size": 123317,
          "sha512": "67be8020ba852edbe7c8f51db34b5a397dfa1651a354ab0e624dc9d75ba60698932a0cfa9b12c0fa1861293467751186195bdfa25bd241fb528f17a56804d7b4",
          "sha256": "f38c48a5dc908a0a8354e0ee91d59311247fa0823f6485e2f06d4e39ec2c0c3b",
          "sha1": "f3ef7d349eb44271d50d7f087752b5be1de60693",
          "md5": "8eff44458d4aeb33aa6a4cd19aaca646"
        }
      ]
    }
  ]
}
