{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.2.jar",
          "url": "api-rs-1.5.2.jar",
          "size": 122758,
          "sha512": "377473b2060af1786f8ec28fabfe792b5823f0e0a1d42864e3f8b4b7b04fdbbc605508ac9052b569a61464c129308876a496c7aa50296126bb3e53a20e6956ba",
          "sha256": "dcb9837a2494ce72148bb4829c8fda5736b63d66a58c63326e850864c96d1f55",
          "sha1": "80303bcf25e16831ec844fe42b9eb70592572333",
          "md5": "23f32c0f260ac3de52941b5a9455a58d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.2.jar",
          "url": "api-rs-1.5.2.jar",
          "size": 122758,
          "sha512": "377473b2060af1786f8ec28fabfe792b5823f0e0a1d42864e3f8b4b7b04fdbbc605508ac9052b569a61464c129308876a496c7aa50296126bb3e53a20e6956ba",
          "sha256": "dcb9837a2494ce72148bb4829c8fda5736b63d66a58c63326e850864c96d1f55",
          "sha1": "80303bcf25e16831ec844fe42b9eb70592572333",
          "md5": "23f32c0f260ac3de52941b5a9455a58d"
        }
      ]
    }
  ]
}
