{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.2.13.jar",
          "url": "scripts-1.2.13.jar",
          "size": 31877,
          "sha512": "0584433eaff74196e6479a2a5b886e552d9a92c25376fdea52f7806bf0afc3132c5fde3e8f505cf27fe2204127f90bf4ed98c8ef1093a22e77bac21e86fd06c5",
          "sha256": "f50f7f8c058c001a3ae88cbf3244adece6b2dfdb0ce3f21d502cd21ed8c723b5",
          "sha1": "7ee0cb1c5e8a7c76c31df04291d01cdaf647546a",
          "md5": "67923c812931ce7a351364ede7315cf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.2.13.jar",
          "url": "scripts-1.2.13.jar",
          "size": 31877,
          "sha512": "0584433eaff74196e6479a2a5b886e552d9a92c25376fdea52f7806bf0afc3132c5fde3e8f505cf27fe2204127f90bf4ed98c8ef1093a22e77bac21e86fd06c5",
          "sha256": "f50f7f8c058c001a3ae88cbf3244adece6b2dfdb0ce3f21d502cd21ed8c723b5",
          "sha1": "7ee0cb1c5e8a7c76c31df04291d01cdaf647546a",
          "md5": "67923c812931ce7a351364ede7315cf2"
        }
      ]
    }
  ]
}
