{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.1.jar",
          "url": "api-rs-1.5.1.jar",
          "size": 122758,
          "sha512": "34fde22567d164af3fa6417effe99c53dea5c85b43689112f2d087134e70b3b62e03371271b3efa5da5312c910143989561de3ba344b7890b1c515bc5dc17e76",
          "sha256": "0570364ca157b749f8e11a1200277c9597fe2a81ce267683b515ab2ef1c08c22",
          "sha1": "b5875008313508a4aae3fdadadd4ddecfcd49b1e",
          "md5": "ce9c8c1d68aff8d8eb3c63a57834b18c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.1.jar",
          "url": "api-rs-1.5.1.jar",
          "size": 122758,
          "sha512": "34fde22567d164af3fa6417effe99c53dea5c85b43689112f2d087134e70b3b62e03371271b3efa5da5312c910143989561de3ba344b7890b1c515bc5dc17e76",
          "sha256": "0570364ca157b749f8e11a1200277c9597fe2a81ce267683b515ab2ef1c08c22",
          "sha1": "b5875008313508a4aae3fdadadd4ddecfcd49b1e",
          "md5": "ce9c8c1d68aff8d8eb3c63a57834b18c"
        }
      ]
    }
  ]
}
