{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.6.jar",
          "url": "api-1.5.6.jar",
          "size": 1338171,
          "sha512": "b8dc09bfa63f8c1e6ac2d90f2a409715cffa2647a9ede95854d1333d31ff52d0db4c2f1ce40eacccd4d61343614d8b1b09aede1d684047bd0c181cf1ffd8454f",
          "sha256": "8891e11236d869e493dc85fbb47070dd1fbe8697341535e4afd28dc69618c85b",
          "sha1": "6e68e71083673d6c275f7c314390fa8bac382bed",
          "md5": "07cbc96583364581ddf109edcf79c4d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.6.jar",
          "url": "api-1.5.6.jar",
          "size": 1338171,
          "sha512": "b8dc09bfa63f8c1e6ac2d90f2a409715cffa2647a9ede95854d1333d31ff52d0db4c2f1ce40eacccd4d61343614d8b1b09aede1d684047bd0c181cf1ffd8454f",
          "sha256": "8891e11236d869e493dc85fbb47070dd1fbe8697341535e4afd28dc69618c85b",
          "sha1": "6e68e71083673d6c275f7c314390fa8bac382bed",
          "md5": "07cbc96583364581ddf109edcf79c4d4"
        }
      ]
    }
  ]
}
