{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.4.jar",
          "url": "api-1.4.4.jar",
          "size": 1338053,
          "sha512": "3df82eff144e4e30d628298c182ab0bd0c471a6f2c6b3c97a0855200474f5138a7e8e7fa2cb427be97147eb3df18b42b47ba4a36432c47f8959668eae2272aaa",
          "sha256": "18a177fb27cd998ab6f283fb80d101a346e02e83136aa6a014213ba866627adb",
          "sha1": "e26f277075e3dbda737a76625cac1118a1f4bbd7",
          "md5": "e72b3ac2d0bcbd8fcf1b4b57aca05044"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.4"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.4.jar",
          "url": "api-1.4.4.jar",
          "size": 1338053,
          "sha512": "3df82eff144e4e30d628298c182ab0bd0c471a6f2c6b3c97a0855200474f5138a7e8e7fa2cb427be97147eb3df18b42b47ba4a36432c47f8959668eae2272aaa",
          "sha256": "18a177fb27cd998ab6f283fb80d101a346e02e83136aa6a014213ba866627adb",
          "sha1": "e26f277075e3dbda737a76625cac1118a1f4bbd7",
          "md5": "e72b3ac2d0bcbd8fcf1b4b57aca05044"
        }
      ]
    }
  ]
}
