{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.2.jar",
          "url": "api-rs-1.4.2.jar",
          "size": 122412,
          "sha512": "67898ac0a39e24eaf02f2ab449b93675453b013784ce2658bcea9d99f29d62d38ca9f57056871cbeab1a70b6b3f990bf657fec9a65fc006f927cb072cfcbd612",
          "sha256": "edba4537678ab29288ea66a1ad3ff68d036de5e96a282e853e5fb3f44372e43f",
          "sha1": "fd6873783474501e4c9153ac903a5dc0eaec687a",
          "md5": "1e2df17626e6aff3dbe2ed51fa042734"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.2.jar",
          "url": "api-rs-1.4.2.jar",
          "size": 122412,
          "sha512": "67898ac0a39e24eaf02f2ab449b93675453b013784ce2658bcea9d99f29d62d38ca9f57056871cbeab1a70b6b3f990bf657fec9a65fc006f927cb072cfcbd612",
          "sha256": "edba4537678ab29288ea66a1ad3ff68d036de5e96a282e853e5fb3f44372e43f",
          "sha1": "fd6873783474501e4c9153ac903a5dc0eaec687a",
          "md5": "1e2df17626e6aff3dbe2ed51fa042734"
        }
      ]
    }
  ]
}
