{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.9.jar",
          "url": "api-rs-1.6.9.jar",
          "size": 123713,
          "sha512": "af3b9bc0f0679d74f4386e6fe96cbc2375d775a4f96a9b76e0181642cac0dc15d5a5a2aceab8f1dbf6f939d76302c266fd1e7a4d94eee73d777b33aa15d50752",
          "sha256": "d690078eaf17263616f3fb271226a095eaa915f59818b47038833f90b603bb39",
          "sha1": "68add3b5a6185ba2fbdccdf8fca5d0549944f35d",
          "md5": "8333f821987744c4008126065422821d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.9.jar",
          "url": "api-rs-1.6.9.jar",
          "size": 123713,
          "sha512": "af3b9bc0f0679d74f4386e6fe96cbc2375d775a4f96a9b76e0181642cac0dc15d5a5a2aceab8f1dbf6f939d76302c266fd1e7a4d94eee73d777b33aa15d50752",
          "sha256": "d690078eaf17263616f3fb271226a095eaa915f59818b47038833f90b603bb39",
          "sha1": "68add3b5a6185ba2fbdccdf8fca5d0549944f35d",
          "md5": "8333f821987744c4008126065422821d"
        }
      ]
    }
  ]
}
