{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.0.0.jar",
          "url": "annotations-1.0.0.jar",
          "size": 7286,
          "sha512": "1a576d13c83b60aff882ca6a6342eee403fd3ec04c5ed45eb84b36b6ad2aa0b349de79971f7579037d42fcb8c960635185abb380a718008253d2692684b8315f",
          "sha256": "6bbdc8214674304f8f16c1dacb55be7bac5fb980403d898a3605da35065e23a4",
          "sha1": "527fcc2e03939f358b2a5a4bad0cc490550312f1",
          "md5": "d9fccef99401cf88041bb0e35cae65b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.0.jar",
          "url": "annotations-1.0.0.jar",
          "size": 7286,
          "sha512": "1a576d13c83b60aff882ca6a6342eee403fd3ec04c5ed45eb84b36b6ad2aa0b349de79971f7579037d42fcb8c960635185abb380a718008253d2692684b8315f",
          "sha256": "6bbdc8214674304f8f16c1dacb55be7bac5fb980403d898a3605da35065e23a4",
          "sha1": "527fcc2e03939f358b2a5a4bad0cc490550312f1",
          "md5": "d9fccef99401cf88041bb0e35cae65b5"
        }
      ]
    }
  ]
}
