{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.0.0.jar",
          "url": "annotations-1.0.0.jar",
          "size": 7286,
          "sha512": "0bfa2fd3b5e2b991e22f76631ba67ee7ce3cb9ff6a21b0f2df2604d38041c416282a22543e781e4ff71d8dfbd17b0360225ca79938e393ba021b3d1b798e842e",
          "sha256": "c9cdf1add350469222b04e1641fff141d6b34bf48304fd87f54a582b5c6902c8",
          "sha1": "b835da63d9d3313bde02e02c2d762a9868f702a9",
          "md5": "3b06e1355185200a45e58178435926ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.0.jar",
          "url": "annotations-1.0.0.jar",
          "size": 7286,
          "sha512": "0bfa2fd3b5e2b991e22f76631ba67ee7ce3cb9ff6a21b0f2df2604d38041c416282a22543e781e4ff71d8dfbd17b0360225ca79938e393ba021b3d1b798e842e",
          "sha256": "c9cdf1add350469222b04e1641fff141d6b34bf48304fd87f54a582b5c6902c8",
          "sha1": "b835da63d9d3313bde02e02c2d762a9868f702a9",
          "md5": "3b06e1355185200a45e58178435926ab"
        }
      ]
    }
  ]
}
