{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.2.jar",
          "url": "api-1.4.2.jar",
          "size": 1338056,
          "sha512": "c8b66f7e579ae198f91a99f0d27b62c191bab5f1e9df9e7f2c6510c5935e150cae48e234cbf926917d95a7f2eb596a4be82e7a02edc518d4d812d63313e8d6a3",
          "sha256": "0e41e60f792ee5d26803101fdfe52b4e25cdf054c2f88f43b813d166015b046b",
          "sha1": "6f38af4184ea31b5d846fa3e7beb4a266cbb77e4",
          "md5": "958244dd797789ca70b6f11da2144a17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.2.jar",
          "url": "api-1.4.2.jar",
          "size": 1338056,
          "sha512": "c8b66f7e579ae198f91a99f0d27b62c191bab5f1e9df9e7f2c6510c5935e150cae48e234cbf926917d95a7f2eb596a4be82e7a02edc518d4d812d63313e8d6a3",
          "sha256": "0e41e60f792ee5d26803101fdfe52b4e25cdf054c2f88f43b813d166015b046b",
          "sha1": "6f38af4184ea31b5d846fa3e7beb4a266cbb77e4",
          "md5": "958244dd797789ca70b6f11da2144a17"
        }
      ]
    }
  ]
}
