{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.5.jar",
          "url": "api-1.5.5.jar",
          "size": 1338171,
          "sha512": "58ca46478a86b04086bc29ed72d5d6f62e225f61af60388f5e8c0eb844d085a261b053964c186673155da3433210fb2879dbe0d297257e09e9289db4434ee58c",
          "sha256": "3e570061cf026d163e4943a760cc7aa1d124adf1515174cad5c524a753205f7f",
          "sha1": "9db17a8566e74291892c6d4750088b30d1b24182",
          "md5": "ea350d3aea6d0a2ec0ec8d158ddac34a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.5.jar",
          "url": "api-1.5.5.jar",
          "size": 1338171,
          "sha512": "58ca46478a86b04086bc29ed72d5d6f62e225f61af60388f5e8c0eb844d085a261b053964c186673155da3433210fb2879dbe0d297257e09e9289db4434ee58c",
          "sha256": "3e570061cf026d163e4943a760cc7aa1d124adf1515174cad5c524a753205f7f",
          "sha1": "9db17a8566e74291892c6d4750088b30d1b24182",
          "md5": "ea350d3aea6d0a2ec0ec8d158ddac34a"
        }
      ]
    }
  ]
}
