{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.7.jar",
          "url": "api-1.1.7.jar",
          "size": 1337810,
          "sha512": "57b85aeafb00ad1260842786fd8c3d86741d6b4135a45dbcbe151c0849876b6afbd29d675e88ed3853565edc5a9bafa53696ec11097a8ef90dbad4b14a589d81",
          "sha256": "c7b3ddb009f6e46651ca19285e8189652675a9bed8ce89481a6e89c819812948",
          "sha1": "56f6677c5ac1695bb97423edb3038054af2a7b1a",
          "md5": "61029f35ab0bb976f8051e209dd7eafc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.7.jar",
          "url": "api-1.1.7.jar",
          "size": 1337810,
          "sha512": "57b85aeafb00ad1260842786fd8c3d86741d6b4135a45dbcbe151c0849876b6afbd29d675e88ed3853565edc5a9bafa53696ec11097a8ef90dbad4b14a589d81",
          "sha256": "c7b3ddb009f6e46651ca19285e8189652675a9bed8ce89481a6e89c819812948",
          "sha1": "56f6677c5ac1695bb97423edb3038054af2a7b1a",
          "md5": "61029f35ab0bb976f8051e209dd7eafc"
        }
      ]
    }
  ]
}
