{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.2.jar",
          "url": "api-1.5.2.jar",
          "size": 1338096,
          "sha512": "b86c5f7745b504ba8c80090523771c432231c0fd3dcb98026cf0a4b5f58fc9c043985913ea945c508486eff6065ea884f1b5a5008972af7adc3560db2e36d112",
          "sha256": "6da72b3d97fb404d252bd7eeb57499871c620cd0efa7a499bc5201813bfc4125",
          "sha1": "54a55af72a993a2de9a983092a4484ee44f23a1f",
          "md5": "f0cf9ec334d84a407559a5ff7d114b2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.2.jar",
          "url": "api-1.5.2.jar",
          "size": 1338096,
          "sha512": "b86c5f7745b504ba8c80090523771c432231c0fd3dcb98026cf0a4b5f58fc9c043985913ea945c508486eff6065ea884f1b5a5008972af7adc3560db2e36d112",
          "sha256": "6da72b3d97fb404d252bd7eeb57499871c620cd0efa7a499bc5201813bfc4125",
          "sha1": "54a55af72a993a2de9a983092a4484ee44f23a1f",
          "md5": "f0cf9ec334d84a407559a5ff7d114b2a"
        }
      ]
    }
  ]
}
