{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.0.jar",
          "url": "http-1.6.0.jar",
          "size": 104410,
          "sha512": "4f464a8e3c8c17aba9fa6ce8dd212d7fa6866cb9e957cfdee1b443c923da691c99513ce9ff5a8544ce4f7e12d934915cd2f645408b95e254c58cbdec530939d5",
          "sha256": "09783f0e68a6431f6f954644111efaf72d6e039cf821af364ac1bc5d833fd7c8",
          "sha1": "a37e56498b0beb035279f94deb08ec364717a0c5",
          "md5": "c14e6418225f0e289abc8cae26d4eca7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.0.jar",
          "url": "http-1.6.0.jar",
          "size": 104410,
          "sha512": "4f464a8e3c8c17aba9fa6ce8dd212d7fa6866cb9e957cfdee1b443c923da691c99513ce9ff5a8544ce4f7e12d934915cd2f645408b95e254c58cbdec530939d5",
          "sha256": "09783f0e68a6431f6f954644111efaf72d6e039cf821af364ac1bc5d833fd7c8",
          "sha1": "a37e56498b0beb035279f94deb08ec364717a0c5",
          "md5": "c14e6418225f0e289abc8cae26d4eca7"
        }
      ]
    }
  ]
}
