{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.9.jar",
          "url": "scripts-1.6.9.jar",
          "size": 28428,
          "sha512": "681d8903faea8f3a4a33937932dd9e57eae549eb32cb62ce5105cee3f161a7f7e8642c85457349c87c1f184592b45eb7d3c4cbf2cc155f47d287db703b1dbc16",
          "sha256": "535a7a764bf568b4b38e8b6664825667687c9503c74213f48d5cd1efb9756ca4",
          "sha1": "50f41ea0c9b63caeaf27b78356434221ae731b3f",
          "md5": "3efb9dc5580fff2e5caff536d7deebb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.9.jar",
          "url": "scripts-1.6.9.jar",
          "size": 28428,
          "sha512": "681d8903faea8f3a4a33937932dd9e57eae549eb32cb62ce5105cee3f161a7f7e8642c85457349c87c1f184592b45eb7d3c4cbf2cc155f47d287db703b1dbc16",
          "sha256": "535a7a764bf568b4b38e8b6664825667687c9503c74213f48d5cd1efb9756ca4",
          "sha1": "50f41ea0c9b63caeaf27b78356434221ae731b3f",
          "md5": "3efb9dc5580fff2e5caff536d7deebb5"
        }
      ]
    }
  ]
}
