{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.2.10.jar",
          "url": "api-rs-1.2.10.jar",
          "size": 122508,
          "sha512": "340eae64f15faa50e1b7827320f05eafd1886479a5542570ada171f61329fc168fe889fedcf0e797e54f785da2a253eac4bb4688493c224e988f9e62829f7ec7",
          "sha256": "97b6feb0a6d6fed0ae008712ebcf692234c583e95d22645c9fcf151b757e3a9d",
          "sha1": "e0fb9ecfa0d4e18ca064df2d9e5b16dab8d21cc2",
          "md5": "c9cbfe6e281b0830f1aa91f68c65d299"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.10.jar",
          "url": "api-rs-1.2.10.jar",
          "size": 122508,
          "sha512": "340eae64f15faa50e1b7827320f05eafd1886479a5542570ada171f61329fc168fe889fedcf0e797e54f785da2a253eac4bb4688493c224e988f9e62829f7ec7",
          "sha256": "97b6feb0a6d6fed0ae008712ebcf692234c583e95d22645c9fcf151b757e3a9d",
          "sha1": "e0fb9ecfa0d4e18ca064df2d9e5b16dab8d21cc2",
          "md5": "c9cbfe6e281b0830f1aa91f68c65d299"
        }
      ]
    }
  ]
}
