{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.0.jar",
          "url": "api-1.5.0.jar",
          "size": 1338096,
          "sha512": "dac075f3e755727c832a2eb488aaf9edac93230969427355799864658609c789898454b5efac600c353be474e87e087a578314088505b17a015db0154f9f59dd",
          "sha256": "abe677fc0159a9dc930599126eb62d091b254e28ca88f09a0eab57b93ca7a648",
          "sha1": "a60ff507123979c90a33e99586261ec40044143d",
          "md5": "cc48bdb8c1cdb49dda7dbb6d261f2242"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.0.jar",
          "url": "api-1.5.0.jar",
          "size": 1338096,
          "sha512": "dac075f3e755727c832a2eb488aaf9edac93230969427355799864658609c789898454b5efac600c353be474e87e087a578314088505b17a015db0154f9f59dd",
          "sha256": "abe677fc0159a9dc930599126eb62d091b254e28ca88f09a0eab57b93ca7a648",
          "sha1": "a60ff507123979c90a33e99586261ec40044143d",
          "md5": "cc48bdb8c1cdb49dda7dbb6d261f2242"
        }
      ]
    }
  ]
}
