{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.0.1.jar",
          "url": "api-rs-1.0.1.jar",
          "size": 116671,
          "sha512": "b2e4802ef7e49ee16a16d563e12872af8010dcf24f4899da32622c9584508599ac4669e6ad3c46ea6f47004e553897d79217ea870407bfdc76a1d641473d74db",
          "sha256": "85c19800587c077b9b883b12f429da0bb35cfbdbd4a8c5b8820137eeea7759a7",
          "sha1": "39abcd65d310dff6b5dffb45e9d27b2a33b456f9",
          "md5": "0cdc0e206c2024e8c299f97da4df05bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.0.1.jar",
          "url": "api-rs-1.0.1.jar",
          "size": 116671,
          "sha512": "b2e4802ef7e49ee16a16d563e12872af8010dcf24f4899da32622c9584508599ac4669e6ad3c46ea6f47004e553897d79217ea870407bfdc76a1d641473d74db",
          "sha256": "85c19800587c077b9b883b12f429da0bb35cfbdbd4a8c5b8820137eeea7759a7",
          "sha1": "39abcd65d310dff6b5dffb45e9d27b2a33b456f9",
          "md5": "0cdc0e206c2024e8c299f97da4df05bf"
        }
      ]
    }
  ]
}
