{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.5.6.jar",
          "url": "http-1.5.6.jar",
          "size": 104410,
          "sha512": "6546bca02270ab03d9c64af9b111d06d391668ab3122dd63333b6cbaf49810980a7d88906f6a0324f90b4399d6b2b7cd7dfae660320b10284b5c2df116728fa8",
          "sha256": "aac30944d71a28d87721bf0cb0f919b11f26262a578ae9112c1178060a8c87af",
          "sha1": "1edec859facffb1174ad2050892c4a9f04b03e0a",
          "md5": "bd81b6194dd300800eed03ffd4574264"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.5.6.jar",
          "url": "http-1.5.6.jar",
          "size": 104410,
          "sha512": "6546bca02270ab03d9c64af9b111d06d391668ab3122dd63333b6cbaf49810980a7d88906f6a0324f90b4399d6b2b7cd7dfae660320b10284b5c2df116728fa8",
          "sha256": "aac30944d71a28d87721bf0cb0f919b11f26262a578ae9112c1178060a8c87af",
          "sha1": "1edec859facffb1174ad2050892c4a9f04b03e0a",
          "md5": "bd81b6194dd300800eed03ffd4574264"
        }
      ]
    }
  ]
}
