{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.3.jar",
          "url": "api-rs-1.4.3.jar",
          "size": 122412,
          "sha512": "24f00c5412ceeb187fa9840c6e32e5314f7957d1bf42801310eff1cd6fc76df7b5e58f07086d433bb1d4f039710b7f771445f4d27dcabee5af41b92b64ed59a5",
          "sha256": "55b8cbffbfb2026d24e14e5076f418e6c910b202a2793595879ac4361492220f",
          "sha1": "e8d39fb7375234e44510e6e87fb7f41cb6c3135e",
          "md5": "fe4d25c020c40410092634c68fa24e5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.3.jar",
          "url": "api-rs-1.4.3.jar",
          "size": 122412,
          "sha512": "24f00c5412ceeb187fa9840c6e32e5314f7957d1bf42801310eff1cd6fc76df7b5e58f07086d433bb1d4f039710b7f771445f4d27dcabee5af41b92b64ed59a5",
          "sha256": "55b8cbffbfb2026d24e14e5076f418e6c910b202a2793595879ac4361492220f",
          "sha1": "e8d39fb7375234e44510e6e87fb7f41cb6c3135e",
          "md5": "fe4d25c020c40410092634c68fa24e5f"
        }
      ]
    }
  ]
}
