{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.1.jar",
          "url": "annotations-1.4.1.jar",
          "size": 8843,
          "sha512": "da1a6ae67d802fafe0f089630c1a90d16e05826d2ad7a2131ab940503c74ddb883c4f5fd1b6a76112d98bfe070807cc50a7d52adfb0cd25aefa62418e8f3bc20",
          "sha256": "d4f6bdfcc129978e71b6a6b8ab120f7b76ae38c2140a2e67c08f5be794b94806",
          "sha1": "822dfed5faac5ecc7f78f942d335e68716fe83fe",
          "md5": "1fa330c94f75c6226c8fc652718b8661"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.1.jar",
          "url": "annotations-1.4.1.jar",
          "size": 8843,
          "sha512": "da1a6ae67d802fafe0f089630c1a90d16e05826d2ad7a2131ab940503c74ddb883c4f5fd1b6a76112d98bfe070807cc50a7d52adfb0cd25aefa62418e8f3bc20",
          "sha256": "d4f6bdfcc129978e71b6a6b8ab120f7b76ae38c2140a2e67c08f5be794b94806",
          "sha1": "822dfed5faac5ecc7f78f942d335e68716fe83fe",
          "md5": "1fa330c94f75c6226c8fc652718b8661"
        }
      ]
    }
  ]
}
