{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.6.jar",
          "url": "api-1.2.6.jar",
          "size": 1339100,
          "sha512": "ce618b1ff9ed42f7eb336095fead4e28382945656acfcfe783c2d9cd52a3aa38a5947a8d6de0aeac3043ba7ba9c634d661899fb409d654e9c1f9e9fc09f878fc",
          "sha256": "be68861af9e015e42fd50ba32e25d0af8803c414db8cfb41739100e795c89184",
          "sha1": "5cd121576bc591dff5f60cffe215a1561537e587",
          "md5": "c5c2edbcd87f04f64921bcc0795dd8de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.6"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.6.jar",
          "url": "api-1.2.6.jar",
          "size": 1339100,
          "sha512": "ce618b1ff9ed42f7eb336095fead4e28382945656acfcfe783c2d9cd52a3aa38a5947a8d6de0aeac3043ba7ba9c634d661899fb409d654e9c1f9e9fc09f878fc",
          "sha256": "be68861af9e015e42fd50ba32e25d0af8803c414db8cfb41739100e795c89184",
          "sha1": "5cd121576bc591dff5f60cffe215a1561537e587",
          "md5": "c5c2edbcd87f04f64921bcc0795dd8de"
        }
      ]
    }
  ]
}
