{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.3.0.jar",
          "url": "http-1.3.0.jar",
          "size": 104410,
          "sha512": "a110e316da9c2731c04a6e591b42f1df17e196b6711924859b575927623f589b4d6ed529fdce5aee6adc2be0001c39e15069dc3ca29b25f139242c4c4078bf68",
          "sha256": "a32b1fe1dcbd5496810c7f15fddb1f86493fa9d392ed4dfac012e444c8ad6d9b",
          "sha1": "ace6e549ff5c568116bebed3c5955fb2d8825c93",
          "md5": "ef2a2d8e59e9a840ff4d577349d27643"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.3.0.jar",
          "url": "http-1.3.0.jar",
          "size": 104410,
          "sha512": "a110e316da9c2731c04a6e591b42f1df17e196b6711924859b575927623f589b4d6ed529fdce5aee6adc2be0001c39e15069dc3ca29b25f139242c4c4078bf68",
          "sha256": "a32b1fe1dcbd5496810c7f15fddb1f86493fa9d392ed4dfac012e444c8ad6d9b",
          "sha1": "ace6e549ff5c568116bebed3c5955fb2d8825c93",
          "md5": "ef2a2d8e59e9a840ff4d577349d27643"
        }
      ]
    }
  ]
}
