{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.4.jar",
          "url": "api-rs-1.6.4.jar",
          "size": 123335,
          "sha512": "3ac4cb1f2e04f2611286309bdb606acb0955bdad6847b59370ff4bf13a8a7f6e6a73ed03dfa1546ec999e4ac603641fd39eed71612b9c91f266387873b91b430",
          "sha256": "b34dcf2a2244cc5931933cc0aa7d02beb9705485e5c4c5f6949a1e253071182c",
          "sha1": "3c3d66adc951d2befac11e625efc101333e20b37",
          "md5": "d89a04307ba6352a3b13b37581baca21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.4.jar",
          "url": "api-rs-1.6.4.jar",
          "size": 123335,
          "sha512": "3ac4cb1f2e04f2611286309bdb606acb0955bdad6847b59370ff4bf13a8a7f6e6a73ed03dfa1546ec999e4ac603641fd39eed71612b9c91f266387873b91b430",
          "sha256": "b34dcf2a2244cc5931933cc0aa7d02beb9705485e5c4c5f6949a1e253071182c",
          "sha1": "3c3d66adc951d2befac11e625efc101333e20b37",
          "md5": "d89a04307ba6352a3b13b37581baca21"
        }
      ]
    }
  ]
}
