{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-3.0.0.jar",
          "url": "http-3.0.0.jar",
          "size": 104410,
          "sha512": "f80fc0b337d1ee997547c4b1977c0baa320c093549b9336feed5e6ce9970733a1931939fcfd18d6cf97b7b66ba5f079763ed198b150388094916f43a80eaf249",
          "sha256": "9c2286869448fba760cfa5a5b35c17de962c96aa5adbc595efd94c0ebac71555",
          "sha1": "1c20e4cbbf269936387dd4af1086e2e903b81ca2",
          "md5": "4f050712833dadcbc39e1f4e4656eea1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-3.0.0.jar",
          "url": "http-3.0.0.jar",
          "size": 104410,
          "sha512": "f80fc0b337d1ee997547c4b1977c0baa320c093549b9336feed5e6ce9970733a1931939fcfd18d6cf97b7b66ba5f079763ed198b150388094916f43a80eaf249",
          "sha256": "9c2286869448fba760cfa5a5b35c17de962c96aa5adbc595efd94c0ebac71555",
          "sha1": "1c20e4cbbf269936387dd4af1086e2e903b81ca2",
          "md5": "4f050712833dadcbc39e1f4e4656eea1"
        }
      ]
    }
  ]
}
