{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.0.jar",
          "url": "logger-1.2.0.jar",
          "size": 8391,
          "sha512": "8364487e783d8d2ca0fd404ecbc080b8f3e53ce93649d12ed09c155186395ede0f98461a38c2cc7f5127933173c72b135d3cb52ab7b4f9dce233360f9659e0ee",
          "sha256": "3aa98b16462d8ef908e69f382dbd310629dee05fa4476aade6c629a7fd486c1c",
          "sha1": "6d4a3cbd085fe9446e48701211952fa0d7ed3c3e",
          "md5": "0f497313a085af2b67e3fd6687e4e571"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.0.jar",
          "url": "logger-1.2.0.jar",
          "size": 8391,
          "sha512": "8364487e783d8d2ca0fd404ecbc080b8f3e53ce93649d12ed09c155186395ede0f98461a38c2cc7f5127933173c72b135d3cb52ab7b4f9dce233360f9659e0ee",
          "sha256": "3aa98b16462d8ef908e69f382dbd310629dee05fa4476aade6c629a7fd486c1c",
          "sha1": "6d4a3cbd085fe9446e48701211952fa0d7ed3c3e",
          "md5": "0f497313a085af2b67e3fd6687e4e571"
        }
      ]
    }
  ]
}
