{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.3.jar",
          "url": "annotations-1.4.3.jar",
          "size": 8843,
          "sha512": "3d9201270177cdaf3a7b74a800efa9c38be9a3a448fc879f4ccb6c14f941f3326e55785d5a5c6cc901d193e83eed2b1c9f00bc2d287c2a3d2385d118e872835a",
          "sha256": "fc88daf032e8fb690c56c49e80320e81c1d4ca646deddef83242541e9642d579",
          "sha1": "ec5efdd15d405c880f95e6c977b308232c08aaf0",
          "md5": "85686cc608f3dcfde396728fae2a519b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.3.jar",
          "url": "annotations-1.4.3.jar",
          "size": 8843,
          "sha512": "3d9201270177cdaf3a7b74a800efa9c38be9a3a448fc879f4ccb6c14f941f3326e55785d5a5c6cc901d193e83eed2b1c9f00bc2d287c2a3d2385d118e872835a",
          "sha256": "fc88daf032e8fb690c56c49e80320e81c1d4ca646deddef83242541e9642d579",
          "sha1": "ec5efdd15d405c880f95e6c977b308232c08aaf0",
          "md5": "85686cc608f3dcfde396728fae2a519b"
        }
      ]
    }
  ]
}
