{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.13.jar",
          "url": "logger-1.6.13.jar",
          "size": 8579,
          "sha512": "5c8b20dd9e8fc7d072951c3613b7dcb67d8daa5dba79bdd3b8ff4b036202e23226c97bd34694591271235258ce0f7650b0ada024496f2813d385879a79fa6184",
          "sha256": "7a9fd2806a5b78a3b1ec55f7bd218f789e0b4f68886fbf1e24222d53a4952e4f",
          "sha1": "1911bdea45dac2ebb6dd153f7fb05936ecfa4890",
          "md5": "4838aff2b3ba677482830a9a78831e6f"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.13.jar",
          "url": "logger-1.6.13.jar",
          "size": 8579,
          "sha512": "5c8b20dd9e8fc7d072951c3613b7dcb67d8daa5dba79bdd3b8ff4b036202e23226c97bd34694591271235258ce0f7650b0ada024496f2813d385879a79fa6184",
          "sha256": "7a9fd2806a5b78a3b1ec55f7bd218f789e0b4f68886fbf1e24222d53a4952e4f",
          "sha1": "1911bdea45dac2ebb6dd153f7fb05936ecfa4890",
          "md5": "4838aff2b3ba677482830a9a78831e6f"
        }
      ]
    }
  ]
}
