{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.6.jar",
          "url": "annotations-1.4.6.jar",
          "size": 8843,
          "sha512": "388595dc235d88c1208d7b61ac2c241e6e227c5605b676ae85c479c1b0f1caa67b4fa4709e65e3b981a4ffc32809ddd0c822a87be882afe32576357cb840733f",
          "sha256": "a8b14c6d36a25509cfac30d8ed981b8f3f6b4295ad1dfaf8af71ef99233bb71a",
          "sha1": "71ddf1d21227db629b8318f11126d919f8b8d798",
          "md5": "07436cea5b3fa83e3c8d70ed78566aa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.6.jar",
          "url": "annotations-1.4.6.jar",
          "size": 8843,
          "sha512": "388595dc235d88c1208d7b61ac2c241e6e227c5605b676ae85c479c1b0f1caa67b4fa4709e65e3b981a4ffc32809ddd0c822a87be882afe32576357cb840733f",
          "sha256": "a8b14c6d36a25509cfac30d8ed981b8f3f6b4295ad1dfaf8af71ef99233bb71a",
          "sha1": "71ddf1d21227db629b8318f11126d919f8b8d798",
          "md5": "07436cea5b3fa83e3c8d70ed78566aa9"
        }
      ]
    }
  ]
}
