{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.4.2.jar",
          "url": "http-1.4.2.jar",
          "size": 104410,
          "sha512": "ff26153d6fe39f359cba34f53805f4fd24d23839b77a27f69d44862da9f22f10c80c0cac9917e0d24f95f2d221da03f3f6ef3751c3fb278e6b12f53dd16469d2",
          "sha256": "14b04f995a3c25c1f5138dc2460b157879f55d921cab3655c033f33085db57e1",
          "sha1": "111ba69c20144638f1e7856882445de8cc3e8b3b",
          "md5": "1130e5d0ffff4b4fe41e4922686c4e44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.4.2.jar",
          "url": "http-1.4.2.jar",
          "size": 104410,
          "sha512": "ff26153d6fe39f359cba34f53805f4fd24d23839b77a27f69d44862da9f22f10c80c0cac9917e0d24f95f2d221da03f3f6ef3751c3fb278e6b12f53dd16469d2",
          "sha256": "14b04f995a3c25c1f5138dc2460b157879f55d921cab3655c033f33085db57e1",
          "sha1": "111ba69c20144638f1e7856882445de8cc3e8b3b",
          "md5": "1130e5d0ffff4b4fe41e4922686c4e44"
        }
      ]
    }
  ]
}
