{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.0.jar",
          "url": "scripts-1.6.0.jar",
          "size": 31942,
          "sha512": "a3a4691ad6af85df36306933b1c6bb7d7ddaea8ee9e9fab8aeba677f4c696e123bb61c6e8e467949aed479de62e95cfae7c8ac4dd7d70569f06b4cc471add3b5",
          "sha256": "78f501f03f9ba22803c735004f1a13c73e228b0f434fc54098ea862eea10f655",
          "sha1": "9aba3a80c0c6081127b9883d4488da59942955c7",
          "md5": "1f21d946518f9fbb271c073b2c299ec9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.0.jar",
          "url": "scripts-1.6.0.jar",
          "size": 31942,
          "sha512": "a3a4691ad6af85df36306933b1c6bb7d7ddaea8ee9e9fab8aeba677f4c696e123bb61c6e8e467949aed479de62e95cfae7c8ac4dd7d70569f06b4cc471add3b5",
          "sha256": "78f501f03f9ba22803c735004f1a13c73e228b0f434fc54098ea862eea10f655",
          "sha1": "9aba3a80c0c6081127b9883d4488da59942955c7",
          "md5": "1f21d946518f9fbb271c073b2c299ec9"
        }
      ]
    }
  ]
}
