{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.5.jar",
          "url": "annotations-1.4.5.jar",
          "size": 8843,
          "sha512": "f53aa1a7c3fda88152a7c46c6bff2189b68e990f43a74bb96af50468cd4962cc06fa874315e13b8db0812d9317623eb3810f9eb1ab9f27515a0315fb14d0bf63",
          "sha256": "7cf9043508b473618fbb00510b2e6c9ff2556d930a05cfc4951c2f99f6ca3c62",
          "sha1": "1bb6a73a8859b32cdb29e3f572aa63b2ea4b7e5b",
          "md5": "a745261159a6444f3a7b962a3f5e405b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.5.jar",
          "url": "annotations-1.4.5.jar",
          "size": 8843,
          "sha512": "f53aa1a7c3fda88152a7c46c6bff2189b68e990f43a74bb96af50468cd4962cc06fa874315e13b8db0812d9317623eb3810f9eb1ab9f27515a0315fb14d0bf63",
          "sha256": "7cf9043508b473618fbb00510b2e6c9ff2556d930a05cfc4951c2f99f6ca3c62",
          "sha1": "1bb6a73a8859b32cdb29e3f572aa63b2ea4b7e5b",
          "md5": "a745261159a6444f3a7b962a3f5e405b"
        }
      ]
    }
  ]
}
