{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.4.1.jar",
          "url": "http-1.4.1.jar",
          "size": 104410,
          "sha512": "ac0fa1e649dce90a386931e5cdf7f63fb4fcac49cdca41d32676bbd8113fbbe566afbdb56bbb5612251150c54a7eb8b210301260049348a60a1479be2edfff8a",
          "sha256": "62d0b463b3fe5f9231dc6931b519021208fae6f492a5af8b68dd4ce622c4ad93",
          "sha1": "87f7b7bfe309aea90b27a8c815196cf739715028",
          "md5": "485091b44633d6b8f421a12319e2f5d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.4.1.jar",
          "url": "http-1.4.1.jar",
          "size": 104410,
          "sha512": "ac0fa1e649dce90a386931e5cdf7f63fb4fcac49cdca41d32676bbd8113fbbe566afbdb56bbb5612251150c54a7eb8b210301260049348a60a1479be2edfff8a",
          "sha256": "62d0b463b3fe5f9231dc6931b519021208fae6f492a5af8b68dd4ce622c4ad93",
          "sha1": "87f7b7bfe309aea90b27a8c815196cf739715028",
          "md5": "485091b44633d6b8f421a12319e2f5d9"
        }
      ]
    }
  ]
}
