{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.2.jar",
          "url": "api-1.0.2.jar",
          "size": 1398855,
          "sha512": "0951cadfdd35388ad5e283e2852028d72496cd57d99eb83cf724e5a89e49371c3a9a852040b13b2c9545f972f9b42e6d5c2f7ca22d4ec64aa5a64d7a0d34d8a2",
          "sha256": "4d04eaa0eb76ecbf7f6a30a40e2d9cf485ca25361b49c53ba1989c79f19a8d36",
          "sha1": "9f24455cf1f5d1281524c213a108093ef020f149",
          "md5": "dcd14247c947546cfab32a45332d2fe7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.2.jar",
          "url": "api-1.0.2.jar",
          "size": 1398855,
          "sha512": "0951cadfdd35388ad5e283e2852028d72496cd57d99eb83cf724e5a89e49371c3a9a852040b13b2c9545f972f9b42e6d5c2f7ca22d4ec64aa5a64d7a0d34d8a2",
          "sha256": "4d04eaa0eb76ecbf7f6a30a40e2d9cf485ca25361b49c53ba1989c79f19a8d36",
          "sha1": "9f24455cf1f5d1281524c213a108093ef020f149",
          "md5": "dcd14247c947546cfab32a45332d2fe7"
        }
      ]
    }
  ]
}
