{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.14.jar",
          "url": "api-rs-1.6.14.jar",
          "size": 124064,
          "sha512": "768103a5a1e93d3a9600e3d92cb15cd53b1f20177b932360ee8fb8c93302a756272f7581974876181f49b8d57b7381ccb27c882cbf5cea307ed8b3a96ce6000c",
          "sha256": "831f112e1ef659a6a809eb5521fa96cbc6d82b4db5e66951b17d99a08cc8b882",
          "sha1": "25b7b4e4f40360c4d0e81e740dbc0e7537266c66",
          "md5": "6a84c3e7e5e7ff1dac815f9bb5b63509"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.14"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.14.jar",
          "url": "api-rs-1.6.14.jar",
          "size": 124064,
          "sha512": "768103a5a1e93d3a9600e3d92cb15cd53b1f20177b932360ee8fb8c93302a756272f7581974876181f49b8d57b7381ccb27c882cbf5cea307ed8b3a96ce6000c",
          "sha256": "831f112e1ef659a6a809eb5521fa96cbc6d82b4db5e66951b17d99a08cc8b882",
          "sha1": "25b7b4e4f40360c4d0e81e740dbc0e7537266c66",
          "md5": "6a84c3e7e5e7ff1dac815f9bb5b63509"
        }
      ]
    }
  ]
}
