{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.0.jar",
          "url": "api-rs-1.6.0.jar",
          "size": 123367,
          "sha512": "7017e08ae79f8a840500c41dd073536369aaba71f498306c55c5dfa078e1fb1ceb8bab606cf3ceb0b21eee281ff5f376c429850bcd0d2950a3073889c6dedd41",
          "sha256": "39ccb2c79f94fa3fe6b3fc1d7e0174f277f0a26435880e5448c511ba7d75cc76",
          "sha1": "42f0723bd71efc0b6598a98f535bbaa453641ac8",
          "md5": "8d60993d3abed96666e01a71f16fd50b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.0.jar",
          "url": "api-rs-1.6.0.jar",
          "size": 123367,
          "sha512": "7017e08ae79f8a840500c41dd073536369aaba71f498306c55c5dfa078e1fb1ceb8bab606cf3ceb0b21eee281ff5f376c429850bcd0d2950a3073889c6dedd41",
          "sha256": "39ccb2c79f94fa3fe6b3fc1d7e0174f277f0a26435880e5448c511ba7d75cc76",
          "sha1": "42f0723bd71efc0b6598a98f535bbaa453641ac8",
          "md5": "8d60993d3abed96666e01a71f16fd50b"
        }
      ]
    }
  ]
}
