{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.13.jar",
          "url": "http-1.6.13.jar",
          "size": 104688,
          "sha512": "627ca5d856768f0f5bac62733ae6991fbc84303039bd12b69e7e61c65a9f546ef06d2681ebf248ce56d511aee873ee58c9ba886cd29f151f71d1a4267ce31182",
          "sha256": "5148d81d58cc073b183e05fa8cd5d7bf43534a02f12152e081555bee556f82c1",
          "sha1": "50004a19ca3d4e30d8a118fc189e9bf9386a258d",
          "md5": "9a2036fa9f54ce9e2e95596414b0cebb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.13"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.13"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.13.jar",
          "url": "http-1.6.13.jar",
          "size": 104688,
          "sha512": "627ca5d856768f0f5bac62733ae6991fbc84303039bd12b69e7e61c65a9f546ef06d2681ebf248ce56d511aee873ee58c9ba886cd29f151f71d1a4267ce31182",
          "sha256": "5148d81d58cc073b183e05fa8cd5d7bf43534a02f12152e081555bee556f82c1",
          "sha1": "50004a19ca3d4e30d8a118fc189e9bf9386a258d",
          "md5": "9a2036fa9f54ce9e2e95596414b0cebb"
        }
      ]
    }
  ]
}
