{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.12.jar",
          "url": "api-1.0.12.jar",
          "size": 1292360,
          "sha512": "e58d3a26db95ea6bd88b15e0c6922fdf41ee3f99404d48073c7fd51061cd569fecc48e8f0b3f09753e410659294c8c5ec29b745fc78e0b8be8233dddfd78d909",
          "sha256": "1835bcc043e7b9939d5898873e54cbf4b67eb2a1c0b0c3fbf798d431ded0a3b2",
          "sha1": "81e2e89732ebeef7b08ab229b40323cab743903e",
          "md5": "dc18c83482f19d8b004b1b2513ba47cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.12"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.12.jar",
          "url": "api-1.0.12.jar",
          "size": 1292360,
          "sha512": "e58d3a26db95ea6bd88b15e0c6922fdf41ee3f99404d48073c7fd51061cd569fecc48e8f0b3f09753e410659294c8c5ec29b745fc78e0b8be8233dddfd78d909",
          "sha256": "1835bcc043e7b9939d5898873e54cbf4b67eb2a1c0b0c3fbf798d431ded0a3b2",
          "sha1": "81e2e89732ebeef7b08ab229b40323cab743903e",
          "md5": "dc18c83482f19d8b004b1b2513ba47cf"
        }
      ]
    }
  ]
}
