{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.3.jar",
          "url": "api-rs-1.5.3.jar",
          "size": 122758,
          "sha512": "f4a4d45f20e88d9eefc509e0affcd7d50b67a452242e1936f189e7c9945d643eac0dac6592e8daa426ee4bbacd865960d1b376ec3eb7914564d470c646fe3cf6",
          "sha256": "ddc50069d523fd3cd7db6b1fee8b1cd8fb00a830e2eecd631e6454f01dfa610f",
          "sha1": "4c37656ca75a89e4d6e8bbc30e1e95b441119b04",
          "md5": "361246f06c9479a8b4e2d8cb2b549934"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.3.jar",
          "url": "api-rs-1.5.3.jar",
          "size": 122758,
          "sha512": "f4a4d45f20e88d9eefc509e0affcd7d50b67a452242e1936f189e7c9945d643eac0dac6592e8daa426ee4bbacd865960d1b376ec3eb7914564d470c646fe3cf6",
          "sha256": "ddc50069d523fd3cd7db6b1fee8b1cd8fb00a830e2eecd631e6454f01dfa610f",
          "sha1": "4c37656ca75a89e4d6e8bbc30e1e95b441119b04",
          "md5": "361246f06c9479a8b4e2d8cb2b549934"
        }
      ]
    }
  ]
}
