{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.3.jar",
          "url": "api-rs-1.5.3.jar",
          "size": 123539,
          "sha512": "51c746e82fd9620d86e79a4f7587f2e2f786f85a87537a882421d889ffc303b7735a0b820f078b6ea171ee5515ed04f976335889d5851ad455d042e63ebf5533",
          "sha256": "79b9dd815bc25afb19970e705d8a656b403760cf13169582aa0d68f9442d31e3",
          "sha1": "5be93a7e387aba4aaea89b5c5aa9826cfcc862d5",
          "md5": "3b24e1a088e463b36a537091fa14cc5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.3.jar",
          "url": "api-rs-1.5.3.jar",
          "size": 123539,
          "sha512": "51c746e82fd9620d86e79a4f7587f2e2f786f85a87537a882421d889ffc303b7735a0b820f078b6ea171ee5515ed04f976335889d5851ad455d042e63ebf5533",
          "sha256": "79b9dd815bc25afb19970e705d8a656b403760cf13169582aa0d68f9442d31e3",
          "sha1": "5be93a7e387aba4aaea89b5c5aa9826cfcc862d5",
          "md5": "3b24e1a088e463b36a537091fa14cc5d"
        }
      ]
    }
  ]
}
