{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.0.0.jar",
          "url": "scripts-1.0.0.jar",
          "size": 28990,
          "sha512": "606e52e725151a2058290104e937ae96de89951b4e59fad39bffa781ab2d40ea59e62b7f2cad619ec13bd68f78dbb7b0a76858f5d1e3eda9175d8e0e04d9daf5",
          "sha256": "9c4fdbc334170f83d2965b40d7f22f2e99261ef1cec72bcdadb4879d3c6a61a2",
          "sha1": "a4715cd98d720aef3a83b9fe30dd4ef3de88c414",
          "md5": "e0f4b20244b07a8b93af510dc39b2547"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.0.0.jar",
          "url": "scripts-1.0.0.jar",
          "size": 28990,
          "sha512": "606e52e725151a2058290104e937ae96de89951b4e59fad39bffa781ab2d40ea59e62b7f2cad619ec13bd68f78dbb7b0a76858f5d1e3eda9175d8e0e04d9daf5",
          "sha256": "9c4fdbc334170f83d2965b40d7f22f2e99261ef1cec72bcdadb4879d3c6a61a2",
          "sha1": "a4715cd98d720aef3a83b9fe30dd4ef3de88c414",
          "md5": "e0f4b20244b07a8b93af510dc39b2547"
        }
      ]
    }
  ]
}
