{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.2.11.jar",
          "url": "api-rs-1.2.11.jar",
          "size": 122504,
          "sha512": "da0e208bf086fd64fbde6c5904e7d6e7c76d27b4b01efb547cf2a0dd95771ede67d18ad688187d9d54cb3c59c6b485abf96f026cc5c9970900949844c1ef9b6d",
          "sha256": "d71f68ea54db44f0ab0badc1dfe9610ceb9cb78dd7c8cd9a6578b7fadc139c9c",
          "sha1": "715048a383fe7c80d89a60e18b15ad1a7bd47462",
          "md5": "b8dac4c7b827b840986bf37e08bbf9e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.11.jar",
          "url": "api-rs-1.2.11.jar",
          "size": 122504,
          "sha512": "da0e208bf086fd64fbde6c5904e7d6e7c76d27b4b01efb547cf2a0dd95771ede67d18ad688187d9d54cb3c59c6b485abf96f026cc5c9970900949844c1ef9b6d",
          "sha256": "d71f68ea54db44f0ab0badc1dfe9610ceb9cb78dd7c8cd9a6578b7fadc139c9c",
          "sha1": "715048a383fe7c80d89a60e18b15ad1a7bd47462",
          "md5": "b8dac4c7b827b840986bf37e08bbf9e6"
        }
      ]
    }
  ]
}
