{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-2.4.0.jar",
          "url": "logger-2.4.0.jar",
          "size": 8658,
          "sha512": "86bdeae1a181a388d654498b948a97a67c54f63a4c274665fba04225100a84bf94645494523ce69cea1d9b2af131934f8f6ba6f3abec62a621f82ab4f6fdf1e6",
          "sha256": "858d69fa3360d3f8223b94d09bc798b07a1bdb9ba14f81421a8816d5ea0a50f8",
          "sha1": "a7ad27008ef7e26755f4fcfaf6f73a0a17ff943c",
          "md5": "3a8c582b0e73f2e7a22080a669018a41"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-2.4.0.jar",
          "url": "logger-2.4.0.jar",
          "size": 8658,
          "sha512": "86bdeae1a181a388d654498b948a97a67c54f63a4c274665fba04225100a84bf94645494523ce69cea1d9b2af131934f8f6ba6f3abec62a621f82ab4f6fdf1e6",
          "sha256": "858d69fa3360d3f8223b94d09bc798b07a1bdb9ba14f81421a8816d5ea0a50f8",
          "sha1": "a7ad27008ef7e26755f4fcfaf6f73a0a17ff943c",
          "md5": "3a8c582b0e73f2e7a22080a669018a41"
        }
      ]
    }
  ]
}
