{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.2.jar",
          "url": "api-1.6.2.jar",
          "size": 1337273,
          "sha512": "a07de57a9e25f79adb0c078f915b3abadfa2835e55c96d856f4b144ec9c47cc81ba4f5ad6f4b7209ecaee79b2559ff5c10a6fcaecff33de6e5aeab6216800cd3",
          "sha256": "a6be61666afb561b1cbcc8455bcb788563b9190297f6893cca674a0c3806f05d",
          "sha1": "8d7850d677ac6e55a366cbed4f7752f4072af5be",
          "md5": "ef84b42c84f9ddb69cc09d66dfc08de2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.2.jar",
          "url": "api-1.6.2.jar",
          "size": 1337273,
          "sha512": "a07de57a9e25f79adb0c078f915b3abadfa2835e55c96d856f4b144ec9c47cc81ba4f5ad6f4b7209ecaee79b2559ff5c10a6fcaecff33de6e5aeab6216800cd3",
          "sha256": "a6be61666afb561b1cbcc8455bcb788563b9190297f6893cca674a0c3806f05d",
          "sha1": "8d7850d677ac6e55a366cbed4f7752f4072af5be",
          "md5": "ef84b42c84f9ddb69cc09d66dfc08de2"
        }
      ]
    }
  ]
}
