{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.2.jar",
          "url": "api-1.6.2.jar",
          "size": 1337273,
          "sha512": "54da96f3a4973f4f65e0e6fc06568b8e7f0debeb04720bc3af96ac915657ea34191e93c99b212df0574a6203a948be4ddb991324310f7ad002b054c9b5a611e5",
          "sha256": "705141297b8d2f34871f6f474f9764047391290cdeb2af2f82620b0caee594b2",
          "sha1": "fc0fc73e711ca4717759ba993068dd1ee063198d",
          "md5": "f207135e62a84c0052648c7c7d8eca20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.2.jar",
          "url": "api-1.6.2.jar",
          "size": 1337273,
          "sha512": "54da96f3a4973f4f65e0e6fc06568b8e7f0debeb04720bc3af96ac915657ea34191e93c99b212df0574a6203a948be4ddb991324310f7ad002b054c9b5a611e5",
          "sha256": "705141297b8d2f34871f6f474f9764047391290cdeb2af2f82620b0caee594b2",
          "sha1": "fc0fc73e711ca4717759ba993068dd1ee063198d",
          "md5": "f207135e62a84c0052648c7c7d8eca20"
        }
      ]
    }
  ]
}
