{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.7.jar",
          "url": "logger-1.6.7.jar",
          "size": 8579,
          "sha512": "76824157ee6d6fe2cfc83db9e2f1d903c1824df7b4e9d7c695584941404bd8b63863564ebcbde4c5de16e4fb287501fd0a824c20b4d62b976e0c29545fa7992d",
          "sha256": "469b05cc8c9536edc421d374738e915ae59c8099f669d4e493c82e4970c87489",
          "sha1": "7d43fd5548ea652a852fbfa2b3a3dfd4213827d7",
          "md5": "c2460ffeb45dc20d65de3872694f5f09"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.7.jar",
          "url": "logger-1.6.7.jar",
          "size": 8579,
          "sha512": "76824157ee6d6fe2cfc83db9e2f1d903c1824df7b4e9d7c695584941404bd8b63863564ebcbde4c5de16e4fb287501fd0a824c20b4d62b976e0c29545fa7992d",
          "sha256": "469b05cc8c9536edc421d374738e915ae59c8099f669d4e493c82e4970c87489",
          "sha1": "7d43fd5548ea652a852fbfa2b3a3dfd4213827d7",
          "md5": "c2460ffeb45dc20d65de3872694f5f09"
        }
      ]
    }
  ]
}
