{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rationalityfrontline",
    "module": "kevent",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kevent-2.1.2.jar",
          "url": "kevent-2.1.2.jar",
          "size": 53023,
          "sha512": "19054233e2de419bdc6a0e25f1adbdcb11798bb2f074e055a90c534f6df2b7df22daca20db19a6f62e138ddc7eb3cc408cffeb25ff541ed7796c4bc551caf3af",
          "sha256": "470de2e0341bc17197da11baf175094f7fac8a10b02612d594dddf5b99cacde3",
          "sha1": "e42a373d6637979fd8c47744b5e4c5ad82ffee16",
          "md5": "e8250431d527abd9230bc888627a19bb"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kevent-2.1.2.jar",
          "url": "kevent-2.1.2.jar",
          "size": 53023,
          "sha512": "19054233e2de419bdc6a0e25f1adbdcb11798bb2f074e055a90c534f6df2b7df22daca20db19a6f62e138ddc7eb3cc408cffeb25ff541ed7796c4bc551caf3af",
          "sha256": "470de2e0341bc17197da11baf175094f7fac8a10b02612d594dddf5b99cacde3",
          "sha1": "e42a373d6637979fd8c47744b5e4c5ad82ffee16",
          "md5": "e8250431d527abd9230bc888627a19bb"
        }
      ]
    }
  ]
}
