{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.5.jar",
          "url": "http-1.6.5.jar",
          "size": 104648,
          "sha512": "fcfd9ea05520984432e7806432ae974d0f304f80bffd5a6755e25312cec5da7714602c5db466bfa67bfef91cdf3ee2dd07dd77d15acc23ddf8fded1744b50992",
          "sha256": "8981d79861b699cd04eb221acfc1ebb2b705c792d1005adf4ae5b51e171bc71d",
          "sha1": "cc91f2b654fb32574c2ee29082496cea5b06cca7",
          "md5": "d41b7d07207793622eb062d39c216d6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.5.jar",
          "url": "http-1.6.5.jar",
          "size": 104648,
          "sha512": "fcfd9ea05520984432e7806432ae974d0f304f80bffd5a6755e25312cec5da7714602c5db466bfa67bfef91cdf3ee2dd07dd77d15acc23ddf8fded1744b50992",
          "sha256": "8981d79861b699cd04eb221acfc1ebb2b705c792d1005adf4ae5b51e171bc71d",
          "sha1": "cc91f2b654fb32574c2ee29082496cea5b06cca7",
          "md5": "d41b7d07207793622eb062d39c216d6f"
        }
      ]
    }
  ]
}
