{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.12.jar",
          "url": "http-1.6.12.jar",
          "size": 104688,
          "sha512": "59c35a833256661a988e8ee9d9c11905dd2d72083068f0ae2e7619f8ee25edb682b6f88d5e514c7848e8fd0fc9d7ea02303106efb1a8b8cb9b2cef1eb0122d4c",
          "sha256": "0c604d857184a4113722b1a90e34068a8e85c31f3d97e73345909194112c824c",
          "sha1": "3973ce6bb5629e33529fa29614eee42fa475a5a2",
          "md5": "4d81ce01712e14869366c02209873c41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.12.jar",
          "url": "http-1.6.12.jar",
          "size": 104688,
          "sha512": "59c35a833256661a988e8ee9d9c11905dd2d72083068f0ae2e7619f8ee25edb682b6f88d5e514c7848e8fd0fc9d7ea02303106efb1a8b8cb9b2cef1eb0122d4c",
          "sha256": "0c604d857184a4113722b1a90e34068a8e85c31f3d97e73345909194112c824c",
          "sha1": "3973ce6bb5629e33529fa29614eee42fa475a5a2",
          "md5": "4d81ce01712e14869366c02209873c41"
        }
      ]
    }
  ]
}
