{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.14.jar",
          "url": "api-1.0.14.jar",
          "size": 1292405,
          "sha512": "5c55c73db42c1fd0bba5029770edd3fc92a16de403c7bcd2437e7713f8e770e650f9e5ef1e932486964ac502eddecb2d58d80c7175f1646676e0aaf86406b354",
          "sha256": "0ce0835550d3f1137a114dc5d006efeee87c72d9f12ae7508a0462b250121657",
          "sha1": "9cf97cd7a16238d0cea9fc9b8108097ed75484bc",
          "md5": "bc8442abd69738a363021c927014cde1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.14"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.14.jar",
          "url": "api-1.0.14.jar",
          "size": 1292405,
          "sha512": "5c55c73db42c1fd0bba5029770edd3fc92a16de403c7bcd2437e7713f8e770e650f9e5ef1e932486964ac502eddecb2d58d80c7175f1646676e0aaf86406b354",
          "sha256": "0ce0835550d3f1137a114dc5d006efeee87c72d9f12ae7508a0462b250121657",
          "sha1": "9cf97cd7a16238d0cea9fc9b8108097ed75484bc",
          "md5": "bc8442abd69738a363021c927014cde1"
        }
      ]
    }
  ]
}
