{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.3.jar",
          "url": "logger-1.2.3.jar",
          "size": 8662,
          "sha512": "ddd9da414528b740b3ea0911a34df88189d51eda5221b8816e5b1d0b4b4e96db8d7ea4fd74cd92b7320cb023675c12f20a7b9dbb4a5c1f9a9213ab73bf880a82",
          "sha256": "7e5956bd061295967fbfba8590ebfb254ba326ef5572c678334abf42801dfc3c",
          "sha1": "e1bd374142a15dbc014b1952bb3863a694da28f9",
          "md5": "f1b822245ac53eb3d80e6598b02ae5ba"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.3.jar",
          "url": "logger-1.2.3.jar",
          "size": 8662,
          "sha512": "ddd9da414528b740b3ea0911a34df88189d51eda5221b8816e5b1d0b4b4e96db8d7ea4fd74cd92b7320cb023675c12f20a7b9dbb4a5c1f9a9213ab73bf880a82",
          "sha256": "7e5956bd061295967fbfba8590ebfb254ba326ef5572c678334abf42801dfc3c",
          "sha1": "e1bd374142a15dbc014b1952bb3863a694da28f9",
          "md5": "f1b822245ac53eb3d80e6598b02ae5ba"
        }
      ]
    }
  ]
}
