{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.1.jar",
          "url": "api-1.6.1.jar",
          "size": 1337766,
          "sha512": "871d09e92759fd8307b1f0ae7d4680a113d52b86fc63cc6ceab3488a6dada3c9ed6199034a7586f3292f56c5f5d44083399f0c2ac9840df7d55ec345b5c89c10",
          "sha256": "68ffa52f642d628b8fade18140b0dd49251e468d7d2942876bd088d0c325a18b",
          "sha1": "4046538faea67bca1f2fe88db0480309c5086e8d",
          "md5": "5e352f06be129be9612af8cb0fa5906b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.1.jar",
          "url": "api-1.6.1.jar",
          "size": 1337766,
          "sha512": "871d09e92759fd8307b1f0ae7d4680a113d52b86fc63cc6ceab3488a6dada3c9ed6199034a7586f3292f56c5f5d44083399f0c2ac9840df7d55ec345b5c89c10",
          "sha256": "68ffa52f642d628b8fade18140b0dd49251e468d7d2942876bd088d0c325a18b",
          "sha1": "4046538faea67bca1f2fe88db0480309c5086e8d",
          "md5": "5e352f06be129be9612af8cb0fa5906b"
        }
      ]
    }
  ]
}
