{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-3.0.0.jar",
          "url": "api-3.0.0.jar",
          "size": 1337402,
          "sha512": "6ce3517bdf858b652dc056fe2484b107b69b562f031bb8ec2318ee4de3cc15c4d8a7d0bbe8f423af89f23427784f4c7f932b2ca39ef6bc607c5a58c6c2e3f543",
          "sha256": "498c9f7121bd054c20cb0b5799f66d7ed970cab15b61d7bff8fc09f40b428d46",
          "sha1": "8d02378b32c281db565ad91520a7d8a54d5a318f",
          "md5": "d6c94463a934c9420a652fa6de31eb89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-3.0.0.jar",
          "url": "api-3.0.0.jar",
          "size": 1337402,
          "sha512": "6ce3517bdf858b652dc056fe2484b107b69b562f031bb8ec2318ee4de3cc15c4d8a7d0bbe8f423af89f23427784f4c7f932b2ca39ef6bc607c5a58c6c2e3f543",
          "sha256": "498c9f7121bd054c20cb0b5799f66d7ed970cab15b61d7bff8fc09f40b428d46",
          "sha1": "8d02378b32c281db565ad91520a7d8a54d5a318f",
          "md5": "d6c94463a934c9420a652fa6de31eb89"
        }
      ]
    }
  ]
}
