{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.12.jar",
          "url": "logger-1.6.12.jar",
          "size": 8579,
          "sha512": "b4c87d70dbabfc2f3b2119bf51dc9f358605104ef5d0f5e87043d2cb922df944d91a881550f833458d0baba3279cfc6814b75b0db008052bcdf40edcf030254c",
          "sha256": "3b911a33d6e6552d43e600d7542d2e9578292d0bd45bca2238439920bad10317",
          "sha1": "9fb6a2322de08483d4b76fa8329acbfae3913956",
          "md5": "75c424f2c2e9b977e72afc1c77e68a48"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.12.jar",
          "url": "logger-1.6.12.jar",
          "size": 8579,
          "sha512": "b4c87d70dbabfc2f3b2119bf51dc9f358605104ef5d0f5e87043d2cb922df944d91a881550f833458d0baba3279cfc6814b75b0db008052bcdf40edcf030254c",
          "sha256": "3b911a33d6e6552d43e600d7542d2e9578292d0bd45bca2238439920bad10317",
          "sha1": "9fb6a2322de08483d4b76fa8329acbfae3913956",
          "md5": "75c424f2c2e9b977e72afc1c77e68a48"
        }
      ]
    }
  ]
}
