{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.13.jar",
          "url": "api-1.2.13.jar",
          "size": 1337402,
          "sha512": "a8ada6faa2195db5d05f4f4894bbdca8dbcfbbbce34236756fb8382b39886d6f5e7081d9da7581adc37e7d81dae558eddf249be28f793512918ac41344db5fe4",
          "sha256": "4a2754e3f90ebaed3f6911e429654c2489805023ddc8530effb33a52a8febd2b",
          "sha1": "3d9cbefb6362eb71375b225a5e09fab4abf57b9f",
          "md5": "50ed641d78f899822258616e3f75ecba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.13.jar",
          "url": "api-1.2.13.jar",
          "size": 1337402,
          "sha512": "a8ada6faa2195db5d05f4f4894bbdca8dbcfbbbce34236756fb8382b39886d6f5e7081d9da7581adc37e7d81dae558eddf249be28f793512918ac41344db5fe4",
          "sha256": "4a2754e3f90ebaed3f6911e429654c2489805023ddc8530effb33a52a8febd2b",
          "sha1": "3d9cbefb6362eb71375b225a5e09fab4abf57b9f",
          "md5": "50ed641d78f899822258616e3f75ecba"
        }
      ]
    }
  ]
}
