{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.15.jar",
          "url": "api-1.6.15.jar",
          "size": 1367744,
          "sha512": "71298f9961a5262c11870468dcdc9b5515d560a63408f847148fae7a4fcfb3a452b1ab32c6b39a535ed495090b267286faaa4c9b4cec8e609dbf24433374a68c",
          "sha256": "0bfd560d74d0f1ab18ee486404f0c865af5691bf8dae205f13e68cf233c9b039",
          "sha1": "be62a65609f3eba2cf7dee1ceaf81613210b0600",
          "md5": "937d625139a91c1b718fb815858e3e69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.15"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.15"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.15.jar",
          "url": "api-1.6.15.jar",
          "size": 1367744,
          "sha512": "71298f9961a5262c11870468dcdc9b5515d560a63408f847148fae7a4fcfb3a452b1ab32c6b39a535ed495090b267286faaa4c9b4cec8e609dbf24433374a68c",
          "sha256": "0bfd560d74d0f1ab18ee486404f0c865af5691bf8dae205f13e68cf233c9b039",
          "sha1": "be62a65609f3eba2cf7dee1ceaf81613210b0600",
          "md5": "937d625139a91c1b718fb815858e3e69"
        }
      ]
    }
  ]
}
