{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.5.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.5.5.jar",
          "url": "http-1.5.5.jar",
          "size": 104410,
          "sha512": "86604795de21c55f4b5726f574ccd86be6576ff7dbd6ef2592f73a15f27cfba5635fafffc171695596ab1c34a065a9641c585087d9a6e66be2ad63de94d442e3",
          "sha256": "4adeac0447ea043588f243981d1279a79e16fbe384ec365fddbfe7ef6dfeb440",
          "sha1": "cdd6cc71b48f25239fb87c8f8778b1892357f784",
          "md5": "f833b1ad192bfac72efc28e3e3b58c4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.5.5.jar",
          "url": "http-1.5.5.jar",
          "size": 104410,
          "sha512": "86604795de21c55f4b5726f574ccd86be6576ff7dbd6ef2592f73a15f27cfba5635fafffc171695596ab1c34a065a9641c585087d9a6e66be2ad63de94d442e3",
          "sha256": "4adeac0447ea043588f243981d1279a79e16fbe384ec365fddbfe7ef6dfeb440",
          "sha1": "cdd6cc71b48f25239fb87c8f8778b1892357f784",
          "md5": "f833b1ad192bfac72efc28e3e3b58c4c"
        }
      ]
    }
  ]
}
