{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 1397864,
          "sha512": "5d67f7360b4b88e14ecc50d3c1d61db191981cf40bf5037773f0cfd26578748cb6b6a8e71b9caae8024769b6ecbdbcd943724456b1cdecca41fc97c746fe2781",
          "sha256": "8a40c9dd7b1785582716ddfbaec306c2b618e4d28f0b4dfbb1dfdb7b16eeea46",
          "sha1": "ab513d9a81dbd636cee7e6cf7c3ac21e0f515e21",
          "md5": "688d6c1c7f12f347cc50288a0fc7b403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 1397864,
          "sha512": "5d67f7360b4b88e14ecc50d3c1d61db191981cf40bf5037773f0cfd26578748cb6b6a8e71b9caae8024769b6ecbdbcd943724456b1cdecca41fc97c746fe2781",
          "sha256": "8a40c9dd7b1785582716ddfbaec306c2b618e4d28f0b4dfbb1dfdb7b16eeea46",
          "sha1": "ab513d9a81dbd636cee7e6cf7c3ac21e0f515e21",
          "md5": "688d6c1c7f12f347cc50288a0fc7b403"
        }
      ]
    }
  ]
}
