{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-4.0.0.jar",
          "url": "http-4.0.0.jar",
          "size": 104410,
          "sha512": "6b563cbf2de199bfee5318f4f7067e52d152b54daad6aa6b8f8535a8579979e0f3518137f08c79230604390ad1c4ca489036d2696d0966aa3dd42df28e863bab",
          "sha256": "644d4128dd3137911d17860dbe648935f6cc985cc52449ae9e021d139693f865",
          "sha1": "9749a8f23873fe56c2b68aeab218cbb39bcd93f5",
          "md5": "b319e0375dbca3f55f91b47f0e521049"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-4.0.0.jar",
          "url": "http-4.0.0.jar",
          "size": 104410,
          "sha512": "6b563cbf2de199bfee5318f4f7067e52d152b54daad6aa6b8f8535a8579979e0f3518137f08c79230604390ad1c4ca489036d2696d0966aa3dd42df28e863bab",
          "sha256": "644d4128dd3137911d17860dbe648935f6cc985cc52449ae9e021d139693f865",
          "sha1": "9749a8f23873fe56c2b68aeab218cbb39bcd93f5",
          "md5": "b319e0375dbca3f55f91b47f0e521049"
        }
      ]
    }
  ]
}
