{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.8.jar",
          "url": "scripts-1.6.8.jar",
          "size": 28428,
          "sha512": "ea943374ee9fc4ddbcad39073d1085e53d1c1bf5a111145e843c9f50aaed68ed6fc747a03e7ab9003b11f44386d151e9a1051b5403622db0e43bea9c8a7d2c6c",
          "sha256": "0396c98a9ed7378d1b99c14c0cae6f5dc68f83ee0a949f4ef535cada162f23f9",
          "sha1": "9eeb03c5f95e422e5c6447460f6d47341d076dde",
          "md5": "958600bb36fef6a787f9af36076f1acf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.8.jar",
          "url": "scripts-1.6.8.jar",
          "size": 28428,
          "sha512": "ea943374ee9fc4ddbcad39073d1085e53d1c1bf5a111145e843c9f50aaed68ed6fc747a03e7ab9003b11f44386d151e9a1051b5403622db0e43bea9c8a7d2c6c",
          "sha256": "0396c98a9ed7378d1b99c14c0cae6f5dc68f83ee0a949f4ef535cada162f23f9",
          "sha1": "9eeb03c5f95e422e5c6447460f6d47341d076dde",
          "md5": "958600bb36fef6a787f9af36076f1acf"
        }
      ]
    }
  ]
}
