{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.3.jar",
          "url": "api-1.4.3.jar",
          "size": 1338053,
          "sha512": "1c592a51c6768ac7768cacf81461badd9b3bcee6b0aca53069d8a8848335ce1f267133a53c3d1c895f1d9f0b52bd2deb3d8848c1af9f048757aede455e29ac43",
          "sha256": "9bc7b357d3d76538e8cdabfc88c77e88b9b7b4445bd2d4afc3641117c1ef721c",
          "sha1": "7583afdc735dfcb31607519c1c9fde043266855f",
          "md5": "1ea84f4b52d43eba08c3a0f749d1230f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.3.jar",
          "url": "api-1.4.3.jar",
          "size": 1338053,
          "sha512": "1c592a51c6768ac7768cacf81461badd9b3bcee6b0aca53069d8a8848335ce1f267133a53c3d1c895f1d9f0b52bd2deb3d8848c1af9f048757aede455e29ac43",
          "sha256": "9bc7b357d3d76538e8cdabfc88c77e88b9b7b4445bd2d4afc3641117c1ef721c",
          "sha1": "7583afdc735dfcb31607519c1c9fde043266855f",
          "md5": "1ea84f4b52d43eba08c3a0f749d1230f"
        }
      ]
    }
  ]
}
