{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.9.jar",
          "url": "logger-1.6.9.jar",
          "size": 8579,
          "sha512": "d706d09d9ece74ea2f99219c5c957f3d75328770e625c11f4fa8c45a1ecaf28ff8fc394bf42731185060867e448113339913df4513f636d6e56e0e0fcf843d98",
          "sha256": "b6a0c28772cd541711508958875807c530e2658e0cd729e210eafc00f7da92b2",
          "sha1": "c51be81482e9d6b6e783b46a2d454122cffd3ecd",
          "md5": "e7273d0dcfe45a227d77e9b52e97dc2e"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.9.jar",
          "url": "logger-1.6.9.jar",
          "size": 8579,
          "sha512": "d706d09d9ece74ea2f99219c5c957f3d75328770e625c11f4fa8c45a1ecaf28ff8fc394bf42731185060867e448113339913df4513f636d6e56e0e0fcf843d98",
          "sha256": "b6a0c28772cd541711508958875807c530e2658e0cd729e210eafc00f7da92b2",
          "sha1": "c51be81482e9d6b6e783b46a2d454122cffd3ecd",
          "md5": "e7273d0dcfe45a227d77e9b52e97dc2e"
        }
      ]
    }
  ]
}
