{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.8.jar",
          "url": "annotations-1.4.8.jar",
          "size": 8843,
          "sha512": "b289be906271c85d8e644e634034a03900e8db46a166ad9929e0647cb9fec83a81b65ec0500d904252817864eca602407015de680572d1c44dd56c55da2e84d3",
          "sha256": "61a451efe0fe04e271fc11412aedd037d962f31568b2856040669cbc8809d923",
          "sha1": "023dc8f72ea6e0b4188bba08a126a19df2aa3db6",
          "md5": "f6cc56a8057d0b9604f3fbba65abead0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.8.jar",
          "url": "annotations-1.4.8.jar",
          "size": 8843,
          "sha512": "b289be906271c85d8e644e634034a03900e8db46a166ad9929e0647cb9fec83a81b65ec0500d904252817864eca602407015de680572d1c44dd56c55da2e84d3",
          "sha256": "61a451efe0fe04e271fc11412aedd037d962f31568b2856040669cbc8809d923",
          "sha1": "023dc8f72ea6e0b4188bba08a126a19df2aa3db6",
          "md5": "f6cc56a8057d0b9604f3fbba65abead0"
        }
      ]
    }
  ]
}
