{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.0.0.jar",
          "url": "api-rs-1.0.0.jar",
          "size": 116641,
          "sha512": "811eb310100aa53f58c2ca5df540370c81e6a97529117260449ffad170c7ef5efec03990b5b8a80371603ef0ceb3753fe9ec02b60118e644db0d5c9ac878a106",
          "sha256": "3575588a090248abb06280aca40a209494002a50399bbeda2a1b03c48e283581",
          "sha1": "8295e8f697689eee53552c291741968f3fa62a6c",
          "md5": "4fa05aa7d79482728b7cf5c254caf3b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.0.0.jar",
          "url": "api-rs-1.0.0.jar",
          "size": 116641,
          "sha512": "811eb310100aa53f58c2ca5df540370c81e6a97529117260449ffad170c7ef5efec03990b5b8a80371603ef0ceb3753fe9ec02b60118e644db0d5c9ac878a106",
          "sha256": "3575588a090248abb06280aca40a209494002a50399bbeda2a1b03c48e283581",
          "sha1": "8295e8f697689eee53552c291741968f3fa62a6c",
          "md5": "4fa05aa7d79482728b7cf5c254caf3b1"
        }
      ]
    }
  ]
}
