{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.0.0.jar",
          "url": "api-rs-1.0.0.jar",
          "size": 116641,
          "sha512": "9e9449623c6616b3a172fd369c8587527037376cf23a472a3f2397fd2a92e1a85d30c76c2247cf37c6ad462ae4e4981c690766b17228fd6adc58bb1a6d5e11c6",
          "sha256": "fa7e2d4cff4d3037438617cfc07c98783e44a444e2e6a06c7032fe022e885423",
          "sha1": "6b6d69b5e41ac455429585556af49e4a0d7754bb",
          "md5": "77ed07b72eb931afb9b8bf7294fa15f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.0.0.jar",
          "url": "api-rs-1.0.0.jar",
          "size": 116641,
          "sha512": "9e9449623c6616b3a172fd369c8587527037376cf23a472a3f2397fd2a92e1a85d30c76c2247cf37c6ad462ae4e4981c690766b17228fd6adc58bb1a6d5e11c6",
          "sha256": "fa7e2d4cff4d3037438617cfc07c98783e44a444e2e6a06c7032fe022e885423",
          "sha1": "6b6d69b5e41ac455429585556af49e4a0d7754bb",
          "md5": "77ed07b72eb931afb9b8bf7294fa15f7"
        }
      ]
    }
  ]
}
