{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.11.jar",
          "url": "api-1.2.11.jar",
          "size": 1338451,
          "sha512": "c468bcc225426a411f1656239d5dc066d7fd31ce9b078089ca1eef8d8003f6e90e617ad2be753f3404d1c1fefbe7accccab3845253b6aa843a2a17dd23f7e0d7",
          "sha256": "077b51e1bae3b03b325c3f48a91100cad421eecc808d236de9942d9fe5687bef",
          "sha1": "1f8ee473e2ad71fc92f67a84b369ad1c30563a63",
          "md5": "7676406d8cdee53f646f0929984f9cc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.11.jar",
          "url": "api-1.2.11.jar",
          "size": 1338451,
          "sha512": "c468bcc225426a411f1656239d5dc066d7fd31ce9b078089ca1eef8d8003f6e90e617ad2be753f3404d1c1fefbe7accccab3845253b6aa843a2a17dd23f7e0d7",
          "sha256": "077b51e1bae3b03b325c3f48a91100cad421eecc808d236de9942d9fe5687bef",
          "sha1": "1f8ee473e2ad71fc92f67a84b369ad1c30563a63",
          "md5": "7676406d8cdee53f646f0929984f9cc1"
        }
      ]
    }
  ]
}
