{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0.0.jar",
          "url": "logger-1.0.0.jar",
          "size": 8391,
          "sha512": "4dadb9585e40c71998a20568946e89e8704f959f0fd75887f11001a9fac93e6feda64dd02a21010f72954b77a11349fcbb2c58c93db31126bd896c205c96574d",
          "sha256": "25f05bcad9f3a11602164cadf3b77568a98df765cd0b4ef3287ab2832af8ed20",
          "sha1": "d3d0b4d295e17d51999d97c8638da705bed001fc",
          "md5": "a580983e393d68107ed703968e6def6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.0.0.jar",
          "url": "logger-1.0.0.jar",
          "size": 8391,
          "sha512": "4dadb9585e40c71998a20568946e89e8704f959f0fd75887f11001a9fac93e6feda64dd02a21010f72954b77a11349fcbb2c58c93db31126bd896c205c96574d",
          "sha256": "25f05bcad9f3a11602164cadf3b77568a98df765cd0b4ef3287ab2832af8ed20",
          "sha1": "d3d0b4d295e17d51999d97c8638da705bed001fc",
          "md5": "a580983e393d68107ed703968e6def6b"
        }
      ]
    }
  ]
}
