{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.4.6.jar",
          "url": "http-1.4.6.jar",
          "size": 104410,
          "sha512": "d39101d90074b6f6e37ed16ddd7de93af141df4a38129e084d0ff7b955fa629d13dfc88c49cdc14215dc6c855c13c38e9590d314356a48edc5a8ecf0544cc16f",
          "sha256": "a35373a5b041bafbf5bc8716b6eba4d98ce978da73bdfe11348426215dbd3f54",
          "sha1": "d39202d11097a566de3f1cfa8a174e5406fd0562",
          "md5": "fd03018e784e710be0ddaef57731e259"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.4.6.jar",
          "url": "http-1.4.6.jar",
          "size": 104410,
          "sha512": "d39101d90074b6f6e37ed16ddd7de93af141df4a38129e084d0ff7b955fa629d13dfc88c49cdc14215dc6c855c13c38e9590d314356a48edc5a8ecf0544cc16f",
          "sha256": "a35373a5b041bafbf5bc8716b6eba4d98ce978da73bdfe11348426215dbd3f54",
          "sha1": "d39202d11097a566de3f1cfa8a174e5406fd0562",
          "md5": "fd03018e784e710be0ddaef57731e259"
        }
      ]
    }
  ]
}
