{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.2.5.jar",
          "url": "api-rs-1.2.5.jar",
          "size": 122374,
          "sha512": "8084a38cd85f4bce1360379ad5043c2b33e0783225c95aa1b3e59b238cc6bfd27ba0d72f0bdc7c7c7bff965e01a83f5e0adeca3e58fdd229d81d52b50756e5b1",
          "sha256": "06a0b5c2cea49973b160c47cb9752c87ae6e3582c25fcd201e31be11f6b87e74",
          "sha1": "54adb5261b98a6cccfbf282ada49e9c2ee9db4df",
          "md5": "666bb89c7663f5ccccdb668498139510"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.5.jar",
          "url": "api-rs-1.2.5.jar",
          "size": 122374,
          "sha512": "8084a38cd85f4bce1360379ad5043c2b33e0783225c95aa1b3e59b238cc6bfd27ba0d72f0bdc7c7c7bff965e01a83f5e0adeca3e58fdd229d81d52b50756e5b1",
          "sha256": "06a0b5c2cea49973b160c47cb9752c87ae6e3582c25fcd201e31be11f6b87e74",
          "sha1": "54adb5261b98a6cccfbf282ada49e9c2ee9db4df",
          "md5": "666bb89c7663f5ccccdb668498139510"
        }
      ]
    }
  ]
}
