{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.11.jar",
          "url": "annotations-1.6.11.jar",
          "size": 8843,
          "sha512": "eb618345162a7d795347f9d9df82ed447cb9697f861190ff3cff7f6a38c1218baa928fe8c6ccbac0e3c9e4a6348bf70f56da94d62bd03acedcf26d1f213989fd",
          "sha256": "b396222e9c5f344aaa1c233cf2ddb14cf1f770e5a8b2a5df68e11a99d3f63e54",
          "sha1": "1f37ab7ad6d6e866ab1717d5235191715485a94a",
          "md5": "0064beefc51d2f555e14bdad1a7e826e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.11.jar",
          "url": "annotations-1.6.11.jar",
          "size": 8843,
          "sha512": "eb618345162a7d795347f9d9df82ed447cb9697f861190ff3cff7f6a38c1218baa928fe8c6ccbac0e3c9e4a6348bf70f56da94d62bd03acedcf26d1f213989fd",
          "sha256": "b396222e9c5f344aaa1c233cf2ddb14cf1f770e5a8b2a5df68e11a99d3f63e54",
          "sha1": "1f37ab7ad6d6e866ab1717d5235191715485a94a",
          "md5": "0064beefc51d2f555e14bdad1a7e826e"
        }
      ]
    }
  ]
}
