{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.4.5.jar",
          "url": "scripts-1.4.5.jar",
          "size": 31877,
          "sha512": "fa8f1822647e28beed245a7de563c8da2cacd02bb9e0921bd267fa4b73a8ce5dd0f3c25210f29335ae2abf9ea6568457e9040a2c471f10b53244ecdef752fb97",
          "sha256": "6553902023846fe28f5abc4e3436bcffb82da68bda99c2964d2c940f4315d4bb",
          "sha1": "f42c63691b5d2ebcbbc5e408e4cb600c505148a1",
          "md5": "dd6b7221037156eba0e8a462f912ca5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.4.5.jar",
          "url": "scripts-1.4.5.jar",
          "size": 31877,
          "sha512": "fa8f1822647e28beed245a7de563c8da2cacd02bb9e0921bd267fa4b73a8ce5dd0f3c25210f29335ae2abf9ea6568457e9040a2c471f10b53244ecdef752fb97",
          "sha256": "6553902023846fe28f5abc4e3436bcffb82da68bda99c2964d2c940f4315d4bb",
          "sha1": "f42c63691b5d2ebcbbc5e408e4cb600c505148a1",
          "md5": "dd6b7221037156eba0e8a462f912ca5d"
        }
      ]
    }
  ]
}
