{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-0.0.0.jar",
          "url": "http-0.0.0.jar",
          "size": 104410,
          "sha512": "abe6f719c4071cac11876942e28970e7538a89f74487b76da6e28682738ebbce0dfeaf0de35d64e86f5a16d0e4025f10f82ef30d3d98472916a4669fb95e336b",
          "sha256": "e91d217655b48fde4580eeec7b6b2e8ab5cc26d18b7cedee5c8216048464d366",
          "sha1": "49db3f69c5d5bf98c0125d34e9e23a1f7e181b66",
          "md5": "e321618130b7ae1cc85c1e6d47a42d23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "0.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-0.0.0.jar",
          "url": "http-0.0.0.jar",
          "size": 104410,
          "sha512": "abe6f719c4071cac11876942e28970e7538a89f74487b76da6e28682738ebbce0dfeaf0de35d64e86f5a16d0e4025f10f82ef30d3d98472916a4669fb95e336b",
          "sha256": "e91d217655b48fde4580eeec7b6b2e8ab5cc26d18b7cedee5c8216048464d366",
          "sha1": "49db3f69c5d5bf98c0125d34e9e23a1f7e181b66",
          "md5": "e321618130b7ae1cc85c1e6d47a42d23"
        }
      ]
    }
  ]
}
