{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.2.jar",
          "url": "logger-1.6.2.jar",
          "size": 8579,
          "sha512": "5649bb881a01a26d24c272ce3c61621d7c1f5e23f0cfe7f856ed8cc697c1984ef6c67b3dc36dd911ef4483f353ceaa89c5deb3a1f49cc4e9f8e22a9007e65c82",
          "sha256": "94dcd44d6b6c7fca46ee1a86108e137cf0132c703d91b88402f9e033ab107c5f",
          "sha1": "9a18a3c74fd0d17c8a488e414d40c24484071a62",
          "md5": "09b2f3930657a6f42c393808aabd425b"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.2.jar",
          "url": "logger-1.6.2.jar",
          "size": 8579,
          "sha512": "5649bb881a01a26d24c272ce3c61621d7c1f5e23f0cfe7f856ed8cc697c1984ef6c67b3dc36dd911ef4483f353ceaa89c5deb3a1f49cc4e9f8e22a9007e65c82",
          "sha256": "94dcd44d6b6c7fca46ee1a86108e137cf0132c703d91b88402f9e033ab107c5f",
          "sha1": "9a18a3c74fd0d17c8a488e414d40c24484071a62",
          "md5": "09b2f3930657a6f42c393808aabd425b"
        }
      ]
    }
  ]
}
