{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.2.jar",
          "url": "logger-1.6.2.jar",
          "size": 8579,
          "sha512": "5a3786ee6ffec5aa061931a2f0c144e1e9bde860634f89cfcf6b9bab52d91a5a1c68223cd13d7291256bbc2c590a1db43c5f3fc0f45187b8a3bb29e16e192171",
          "sha256": "79e08d1b2ceac7744211a72bbb9e6360dbfe605b3ce7f9a4c067814ee0341b5c",
          "sha1": "a426e407c6e70570a373af65b9764392c9f63507",
          "md5": "7922f0130b8d86962b11e997181bab2e"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.2.jar",
          "url": "logger-1.6.2.jar",
          "size": 8579,
          "sha512": "5a3786ee6ffec5aa061931a2f0c144e1e9bde860634f89cfcf6b9bab52d91a5a1c68223cd13d7291256bbc2c590a1db43c5f3fc0f45187b8a3bb29e16e192171",
          "sha256": "79e08d1b2ceac7744211a72bbb9e6360dbfe605b3ce7f9a4c067814ee0341b5c",
          "sha1": "a426e407c6e70570a373af65b9764392c9f63507",
          "md5": "7922f0130b8d86962b11e997181bab2e"
        }
      ]
    }
  ]
}
