{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.7.jar",
          "url": "api-1.6.7.jar",
          "size": 1338276,
          "sha512": "114cb54de9f8d137d67b63d84f5b819a42ea308bc2de13d596e1ddc774e0ac37151a1b7fd19068c513a55285ac7a029161261a7ec58cab26c57ec9605bb9bf28",
          "sha256": "adfc6b50e68c7382f53aad73b8b325be827037062cf30392f9edd52d8c96315d",
          "sha1": "ff8cbb3b7af33261354921a83189edfd16dfa548",
          "md5": "c57f248403266eb35eed706a1cf4f8f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.7.jar",
          "url": "api-1.6.7.jar",
          "size": 1338276,
          "sha512": "114cb54de9f8d137d67b63d84f5b819a42ea308bc2de13d596e1ddc774e0ac37151a1b7fd19068c513a55285ac7a029161261a7ec58cab26c57ec9605bb9bf28",
          "sha256": "adfc6b50e68c7382f53aad73b8b325be827037062cf30392f9edd52d8c96315d",
          "sha1": "ff8cbb3b7af33261354921a83189edfd16dfa548",
          "md5": "c57f248403266eb35eed706a1cf4f8f1"
        }
      ]
    }
  ]
}
