{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.0.jar",
          "url": "api-1.1.0.jar",
          "size": 1303567,
          "sha512": "7269b89ea74567556a1ac5633e173398259f22c866ce21246cfa6fbe1147a058b38fde4b49319d40ef7b51ca636c5ee0cedf70cf333c176b4be9e39a0acf9284",
          "sha256": "5fd0a4834f501105bbedb455d2525ed1903a9dff10d776d9a24147adf0d5a027",
          "sha1": "8f8a888faf6aefad2f219fbd01d219838c5d5c3d",
          "md5": "63aef0f3b3d891cf5cfb4b78cdada344"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.0.jar",
          "url": "api-1.1.0.jar",
          "size": 1303567,
          "sha512": "7269b89ea74567556a1ac5633e173398259f22c866ce21246cfa6fbe1147a058b38fde4b49319d40ef7b51ca636c5ee0cedf70cf333c176b4be9e39a0acf9284",
          "sha256": "5fd0a4834f501105bbedb455d2525ed1903a9dff10d776d9a24147adf0d5a027",
          "sha1": "8f8a888faf6aefad2f219fbd01d219838c5d5c3d",
          "md5": "63aef0f3b3d891cf5cfb4b78cdada344"
        }
      ]
    }
  ]
}
