{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.3.jar",
          "url": "api-1.1.3.jar",
          "size": 1343621,
          "sha512": "3314dbb133251361677577c0a54d0d670eca1a54d1b267c073af397fb4fde19b3262190ddc21ca2319acf738cbecb21b7698e121f096f91090a8e43b70100041",
          "sha256": "586f851ddf0d0c5de0a2cc2f35b4ca8e84e5625baebb58d59a6b79c4f3436e84",
          "sha1": "840adf348835495a51b0cf036048e0a419764a18",
          "md5": "9ca47bf09d0e9cf9f6738d3302666ce9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.3.jar",
          "url": "api-1.1.3.jar",
          "size": 1343621,
          "sha512": "3314dbb133251361677577c0a54d0d670eca1a54d1b267c073af397fb4fde19b3262190ddc21ca2319acf738cbecb21b7698e121f096f91090a8e43b70100041",
          "sha256": "586f851ddf0d0c5de0a2cc2f35b4ca8e84e5625baebb58d59a6b79c4f3436e84",
          "sha1": "840adf348835495a51b0cf036048e0a419764a18",
          "md5": "9ca47bf09d0e9cf9f6738d3302666ce9"
        }
      ]
    }
  ]
}
