{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.4.jar",
          "url": "api-1.2.4.jar",
          "size": 1339121,
          "sha512": "a7c20c8889df42b4697ede2045bf9bd06ca3e56bdadecee3c435ff897b114a4426f6f94f078de968263de1d2c644aa52c7bca59d8397916245a7d7a5ef11df10",
          "sha256": "b0e7f2d51b68cefff90af7a943b49cd9b78dd6dc90dc3126352e57e1c7424b0f",
          "sha1": "4e2024e57ae5c13fe2ed7b066f4e951600a8b4bc",
          "md5": "8d843c622e9e37d5b18c5df2c57b0675"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.4.jar",
          "url": "api-1.2.4.jar",
          "size": 1339121,
          "sha512": "a7c20c8889df42b4697ede2045bf9bd06ca3e56bdadecee3c435ff897b114a4426f6f94f078de968263de1d2c644aa52c7bca59d8397916245a7d7a5ef11df10",
          "sha256": "b0e7f2d51b68cefff90af7a943b49cd9b78dd6dc90dc3126352e57e1c7424b0f",
          "sha1": "4e2024e57ae5c13fe2ed7b066f4e951600a8b4bc",
          "md5": "8d843c622e9e37d5b18c5df2c57b0675"
        }
      ]
    }
  ]
}
