{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.1.2.jar",
          "url": "http-1.1.2.jar",
          "size": 104389,
          "sha512": "e5a88cd2057e83198bc3016839a9dc0ac2aa0aa5432340d67414304724b961fe7ab5507cfbcdcfb47028188c08647c31970ad12d225dee01cd7b1e255e7b21d2",
          "sha256": "f1bb261c1d518b385f02a9b73e2dc18ab8a024ef6d047068fa947c34f9dc0d98",
          "sha1": "d3d852cd3a4d18a9d72f23c635c4d04ff2b67e69",
          "md5": "dda92a47b74038b6ee86433f08d838a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.1.2.jar",
          "url": "http-1.1.2.jar",
          "size": 104389,
          "sha512": "e5a88cd2057e83198bc3016839a9dc0ac2aa0aa5432340d67414304724b961fe7ab5507cfbcdcfb47028188c08647c31970ad12d225dee01cd7b1e255e7b21d2",
          "sha256": "f1bb261c1d518b385f02a9b73e2dc18ab8a024ef6d047068fa947c34f9dc0d98",
          "sha1": "d3d852cd3a4d18a9d72f23c635c4d04ff2b67e69",
          "md5": "dda92a47b74038b6ee86433f08d838a1"
        }
      ]
    }
  ]
}
