{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.4.jar",
          "url": "api-1.1.4.jar",
          "size": 1341882,
          "sha512": "491baac2bbebf317d73d9a0937d729aca4c2f086c3aadac71092988d9fa135a1ac4a0ab829c0fb24d655939e193ef82caa9fdac91bc886e27b694a0aa556410d",
          "sha256": "c37d8984185c0e274e5871c154660da713e4e0f40cd96db60a14e5d01786b478",
          "sha1": "437049c2895c4c8095374ee5d3e1c958a33b1e5b",
          "md5": "8c477eb98c28af0f9affb4b792473594"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.4"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.4.jar",
          "url": "api-1.1.4.jar",
          "size": 1341882,
          "sha512": "491baac2bbebf317d73d9a0937d729aca4c2f086c3aadac71092988d9fa135a1ac4a0ab829c0fb24d655939e193ef82caa9fdac91bc886e27b694a0aa556410d",
          "sha256": "c37d8984185c0e274e5871c154660da713e4e0f40cd96db60a14e5d01786b478",
          "sha1": "437049c2895c4c8095374ee5d3e1c958a33b1e5b",
          "md5": "8c477eb98c28af0f9affb4b792473594"
        }
      ]
    }
  ]
}
