{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.0.jar",
          "url": "api-1.6.0.jar",
          "size": 1337786,
          "sha512": "0a7a24fe7c7618aa4be9b2c75bfff9f2e663587887b173fb8ecc79ce197b2b81e2cea30f7c208729739e46837a927a30f1f0c2b9a26bef7b1181dfbe4ea0956d",
          "sha256": "c8f715046c9bc3c8e444d0a92716bd8495c7b9d895eba55b1aca2d5ae7b07b68",
          "sha1": "98bd41edd71f41078c60f46c25d5f2e7cd628c4f",
          "md5": "7508770aed56f83af3d44d98d40222db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.0.jar",
          "url": "api-1.6.0.jar",
          "size": 1337786,
          "sha512": "0a7a24fe7c7618aa4be9b2c75bfff9f2e663587887b173fb8ecc79ce197b2b81e2cea30f7c208729739e46837a927a30f1f0c2b9a26bef7b1181dfbe4ea0956d",
          "sha256": "c8f715046c9bc3c8e444d0a92716bd8495c7b9d895eba55b1aca2d5ae7b07b68",
          "sha1": "98bd41edd71f41078c60f46c25d5f2e7cd628c4f",
          "md5": "7508770aed56f83af3d44d98d40222db"
        }
      ]
    }
  ]
}
