{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.5.jar",
          "url": "api-rs-1.4.5.jar",
          "size": 122412,
          "sha512": "1662c8cf67789c65979044614c50665c2505db80fcf3c6559fe6f16cd8ce6eba3354785c7faf965989726c911f4a44e48f785c60928130cd36878b07aeeda5b3",
          "sha256": "ebad1b558177e9f8d67d27b7410dc244f01e635ff36d44a9a5c312e3cc116843",
          "sha1": "ba803cfeb93a08adbae4b543586ca2ef9baad149",
          "md5": "adb8e10a87e7b0a60a7799d9b501d89a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.5.jar",
          "url": "api-rs-1.4.5.jar",
          "size": 122412,
          "sha512": "1662c8cf67789c65979044614c50665c2505db80fcf3c6559fe6f16cd8ce6eba3354785c7faf965989726c911f4a44e48f785c60928130cd36878b07aeeda5b3",
          "sha256": "ebad1b558177e9f8d67d27b7410dc244f01e635ff36d44a9a5c312e3cc116843",
          "sha1": "ba803cfeb93a08adbae4b543586ca2ef9baad149",
          "md5": "adb8e10a87e7b0a60a7799d9b501d89a"
        }
      ]
    }
  ]
}
