{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.4.0.jar",
          "url": "scripts-1.4.0.jar",
          "size": 31877,
          "sha512": "4b47c60b87401463953aaf47a7e0de2eb06121a41de448b0a6988472c2180bec00133669ea36da7f488a954c493cf836d7c0e9acc92f889a31be9c308d530a53",
          "sha256": "00843849d519bb42910abf2505e2471514049b60aebe17fbb52a273495fe259f",
          "sha1": "b1d2893378d86929997772cabb443000a8b29d86",
          "md5": "4398baa484ccf1aeceb60356c0d1b70b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.4.0.jar",
          "url": "scripts-1.4.0.jar",
          "size": 31877,
          "sha512": "4b47c60b87401463953aaf47a7e0de2eb06121a41de448b0a6988472c2180bec00133669ea36da7f488a954c493cf836d7c0e9acc92f889a31be9c308d530a53",
          "sha256": "00843849d519bb42910abf2505e2471514049b60aebe17fbb52a273495fe259f",
          "sha1": "b1d2893378d86929997772cabb443000a8b29d86",
          "md5": "4398baa484ccf1aeceb60356c0d1b70b"
        }
      ]
    }
  ]
}
