{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.15.jar",
          "url": "api-rs-1.6.15.jar",
          "size": 124096,
          "sha512": "a8184f510bff31c20ea5341ec53425903d0d6ff9f88d4fae048212466ce6ae73bf02d0e67b6e730439aa95f67384b8a9089221ede3413b1b147052b07c2f7270",
          "sha256": "64f792084fe734d2952567a9079b0921c84adc1d56235a538706969e6884d0cf",
          "sha1": "5912074afd7db163fd0b73091ca505b5436eae5a",
          "md5": "95d0170090b319bd72238810276e2cf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.15"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.15.jar",
          "url": "api-rs-1.6.15.jar",
          "size": 124096,
          "sha512": "a8184f510bff31c20ea5341ec53425903d0d6ff9f88d4fae048212466ce6ae73bf02d0e67b6e730439aa95f67384b8a9089221ede3413b1b147052b07c2f7270",
          "sha256": "64f792084fe734d2952567a9079b0921c84adc1d56235a538706969e6884d0cf",
          "sha1": "5912074afd7db163fd0b73091ca505b5436eae5a",
          "md5": "95d0170090b319bd72238810276e2cf9"
        }
      ]
    }
  ]
}
