{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.14.jar",
          "url": "annotations-1.6.14.jar",
          "size": 8843,
          "sha512": "f6d48dae01866439fc76463238986de0c0f51b1cb6ff6888a66099ccbb6d4c5d688dc4184e62809f5b2f82ad30237a1da4c4c5140cb0697c1052a7e3966ab292",
          "sha256": "7a40f9e6b30618be6f8ec6f413f8f0510b723e2e0769ba40678d1e5e7dcb80fb",
          "sha1": "e0aa1429e4347891a6f024bfdc8035eef0d8ca37",
          "md5": "645140d91fae78118be32ca6db742102"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.14.jar",
          "url": "annotations-1.6.14.jar",
          "size": 8843,
          "sha512": "f6d48dae01866439fc76463238986de0c0f51b1cb6ff6888a66099ccbb6d4c5d688dc4184e62809f5b2f82ad30237a1da4c4c5140cb0697c1052a7e3966ab292",
          "sha256": "7a40f9e6b30618be6f8ec6f413f8f0510b723e2e0769ba40678d1e5e7dcb80fb",
          "sha1": "e0aa1429e4347891a6f024bfdc8035eef0d8ca37",
          "md5": "645140d91fae78118be32ca6db742102"
        }
      ]
    }
  ]
}
