{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.14.jar",
          "url": "annotations-1.6.14.jar",
          "size": 8843,
          "sha512": "5f91d2625147ac3c34ad151f10958b7f95bebe6f6c7e24674cdbf775c0c641db9f668de82f817291b98d2060ec0950d846e7c8db7a030e83dd580f99d5a9aa07",
          "sha256": "9d1f27f0f7f9496c937ea181fc45b59f3234b8585c8b957d42d95819e5a8e2a8",
          "sha1": "8448c5ab25552050ff712545288b183dfeaa6055",
          "md5": "d63b3bac8ff0d2885bf5290f9094b4e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.14.jar",
          "url": "annotations-1.6.14.jar",
          "size": 8843,
          "sha512": "5f91d2625147ac3c34ad151f10958b7f95bebe6f6c7e24674cdbf775c0c641db9f668de82f817291b98d2060ec0950d846e7c8db7a030e83dd580f99d5a9aa07",
          "sha256": "9d1f27f0f7f9496c937ea181fc45b59f3234b8585c8b957d42d95819e5a8e2a8",
          "sha1": "8448c5ab25552050ff712545288b183dfeaa6055",
          "md5": "d63b3bac8ff0d2885bf5290f9094b4e2"
        }
      ]
    }
  ]
}
