{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.7.jar",
          "url": "api-rs-1.6.7.jar",
          "size": 123444,
          "sha512": "8a172485e8117ed1d930f12425018752b2a3a7a6696386147d054149dfd2d8de6d9671079af30c5eab95f7ca1d417f8bd2eb9cb54ac8d45062402525dd6561e4",
          "sha256": "8e384796fb86a65daa00ca7a56939c6a8095ea733538aab85f9b740b9d5ebb77",
          "sha1": "8686a5affef0852942d3809a15967e52743662e4",
          "md5": "175f85e61804a0ad6fbc689c9a5eb20b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.7.jar",
          "url": "api-rs-1.6.7.jar",
          "size": 123444,
          "sha512": "8a172485e8117ed1d930f12425018752b2a3a7a6696386147d054149dfd2d8de6d9671079af30c5eab95f7ca1d417f8bd2eb9cb54ac8d45062402525dd6561e4",
          "sha256": "8e384796fb86a65daa00ca7a56939c6a8095ea733538aab85f9b740b9d5ebb77",
          "sha1": "8686a5affef0852942d3809a15967e52743662e4",
          "md5": "175f85e61804a0ad6fbc689c9a5eb20b"
        }
      ]
    }
  ]
}
