{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.4.7.jar",
          "url": "scripts-1.4.7.jar",
          "size": 31877,
          "sha512": "603f20409b3e8d7c2fdb832078fad96bbb3afab3ec01ae8eb35d458789fd90f2c13f37612693671ffe5f2d45ec49cc3f72b6f7c6f9d2cf28d3343a8dee37de4f",
          "sha256": "e24e57cd2350ff2752f1562fb3750f54a0c23655e077385852e7a87c8cf9107e",
          "sha1": "139f1a27b6a9889635320ef0cc59c21cb7a5bb69",
          "md5": "2f567612647180b3733d0bfbb2a42f95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.4.7.jar",
          "url": "scripts-1.4.7.jar",
          "size": 31877,
          "sha512": "603f20409b3e8d7c2fdb832078fad96bbb3afab3ec01ae8eb35d458789fd90f2c13f37612693671ffe5f2d45ec49cc3f72b6f7c6f9d2cf28d3343a8dee37de4f",
          "sha256": "e24e57cd2350ff2752f1562fb3750f54a0c23655e077385852e7a87c8cf9107e",
          "sha1": "139f1a27b6a9889635320ef0cc59c21cb7a5bb69",
          "md5": "2f567612647180b3733d0bfbb2a42f95"
        }
      ]
    }
  ]
}
