{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.8.jar",
          "url": "api-rs-1.4.8.jar",
          "size": 122758,
          "sha512": "ec1df6732943296231afb58ce58b36542e8439e2a67d39b8b596fa246081b55a706b4773138c69b2094c293642d1c207dbbaabaa5ba7d43ba14a99e842c026dc",
          "sha256": "8086773020422f4153d1737cfe42ec9678356d46d1597fb74f537b0b9bbe1038",
          "sha1": "ac757a6c7c9782d9b40e64d13bc01cec033fe829",
          "md5": "cd5a200e10a6ccc6aed383271118326b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.8.jar",
          "url": "api-rs-1.4.8.jar",
          "size": 122758,
          "sha512": "ec1df6732943296231afb58ce58b36542e8439e2a67d39b8b596fa246081b55a706b4773138c69b2094c293642d1c207dbbaabaa5ba7d43ba14a99e842c026dc",
          "sha256": "8086773020422f4153d1737cfe42ec9678356d46d1597fb74f537b0b9bbe1038",
          "sha1": "ac757a6c7c9782d9b40e64d13bc01cec033fe829",
          "md5": "cd5a200e10a6ccc6aed383271118326b"
        }
      ]
    }
  ]
}
