{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.8.jar",
          "url": "api-rs-1.4.8.jar",
          "size": 122758,
          "sha512": "786f6aea64dafe27ba3fa840a3c4f35e527b1cb8d10251fd6221edf1876ed81bec809389e3abd2e2c7bb0670b28693b1999139f429cd74e18b3fa31d334c471d",
          "sha256": "d5b7b85dd7735384727ed2659b3c3fb546445f18e3bca14972abd8f2937bfe58",
          "sha1": "7b6975f3304c1ed10db54640f50ac75e0a10df29",
          "md5": "f98ca7e2ab92e45132da0c1a3ca0c847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.8.jar",
          "url": "api-rs-1.4.8.jar",
          "size": 122758,
          "sha512": "786f6aea64dafe27ba3fa840a3c4f35e527b1cb8d10251fd6221edf1876ed81bec809389e3abd2e2c7bb0670b28693b1999139f429cd74e18b3fa31d334c471d",
          "sha256": "d5b7b85dd7735384727ed2659b3c3fb546445f18e3bca14972abd8f2937bfe58",
          "sha1": "7b6975f3304c1ed10db54640f50ac75e0a10df29",
          "md5": "f98ca7e2ab92e45132da0c1a3ca0c847"
        }
      ]
    }
  ]
}
