{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.15.jar",
          "url": "logger-1.6.15.jar",
          "size": 8579,
          "sha512": "5600abc4406501480d5c40db906ecd4df9b441db12e77acb21706db7649014b70e19845a839555194ca7f4d450cd974cfb6fc617cd126e2995b0a109060c0bac",
          "sha256": "17163ac41a5ef2d9d2ce9345aca1de0aeb5b35a8055eee08f05deadd1eb9b2c7",
          "sha1": "71b133fce904b99dd0fc57fdaa2100c7f7188c0b",
          "md5": "e8f3869a9fe90542fe077bfd892d6e11"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.15.jar",
          "url": "logger-1.6.15.jar",
          "size": 8579,
          "sha512": "5600abc4406501480d5c40db906ecd4df9b441db12e77acb21706db7649014b70e19845a839555194ca7f4d450cd974cfb6fc617cd126e2995b0a109060c0bac",
          "sha256": "17163ac41a5ef2d9d2ce9345aca1de0aeb5b35a8055eee08f05deadd1eb9b2c7",
          "sha1": "71b133fce904b99dd0fc57fdaa2100c7f7188c0b",
          "md5": "e8f3869a9fe90542fe077bfd892d6e11"
        }
      ]
    }
  ]
}
