{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.14.jar",
          "url": "http-1.6.14.jar",
          "size": 104688,
          "sha512": "c2235360c3c6b62b0e44825382847dbfe778418174117b6aaf3d990f1becb6fbee1f13a0ae3eb0332d9304ad32a2e9ac15f8a7a7ad1d16eb0c706749ef54cb8a",
          "sha256": "de046e1c93b6ac5386723788d610e244eb769e86a5c2b5acda699d4f611ecc37",
          "sha1": "e029191b15ea6d380668e7cbcb31f924fd6b2285",
          "md5": "c254778afc2f4060ac1e854e9a60a649"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.14"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.14"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.14.jar",
          "url": "http-1.6.14.jar",
          "size": 104688,
          "sha512": "c2235360c3c6b62b0e44825382847dbfe778418174117b6aaf3d990f1becb6fbee1f13a0ae3eb0332d9304ad32a2e9ac15f8a7a7ad1d16eb0c706749ef54cb8a",
          "sha256": "de046e1c93b6ac5386723788d610e244eb769e86a5c2b5acda699d4f611ecc37",
          "sha1": "e029191b15ea6d380668e7cbcb31f924fd6b2285",
          "md5": "c254778afc2f4060ac1e854e9a60a649"
        }
      ]
    }
  ]
}
