{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-3.0.0.jar",
          "url": "api-rs-3.0.0.jar",
          "size": 122412,
          "sha512": "df4daba836e0a20f0f0dc1e6ea94c650fc96d80ecbd6a93b45173aa1e9f186a697361471d2aa76b9a58d3a2dd35621c004ded6de363b7b3fa2ae47b8558ddd9c",
          "sha256": "0ea97cad068187a19853c931fc923b1f5faf68f74f6eea7612f22a158866b641",
          "sha1": "b21b1ad5b2f956124196b8bb94be18bda109c963",
          "md5": "1ef45a8b3cdfbfa447faa83f34048525"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-3.0.0.jar",
          "url": "api-rs-3.0.0.jar",
          "size": 122412,
          "sha512": "df4daba836e0a20f0f0dc1e6ea94c650fc96d80ecbd6a93b45173aa1e9f186a697361471d2aa76b9a58d3a2dd35621c004ded6de363b7b3fa2ae47b8558ddd9c",
          "sha256": "0ea97cad068187a19853c931fc923b1f5faf68f74f6eea7612f22a158866b641",
          "sha1": "b21b1ad5b2f956124196b8bb94be18bda109c963",
          "md5": "1ef45a8b3cdfbfa447faa83f34048525"
        }
      ]
    }
  ]
}
