{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.0.jar",
          "url": "annotations-1.4.0.jar",
          "size": 8843,
          "sha512": "7708a0d7e6e10589f226e44b331903dad1c4e16a04c61592b0ec5c57fccba4407d177451aa34878dfd3a849f66c995bd58558901aa199753a58a5015fa554176",
          "sha256": "21c1808787beadaab2d57e0d33b825f44828ff0b555ab4425ad511956b4c21c8",
          "sha1": "3c78fe0c18bc50a9fa4e5dff17d8e4337a41b440",
          "md5": "32d93078e8beb143cb1a78c8c5f584c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.0.jar",
          "url": "annotations-1.4.0.jar",
          "size": 8843,
          "sha512": "7708a0d7e6e10589f226e44b331903dad1c4e16a04c61592b0ec5c57fccba4407d177451aa34878dfd3a849f66c995bd58558901aa199753a58a5015fa554176",
          "sha256": "21c1808787beadaab2d57e0d33b825f44828ff0b555ab4425ad511956b4c21c8",
          "sha1": "3c78fe0c18bc50a9fa4e5dff17d8e4337a41b440",
          "md5": "32d93078e8beb143cb1a78c8c5f584c2"
        }
      ]
    }
  ]
}
