{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.4.0.jar",
          "url": "annotations-1.4.0.jar",
          "size": 8843,
          "sha512": "f43d7b4002a4b29761f41cabbbaaeedaffeb0c36d2f63d6cff1fe2c41e468ab98e3a00535153ab261c1718302a23ebb6bf4818207f43b62115e6d2b9607b4398",
          "sha256": "d958dea2208ba98af21fa7f9180d3c0a43388c6bb83cb50d2d1621c39dd6c711",
          "sha1": "89207c33f9f10db6610bbebd16cef73f02722fb9",
          "md5": "2d0a3216f6e18decdc26befb40c0182a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.4.0.jar",
          "url": "annotations-1.4.0.jar",
          "size": 8843,
          "sha512": "f43d7b4002a4b29761f41cabbbaaeedaffeb0c36d2f63d6cff1fe2c41e468ab98e3a00535153ab261c1718302a23ebb6bf4818207f43b62115e6d2b9607b4398",
          "sha256": "d958dea2208ba98af21fa7f9180d3c0a43388c6bb83cb50d2d1621c39dd6c711",
          "sha1": "89207c33f9f10db6610bbebd16cef73f02722fb9",
          "md5": "2d0a3216f6e18decdc26befb40c0182a"
        }
      ]
    }
  ]
}
