{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.14.jar",
          "url": "api-1.6.14.jar",
          "size": 1367732,
          "sha512": "3fb1a7e4c368fa7a9fb0e00c34ace59807d00dd056c917b0c97ff10356c7662d4f497fbb9d6e6c0b9357a33e036c2db649e57c41f219409aa4c89403077b1799",
          "sha256": "17894e0792c8643f6f9c0a1364569ed0d1d5d1f0cfb232dc336fe5309a2db011",
          "sha1": "40e0eadc2b51c496de920da5be1b3a0ced400628",
          "md5": "8e4edba84cd80a4e3be6ac9f01eba20b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.14"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.14"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.14.jar",
          "url": "api-1.6.14.jar",
          "size": 1367732,
          "sha512": "3fb1a7e4c368fa7a9fb0e00c34ace59807d00dd056c917b0c97ff10356c7662d4f497fbb9d6e6c0b9357a33e036c2db649e57c41f219409aa4c89403077b1799",
          "sha256": "17894e0792c8643f6f9c0a1364569ed0d1d5d1f0cfb232dc336fe5309a2db011",
          "sha1": "40e0eadc2b51c496de920da5be1b3a0ced400628",
          "md5": "8e4edba84cd80a4e3be6ac9f01eba20b"
        }
      ]
    }
  ]
}
