{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.6.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.14.jar",
          "url": "logger-1.6.14.jar",
          "size": 8579,
          "sha512": "261621669a8f328694b2b7748f487323ba14521b9b96bd1c95c2bc7f566466f32dbcd356a3b53cade14cf536324d0ac9da8b0ae6c2ab73aa2e36832349206b68",
          "sha256": "4cdc9bc6db12a0a8ca944ce5b5eba4b781006a4ab1670940a53aa75f88740beb",
          "sha1": "ef5804e477f6e9ea9db8c289a3a6cc1eacc8ae53",
          "md5": "efb9ed20ff358239c169e8ff1d568590"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.6.14.jar",
          "url": "logger-1.6.14.jar",
          "size": 8579,
          "sha512": "261621669a8f328694b2b7748f487323ba14521b9b96bd1c95c2bc7f566466f32dbcd356a3b53cade14cf536324d0ac9da8b0ae6c2ab73aa2e36832349206b68",
          "sha256": "4cdc9bc6db12a0a8ca944ce5b5eba4b781006a4ab1670940a53aa75f88740beb",
          "sha1": "ef5804e477f6e9ea9db8c289a3a6cc1eacc8ae53",
          "md5": "efb9ed20ff358239c169e8ff1d568590"
        }
      ]
    }
  ]
}
