{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.12.jar",
          "url": "api-1.2.12.jar",
          "size": 1338428,
          "sha512": "35044908bd6d82ed0dc82b96db989d821008cbf6c3b8ea251c9c84731b3d9cdea6657aa337cdc1834cd2f578704476827f5e4b253257497680174bd714008895",
          "sha256": "1e64d2010cb167b879f5a82caeadbc16a12c5b9611f8e2818ff4550687df07ea",
          "sha1": "0f49df13d90f39772e2efc4ed847539a445818a2",
          "md5": "52a7dddddc488d5bf009122afbcdae2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.12"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.12.jar",
          "url": "api-1.2.12.jar",
          "size": 1338428,
          "sha512": "35044908bd6d82ed0dc82b96db989d821008cbf6c3b8ea251c9c84731b3d9cdea6657aa337cdc1834cd2f578704476827f5e4b253257497680174bd714008895",
          "sha256": "1e64d2010cb167b879f5a82caeadbc16a12c5b9611f8e2818ff4550687df07ea",
          "sha1": "0f49df13d90f39772e2efc4ed847539a445818a2",
          "md5": "52a7dddddc488d5bf009122afbcdae2b"
        }
      ]
    }
  ]
}
