{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.8.jar",
          "url": "annotations-1.6.8.jar",
          "size": 8843,
          "sha512": "9f4f87c9f9bbfc7291b94f76d139b2b2f3538079a288bffc791bc701cfc177a96799b9b8859feddb15e20d9c8b8a40b502ac7b88e21b96f30a4b81112e9047b0",
          "sha256": "e400028bb807fa45c892dece83dd57426004a0a2992550c216cb478dd0970a05",
          "sha1": "83ed2a2f8ed46860086b0aa81eced28b23283633",
          "md5": "d978ed6de0905f28a4e173103c634433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.8.jar",
          "url": "annotations-1.6.8.jar",
          "size": 8843,
          "sha512": "9f4f87c9f9bbfc7291b94f76d139b2b2f3538079a288bffc791bc701cfc177a96799b9b8859feddb15e20d9c8b8a40b502ac7b88e21b96f30a4b81112e9047b0",
          "sha256": "e400028bb807fa45c892dece83dd57426004a0a2992550c216cb478dd0970a05",
          "sha1": "83ed2a2f8ed46860086b0aa81eced28b23283633",
          "md5": "d978ed6de0905f28a4e173103c634433"
        }
      ]
    }
  ]
}
