{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-4.0.0.jar",
          "url": "api-rs-4.0.0.jar",
          "size": 122412,
          "sha512": "8588bf25ede3ee19fa614d575c9671b211a8b6aeaaecbe1653d8a441ad80a02f2196d3a35c13255fb39e70e87f469e4fcc1229889e10a3c4b9cfbbe16f4b3d03",
          "sha256": "5ddc5b617ba13853bdccc2db825aeffec77fbd70e141ef4e0abfc8ddec490d7b",
          "sha1": "03ec74e8d1f0df439a65c22fcea5febb57b1acfc",
          "md5": "8e40e39f50409e915d3c982c77f37daa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-4.0.0.jar",
          "url": "api-rs-4.0.0.jar",
          "size": 122412,
          "sha512": "8588bf25ede3ee19fa614d575c9671b211a8b6aeaaecbe1653d8a441ad80a02f2196d3a35c13255fb39e70e87f469e4fcc1229889e10a3c4b9cfbbe16f4b3d03",
          "sha256": "5ddc5b617ba13853bdccc2db825aeffec77fbd70e141ef4e0abfc8ddec490d7b",
          "sha1": "03ec74e8d1f0df439a65c22fcea5febb57b1acfc",
          "md5": "8e40e39f50409e915d3c982c77f37daa"
        }
      ]
    }
  ]
}
