{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.3.jar",
          "url": "api-1.2.3.jar",
          "size": 1339145,
          "sha512": "13439d36beeb52bf03767433333f6d50e6ae0730d50e3e62b5f5b758a24ca2c2875152852957d7411d69dd83ee2b778a28f0a639896188490821c6ebd4ca1140",
          "sha256": "357bd19152f577009786932b0f1a21b7cd57f4dc135dfed80d1f80880004bb7c",
          "sha1": "cb6f865320c3c994e2f9ccc6b10bdbf29ac6a16e",
          "md5": "a26ec740e6d25887439a8002de892cec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.3.jar",
          "url": "api-1.2.3.jar",
          "size": 1339145,
          "sha512": "13439d36beeb52bf03767433333f6d50e6ae0730d50e3e62b5f5b758a24ca2c2875152852957d7411d69dd83ee2b778a28f0a639896188490821c6ebd4ca1140",
          "sha256": "357bd19152f577009786932b0f1a21b7cd57f4dc135dfed80d1f80880004bb7c",
          "sha1": "cb6f865320c3c994e2f9ccc6b10bdbf29ac6a16e",
          "md5": "a26ec740e6d25887439a8002de892cec"
        }
      ]
    }
  ]
}
