{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.0.0.jar",
          "url": "http-1.0.0.jar",
          "size": 104390,
          "sha512": "8b351af627c8fb74f1635ce773c5e4d3a3df46effc7f60d2b43f8cd33dbf4473f49df84736759cbde58d4973ba8c010ca4a68e00d1523569897fae7e7aa37d52",
          "sha256": "441d413104bd2b9ce1f2b50bcec29735ffe855ba269dfc5ebf7300e2b4b2753c",
          "sha1": "770d0da8b6b2ed388d3c4c88cd896586e9faab95",
          "md5": "776cab2ee0434dd53abea33cffde4ff5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.0.0.jar",
          "url": "http-1.0.0.jar",
          "size": 104390,
          "sha512": "8b351af627c8fb74f1635ce773c5e4d3a3df46effc7f60d2b43f8cd33dbf4473f49df84736759cbde58d4973ba8c010ca4a68e00d1523569897fae7e7aa37d52",
          "sha256": "441d413104bd2b9ce1f2b50bcec29735ffe855ba269dfc5ebf7300e2b4b2753c",
          "sha1": "770d0da8b6b2ed388d3c4c88cd896586e9faab95",
          "md5": "776cab2ee0434dd53abea33cffde4ff5"
        }
      ]
    }
  ]
}
