{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.0.0.jar",
          "url": "http-1.0.0.jar",
          "size": 104390,
          "sha512": "f9bb1856ed8ea22b135e3215b1ddc53e64f3e6be7f7f9138a12abb397099a783487f9c8ae553eed35802e06b11a4207f3884ef67b662c25e24dc41bccde64c34",
          "sha256": "c15a0f48a49e1271de18fedf6fa26eeb9822c7ef4f3d09706e6a9a50b7a5a78f",
          "sha1": "2e0db1ed47a980fc19089c0ef07eb21245676eed",
          "md5": "473f346c0135cb0969737d9a2158fc82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.0.0.jar",
          "url": "http-1.0.0.jar",
          "size": 104390,
          "sha512": "f9bb1856ed8ea22b135e3215b1ddc53e64f3e6be7f7f9138a12abb397099a783487f9c8ae553eed35802e06b11a4207f3884ef67b662c25e24dc41bccde64c34",
          "sha256": "c15a0f48a49e1271de18fedf6fa26eeb9822c7ef4f3d09706e6a9a50b7a5a78f",
          "sha1": "2e0db1ed47a980fc19089c0ef07eb21245676eed",
          "md5": "473f346c0135cb0969737d9a2158fc82"
        }
      ]
    }
  ]
}
