{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.5.jar",
          "url": "api-1.6.5.jar",
          "size": 1338996,
          "sha512": "cda1651de5b56ca2797cf090a58c6b1dd73945b76c1551b4b64235d3073490b330ce64ee083b025a9dd020624a160faa0178debfd5162e0dca7e06aefb13955f",
          "sha256": "004c9de2589ec4d6cb5b8b26ceac6b2f1633c21bc7fbc9828bd9395702bee45b",
          "sha1": "d651252c6e23096b9892ab60ef68460e6e752c5a",
          "md5": "de8a9da01caf9d0414f6658b0dde5b0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.5.jar",
          "url": "api-1.6.5.jar",
          "size": 1338996,
          "sha512": "cda1651de5b56ca2797cf090a58c6b1dd73945b76c1551b4b64235d3073490b330ce64ee083b025a9dd020624a160faa0178debfd5162e0dca7e06aefb13955f",
          "sha256": "004c9de2589ec4d6cb5b8b26ceac6b2f1633c21bc7fbc9828bd9395702bee45b",
          "sha1": "d651252c6e23096b9892ab60ef68460e6e752c5a",
          "md5": "de8a9da01caf9d0414f6658b0dde5b0b"
        }
      ]
    }
  ]
}
