{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.5.jar",
          "url": "api-1.0.5.jar",
          "size": 1399954,
          "sha512": "667bcbf627038aa8a32b2034625b12ea5bac354f74ed251d03d3dd653b76f3730a12174d9150208b097d27548908be0dbc7fdf73193672986f9c7a7150bf097b",
          "sha256": "e21fabe5730b33e41bbd54f67ece8ffde69e40855b0f26dbcc25f52ea324685e",
          "sha1": "024f35f842c7db54cae1e3946e36c093757e0157",
          "md5": "ed7909f8699bb9e1f6b00ce8babe8928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.5.jar",
          "url": "api-1.0.5.jar",
          "size": 1399954,
          "sha512": "667bcbf627038aa8a32b2034625b12ea5bac354f74ed251d03d3dd653b76f3730a12174d9150208b097d27548908be0dbc7fdf73193672986f9c7a7150bf097b",
          "sha256": "e21fabe5730b33e41bbd54f67ece8ffde69e40855b0f26dbcc25f52ea324685e",
          "sha1": "024f35f842c7db54cae1e3946e36c093757e0157",
          "md5": "ed7909f8699bb9e1f6b00ce8babe8928"
        }
      ]
    }
  ]
}
