{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.2.1.jar",
          "url": "api-rs-1.2.1.jar",
          "size": 122013,
          "sha512": "c0a3b2c1cea632899069b0f2b43862a54ae959eebc388a1128646e5263ed368203395159979b7882a377e7709053146d5d6fd73c1bf956370c0c8472ae739846",
          "sha256": "1bba734c50f8d86d4b71e236518d0d96bb384363ba27e102ae6ec974054e1e0c",
          "sha1": "d4d2759e997cce55fe69a1a65a2b3311ccceff64",
          "md5": "45c2cd0aa2e7124d1fb7a7e7ab23bf51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.1.jar",
          "url": "api-rs-1.2.1.jar",
          "size": 122013,
          "sha512": "c0a3b2c1cea632899069b0f2b43862a54ae959eebc388a1128646e5263ed368203395159979b7882a377e7709053146d5d6fd73c1bf956370c0c8472ae739846",
          "sha256": "1bba734c50f8d86d4b71e236518d0d96bb384363ba27e102ae6ec974054e1e0c",
          "sha1": "d4d2759e997cce55fe69a1a65a2b3311ccceff64",
          "md5": "45c2cd0aa2e7124d1fb7a7e7ab23bf51"
        }
      ]
    }
  ]
}
