{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-3.0.0.jar",
          "url": "scripts-3.0.0.jar",
          "size": 31877,
          "sha512": "0e31c9626a69cac459a6325ee764c8391ffc425dc9c7a050a8258ab5e93534f493b45a706cd1b211b09111620ff7372b05ff23c66195ad918768af1431579c90",
          "sha256": "368d9842f14d4cd19a39968e89c0a75ebb2e78750c5c4f5808eefca3c30ed0f0",
          "sha1": "9287e9eed2a26cb27dc22c98bf2103cef79cb917",
          "md5": "394d6ad5b297c0658ea627d5c9a5b648"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-3.0.0.jar",
          "url": "scripts-3.0.0.jar",
          "size": 31877,
          "sha512": "0e31c9626a69cac459a6325ee764c8391ffc425dc9c7a050a8258ab5e93534f493b45a706cd1b211b09111620ff7372b05ff23c66195ad918768af1431579c90",
          "sha256": "368d9842f14d4cd19a39968e89c0a75ebb2e78750c5c4f5808eefca3c30ed0f0",
          "sha1": "9287e9eed2a26cb27dc22c98bf2103cef79cb917",
          "md5": "394d6ad5b297c0658ea627d5c9a5b648"
        }
      ]
    }
  ]
}
