{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.4.3.jar",
          "url": "scripts-1.4.3.jar",
          "size": 31877,
          "sha512": "23022b7802f2d0d6a2067160a2f909495dd8940febc3218ee9a028dcea235a9e8c43baec267629c6a709dacd3c0e4d66784ff446d33b49bd8129243197438fc6",
          "sha256": "75462193104dd497a8806b431b443c33410a9d5324646dd1b30e94031420d967",
          "sha1": "caa824b8652f19a2b8a511cc11c3af879f4caa74",
          "md5": "b43b334bdb19c026d298ffe535b3f5a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.4.3.jar",
          "url": "scripts-1.4.3.jar",
          "size": 31877,
          "sha512": "23022b7802f2d0d6a2067160a2f909495dd8940febc3218ee9a028dcea235a9e8c43baec267629c6a709dacd3c0e4d66784ff446d33b49bd8129243197438fc6",
          "sha256": "75462193104dd497a8806b431b443c33410a9d5324646dd1b30e94031420d967",
          "sha1": "caa824b8652f19a2b8a511cc11c3af879f4caa74",
          "md5": "b43b334bdb19c026d298ffe535b3f5a6"
        }
      ]
    }
  ]
}
