{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.2.2.jar",
          "url": "annotations-1.2.2.jar",
          "size": 8843,
          "sha512": "2d974382589fb3ceb81d9a03ac8899703a2b8483372a0203796ba0c84969cea838fb8c394e4cf94803c57c4081104f7f363e3b6544f6a18481dc96a09a5515f8",
          "sha256": "51fc6656a4ada6844e838f5a63df0ba7e2b766adc2e281d797a40888fa1dbfd8",
          "sha1": "1ad38ac92405240293ecbd5392dcee573dbb7376",
          "md5": "f8092cde2caa7314f44b984eed2bb212"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.2.2.jar",
          "url": "annotations-1.2.2.jar",
          "size": 8843,
          "sha512": "2d974382589fb3ceb81d9a03ac8899703a2b8483372a0203796ba0c84969cea838fb8c394e4cf94803c57c4081104f7f363e3b6544f6a18481dc96a09a5515f8",
          "sha256": "51fc6656a4ada6844e838f5a63df0ba7e2b766adc2e281d797a40888fa1dbfd8",
          "sha1": "1ad38ac92405240293ecbd5392dcee573dbb7376",
          "md5": "f8092cde2caa7314f44b984eed2bb212"
        }
      ]
    }
  ]
}
