{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-4.0.0.jar",
          "url": "scripts-4.0.0.jar",
          "size": 31877,
          "sha512": "d634ba163d5a27b623ef59623f1837fa652c5f1aeb4f91a4338fc4ae9623696334c532f243bee169e96a64d9ce69a975d6157d6b6f567f0ce25bec5cbab68529",
          "sha256": "f0a8375bce98937e4c8f66683829e983d921eea84dd3f1e59c21592681699728",
          "sha1": "4c0d5392f1473b46fd1f3f99578e918c755a003c",
          "md5": "fb8fa6e410bd1930668b1bdcd3ab807a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-4.0.0.jar",
          "url": "scripts-4.0.0.jar",
          "size": 31877,
          "sha512": "d634ba163d5a27b623ef59623f1837fa652c5f1aeb4f91a4338fc4ae9623696334c532f243bee169e96a64d9ce69a975d6157d6b6f567f0ce25bec5cbab68529",
          "sha256": "f0a8375bce98937e4c8f66683829e983d921eea84dd3f1e59c21592681699728",
          "sha1": "4c0d5392f1473b46fd1f3f99578e918c755a003c",
          "md5": "fb8fa6e410bd1930668b1bdcd3ab807a"
        }
      ]
    }
  ]
}
