{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.9.jar",
          "url": "http-1.6.9.jar",
          "size": 104688,
          "sha512": "2a384b187b2e13cfe9a365adf229a296439ceb0588e66da64972f90b6f024e931567d314779e20b29d593765dfcbc71fd63c771b1990384915dd581787fb9381",
          "sha256": "3061842aa97a3a278472f41d96eb551a5064b3c1e48302759d1c851fd9d95a41",
          "sha1": "a580dc262203a21e56d84510d15bfd0fa14708b5",
          "md5": "394003bfba94aac566f638987488540b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.9.jar",
          "url": "http-1.6.9.jar",
          "size": 104688,
          "sha512": "2a384b187b2e13cfe9a365adf229a296439ceb0588e66da64972f90b6f024e931567d314779e20b29d593765dfcbc71fd63c771b1990384915dd581787fb9381",
          "sha256": "3061842aa97a3a278472f41d96eb551a5064b3c1e48302759d1c851fd9d95a41",
          "sha1": "a580dc262203a21e56d84510d15bfd0fa14708b5",
          "md5": "394003bfba94aac566f638987488540b"
        }
      ]
    }
  ]
}
