{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.11.jar",
          "url": "api-1.6.11.jar",
          "size": 1341833,
          "sha512": "78933e3e9249a5531cfc9b69d58a8657b52d995627c294f3e68e9c13edaaee2726ba16a955ba1aa6c9ad4238c667389111577ef8de055567e984f0c180051764",
          "sha256": "673832b3b57855800aef1171d242ed1c5f79edf28a81d167a06b289ed33bebff",
          "sha1": "f355c96979376e804c6b3b7e537627494bd34ca2",
          "md5": "14f03a8f76311f5631bfa209a4691a80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.11"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.11.jar",
          "url": "api-1.6.11.jar",
          "size": 1341833,
          "sha512": "78933e3e9249a5531cfc9b69d58a8657b52d995627c294f3e68e9c13edaaee2726ba16a955ba1aa6c9ad4238c667389111577ef8de055567e984f0c180051764",
          "sha256": "673832b3b57855800aef1171d242ed1c5f79edf28a81d167a06b289ed33bebff",
          "sha1": "f355c96979376e804c6b3b7e537627494bd34ca2",
          "md5": "14f03a8f76311f5631bfa209a4691a80"
        }
      ]
    }
  ]
}
