{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.5.1.jar",
          "url": "annotations-1.5.1.jar",
          "size": 8843,
          "sha512": "33036ac93b4ac47d7ac2096dc14c4a796e15df6ca554d48094933e3a26306bb3bd37d524b8e88e46792c9333c969d3d339318744f3f1857cdade0d50d0da1233",
          "sha256": "4295f19932ff39856cd04b5efeed0407088d0f56bec67377742440870fecfe1d",
          "sha1": "1f3856dc69b3e66cbda40cc0c458bcb0ae13887d",
          "md5": "eb1cdd3ff45ee72a5c3d94b02582d453"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.5.1.jar",
          "url": "annotations-1.5.1.jar",
          "size": 8843,
          "sha512": "33036ac93b4ac47d7ac2096dc14c4a796e15df6ca554d48094933e3a26306bb3bd37d524b8e88e46792c9333c969d3d339318744f3f1857cdade0d50d0da1233",
          "sha256": "4295f19932ff39856cd04b5efeed0407088d0f56bec67377742440870fecfe1d",
          "sha1": "1f3856dc69b3e66cbda40cc0c458bcb0ae13887d",
          "md5": "eb1cdd3ff45ee72a5c3d94b02582d453"
        }
      ]
    }
  ]
}
