{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-2.0.0.jar",
          "url": "annotations-2.0.0.jar",
          "size": 8843,
          "sha512": "0f9132c523388ce9e375ced1da29070d08b5fc6f66db70a208ccf4ae2f8504e0590e5ff538888e170ff9e06aac34ef2f2dd0cd97a1f4a36bead85efbcb701eda",
          "sha256": "8311da3fff7ea9067b0a0b3b7cfa436e94c0b6b67ce58a4f18698c875e77183d",
          "sha1": "87fd911d057780f121d7eabe1699335d5e342e25",
          "md5": "763410b1269c862069489b37b2aeb2d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-2.0.0.jar",
          "url": "annotations-2.0.0.jar",
          "size": 8843,
          "sha512": "0f9132c523388ce9e375ced1da29070d08b5fc6f66db70a208ccf4ae2f8504e0590e5ff538888e170ff9e06aac34ef2f2dd0cd97a1f4a36bead85efbcb701eda",
          "sha256": "8311da3fff7ea9067b0a0b3b7cfa436e94c0b6b67ce58a4f18698c875e77183d",
          "sha1": "87fd911d057780f121d7eabe1699335d5e342e25",
          "md5": "763410b1269c862069489b37b2aeb2d6"
        }
      ]
    }
  ]
}
