{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.7.jar",
          "url": "http-1.6.7.jar",
          "size": 104648,
          "sha512": "6e9d791b2ba117e9941b02d6a60bcf75b0a3eefbcd465cbcf6040e9a5ab1a0c52c14dacedea8a980aebd59f9c03315b683de11be73cfd17518a6f2a54a7eac66",
          "sha256": "6b4d86792b6e2062e33b365115dd2c7a8d5e923215cc9a423228e00398b1360a",
          "sha1": "0c3e67b96e57381dc33db1a7340827af330fca34",
          "md5": "cc62a3b665f77e6aad31680936d54b14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.7.jar",
          "url": "http-1.6.7.jar",
          "size": 104648,
          "sha512": "6e9d791b2ba117e9941b02d6a60bcf75b0a3eefbcd465cbcf6040e9a5ab1a0c52c14dacedea8a980aebd59f9c03315b683de11be73cfd17518a6f2a54a7eac66",
          "sha256": "6b4d86792b6e2062e33b365115dd2c7a8d5e923215cc9a423228e00398b1360a",
          "sha1": "0c3e67b96e57381dc33db1a7340827af330fca34",
          "md5": "cc62a3b665f77e6aad31680936d54b14"
        }
      ]
    }
  ]
}
