{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-4.0.0.jar",
          "url": "annotations-4.0.0.jar",
          "size": 8843,
          "sha512": "495a592eda17b7737de1e2cd10e1ca7e81431e67d0b271d9fb28ba5ce044336fe41d115a4a20736193e33d8eac297ae3160f004db2153cf320031a4a4cdbd952",
          "sha256": "c888295a98a9de9fcd1f9108851ac7b79d64fe0dbdb6f2f8d6334608f183f7e7",
          "sha1": "fd5d4ee868aacb88a3a8eb1b1eabbc129ce505f3",
          "md5": "a311eb72cf08f2fa3017d63c14962d1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-4.0.0.jar",
          "url": "annotations-4.0.0.jar",
          "size": 8843,
          "sha512": "495a592eda17b7737de1e2cd10e1ca7e81431e67d0b271d9fb28ba5ce044336fe41d115a4a20736193e33d8eac297ae3160f004db2153cf320031a4a4cdbd952",
          "sha256": "c888295a98a9de9fcd1f9108851ac7b79d64fe0dbdb6f2f8d6334608f183f7e7",
          "sha1": "fd5d4ee868aacb88a3a8eb1b1eabbc129ce505f3",
          "md5": "a311eb72cf08f2fa3017d63c14962d1e"
        }
      ]
    }
  ]
}
