{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.7.jar",
          "url": "api-rs-1.4.7.jar",
          "size": 122718,
          "sha512": "ca115e103c9b9a8ed21ba3dbca63103b4a3cc12f2150c707a1762fdc3cbad0ed9fbdd3b0c164ebb796ab8bad45d795067881dc9c22b80f8cb20db8a330ddb982",
          "sha256": "38a16bf281781287533f0761aed606a063b47b48d3294abfaba2628c1977242f",
          "sha1": "f1c01405cdac2cb360c0ad4425d384f209351516",
          "md5": "aade988db30074bce2d7e484fbe971ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.7.jar",
          "url": "api-rs-1.4.7.jar",
          "size": 122718,
          "sha512": "ca115e103c9b9a8ed21ba3dbca63103b4a3cc12f2150c707a1762fdc3cbad0ed9fbdd3b0c164ebb796ab8bad45d795067881dc9c22b80f8cb20db8a330ddb982",
          "sha256": "38a16bf281781287533f0761aed606a063b47b48d3294abfaba2628c1977242f",
          "sha1": "f1c01405cdac2cb360c0ad4425d384f209351516",
          "md5": "aade988db30074bce2d7e484fbe971ff"
        }
      ]
    }
  ]
}
