{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.2.4.jar",
          "url": "annotations-1.2.4.jar",
          "size": 8843,
          "sha512": "50566dc38104e6c6877d4c55b90ec7c683bb861f46608d403da9da98bdde1b53315c204066f7f603a9b34af0012b360b6f8ac5957c54e6ac83e7a80afee660be",
          "sha256": "fe2f5f384ae0c1dd70bf53c60f93e5bbc10511b80b574bcab036de0550bb8b49",
          "sha1": "888ec2aba94c00079a604749717c756628a5f7ea",
          "md5": "e9498bb4cabe4dd13aa1cf24ad6b07c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.2.4.jar",
          "url": "annotations-1.2.4.jar",
          "size": 8843,
          "sha512": "50566dc38104e6c6877d4c55b90ec7c683bb861f46608d403da9da98bdde1b53315c204066f7f603a9b34af0012b360b6f8ac5957c54e6ac83e7a80afee660be",
          "sha256": "fe2f5f384ae0c1dd70bf53c60f93e5bbc10511b80b574bcab036de0550bb8b49",
          "sha1": "888ec2aba94c00079a604749717c756628a5f7ea",
          "md5": "e9498bb4cabe4dd13aa1cf24ad6b07c7"
        }
      ]
    }
  ]
}
