{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.2.4.jar",
          "url": "http-1.2.4.jar",
          "size": 104409,
          "sha512": "a0aec90825ec7607f9a0f6ad6760571d3fb5cad056caf25db6d8c945473c1c14dc480a0543089bb1acb924e9ad498265d6849b6e8d2a426b141f0d31fdfb2714",
          "sha256": "f397561d48736f5c58de813d45995e31672e74da51668aefbac1932ced00c902",
          "sha1": "7edc19617d55b63db873d3da7827ccbcc0087f89",
          "md5": "f7ef2f3be7a6a4c138ddd76edbf0d4e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.2.4.jar",
          "url": "http-1.2.4.jar",
          "size": 104409,
          "sha512": "a0aec90825ec7607f9a0f6ad6760571d3fb5cad056caf25db6d8c945473c1c14dc480a0543089bb1acb924e9ad498265d6849b6e8d2a426b141f0d31fdfb2714",
          "sha256": "f397561d48736f5c58de813d45995e31672e74da51668aefbac1932ced00c902",
          "sha1": "7edc19617d55b63db873d3da7827ccbcc0087f89",
          "md5": "f7ef2f3be7a6a4c138ddd76edbf0d4e0"
        }
      ]
    }
  ]
}
