{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "api-rs-1.1.6.jar",
          "url": "api-rs-1.1.6.jar",
          "size": 122013,
          "sha512": "f4d1d741bf7dc242dab01cf87649c7f7b5d4e1a1a8af51ed38dfdecaf746929108b08a51dac29ca2552b78e21d49f4fb606bd182c0e470afe88445929cd4a7b3",
          "sha256": "3402845c45edd6ec1b0b3e10b23c06235c222f16fc5386c0fbcdcffbbd40dc59",
          "sha1": "a9490320b30dbc4b4033f91f021b57c835596006",
          "md5": "5913f497b60138e8f7ca987701efcae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-rs-1.1.6.jar",
          "url": "api-rs-1.1.6.jar",
          "size": 122013,
          "sha512": "f4d1d741bf7dc242dab01cf87649c7f7b5d4e1a1a8af51ed38dfdecaf746929108b08a51dac29ca2552b78e21d49f4fb606bd182c0e470afe88445929cd4a7b3",
          "sha256": "3402845c45edd6ec1b0b3e10b23c06235c222f16fc5386c0fbcdcffbbd40dc59",
          "sha1": "a9490320b30dbc4b4033f91f021b57c835596006",
          "md5": "5913f497b60138e8f7ca987701efcae6"
        }
      ]
    }
  ]
}
