{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.5.jar",
          "url": "annotations-1.6.5.jar",
          "size": 8843,
          "sha512": "a864fd4b9d1b94978bea4704015638a53a3a73c979724a766a636b4367c46dfcc675edcaf7f2f2302058203a0b8ba248f4c415d1d2374e1b46566e3fb4bae3a6",
          "sha256": "ca8bd5e5e3a6b284f1bfd7661e1c93a136283feb5836ee2ed4ec86d034fdd9d8",
          "sha1": "66be85c49fda1ad783b827801ab45fd3149fa615",
          "md5": "8f36209d128a16441ce6af12e82d7570"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.5.jar",
          "url": "annotations-1.6.5.jar",
          "size": 8843,
          "sha512": "a864fd4b9d1b94978bea4704015638a53a3a73c979724a766a636b4367c46dfcc675edcaf7f2f2302058203a0b8ba248f4c415d1d2374e1b46566e3fb4bae3a6",
          "sha256": "ca8bd5e5e3a6b284f1bfd7661e1c93a136283feb5836ee2ed4ec86d034fdd9d8",
          "sha1": "66be85c49fda1ad783b827801ab45fd3149fa615",
          "md5": "8f36209d128a16441ce6af12e82d7570"
        }
      ]
    }
  ]
}
