{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.2.4.jar",
          "url": "api-rs-1.2.4.jar",
          "size": 122366,
          "sha512": "823750ddc9df5f45e81bd6f6fd2361e3aa12a89bd45395d50204259ada6eee15a3b917c095419c69c048ac7e31d364fcc96aedea54fac2f3918b4259acfe719f",
          "sha256": "b361636f39b88267740f645ee062ccc1096e276dbfc03be653a0b5d9c10f6db7",
          "sha1": "000c1f56a24ac463a2efb93180cf5cdc4c55693d",
          "md5": "6a50860cb3ecbbfb55c8d3e78560849d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.2.4.jar",
          "url": "api-rs-1.2.4.jar",
          "size": 122366,
          "sha512": "823750ddc9df5f45e81bd6f6fd2361e3aa12a89bd45395d50204259ada6eee15a3b917c095419c69c048ac7e31d364fcc96aedea54fac2f3918b4259acfe719f",
          "sha256": "b361636f39b88267740f645ee062ccc1096e276dbfc03be653a0b5d9c10f6db7",
          "sha1": "000c1f56a24ac463a2efb93180cf5cdc4c55693d",
          "md5": "6a50860cb3ecbbfb55c8d3e78560849d"
        }
      ]
    }
  ]
}
