{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.0.jar",
          "url": "api-rs-1.4.0.jar",
          "size": 122412,
          "sha512": "dd35505ee252e9ce4bf0423b84b72e0648040008bdc6f5d44560faa11061d3cda6de6b5776f18e306301cb635fe538405d0d371d4bc8b66c94c0fd1a94b85b87",
          "sha256": "a43ff0d55625a7e8e3800dfd2d16a37ec83188df1b0fa4a60ffa4d57bd793f26",
          "sha1": "3f43633c300adbe5608b074148822557c1ee9745",
          "md5": "34fa130f612877c12d30935621a97c56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.0.jar",
          "url": "api-rs-1.4.0.jar",
          "size": 122412,
          "sha512": "dd35505ee252e9ce4bf0423b84b72e0648040008bdc6f5d44560faa11061d3cda6de6b5776f18e306301cb635fe538405d0d371d4bc8b66c94c0fd1a94b85b87",
          "sha256": "a43ff0d55625a7e8e3800dfd2d16a37ec83188df1b0fa4a60ffa4d57bd793f26",
          "sha1": "3f43633c300adbe5608b074148822557c1ee9745",
          "md5": "34fa130f612877c12d30935621a97c56"
        }
      ]
    }
  ]
}
