{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.12.jar",
          "url": "api-1.6.12.jar",
          "size": 1341880,
          "sha512": "33fdf2a608899f795defc6f2e652c7f308d276e674f9e74fb7ce352a240740c56188a23152598dc4bb30b504f59e93e7f7bbea8d1c8ee510e0e571adcc01465d",
          "sha256": "6b6200d37ef9561e07892ac2d6ad07f70b15b6cb66f7610acfb218abf7189ede",
          "sha1": "f51e7325ca89ec24ea4d72d322c0026a8d77942e",
          "md5": "64876498627a759c4530d166ed092dd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.12"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.12.jar",
          "url": "api-1.6.12.jar",
          "size": 1341880,
          "sha512": "33fdf2a608899f795defc6f2e652c7f308d276e674f9e74fb7ce352a240740c56188a23152598dc4bb30b504f59e93e7f7bbea8d1c8ee510e0e571adcc01465d",
          "sha256": "6b6200d37ef9561e07892ac2d6ad07f70b15b6cb66f7610acfb218abf7189ede",
          "sha1": "f51e7325ca89ec24ea4d72d322c0026a8d77942e",
          "md5": "64876498627a759c4530d166ed092dd0"
        }
      ]
    }
  ]
}
