{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.2.3.jar",
          "url": "annotations-1.2.3.jar",
          "size": 8843,
          "sha512": "404874289bfef8d91d27eeeadbe7fb56a8d1f9d3bcaba2b7862e5ffa7558605001225f0e10689e731f6d7e3937798478ebc23d604ff614515205e75937bc6ba5",
          "sha256": "ce39f4f2ddd1ebaee566236a35d387dbe0899935bff651651735a7c5497f8088",
          "sha1": "077bb423ffc108f6bad3042c399a4b4fd84c0b6d",
          "md5": "cbb7c02a8f0349ddcc0fc587d8bcb4e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.2.3.jar",
          "url": "annotations-1.2.3.jar",
          "size": 8843,
          "sha512": "404874289bfef8d91d27eeeadbe7fb56a8d1f9d3bcaba2b7862e5ffa7558605001225f0e10689e731f6d7e3937798478ebc23d604ff614515205e75937bc6ba5",
          "sha256": "ce39f4f2ddd1ebaee566236a35d387dbe0899935bff651651735a7c5497f8088",
          "sha1": "077bb423ffc108f6bad3042c399a4b4fd84c0b6d",
          "md5": "cbb7c02a8f0349ddcc0fc587d8bcb4e9"
        }
      ]
    }
  ]
}
