{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "client",
    "version": "1.5.2-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "client-1.5.2-1.jar",
          "url": "client-1.5.2-1.jar",
          "size": 8374797,
          "sha512": "ea55ef1e57d1aa3215a83b90578275472f30656f48cfaf7461a3d847dc25dcf5be38e026bbc76b04fec6d729aa8bc437ebf588a0d203623ca9eaa302666d6408",
          "sha256": "53dd99d975c22720dfe44628baf361f9cdd881deaf66a0d0db8db363ce400e10",
          "sha1": "f456d4f90ca2c1cb1ae978af108efa343c60d310",
          "md5": "33755c78929f1be9b7ede409ed6d64b6"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api-rs",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "http",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-gldesktop-dbg",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.20"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.rationalityfrontline",
          "module": "kevent",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.7",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf-intellij-themes",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.miglayout",
          "module": "miglayout",
          "version": {
            "requires": "3.7.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "com.kitfox.svg",
          "module": "svg-salamander",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.formdev",
          "module": "flatlaf-extras",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.godaddy.android.colorpicker",
          "module": "compose-color-picker-jvm",
          "version": {
            "requires": "0.4.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.compose.desktop",
          "module": "desktop-jvm-windows-x64",
          "version": {
            "requires": "1.2.0-alpha01-dev686"
          }
        },
        {
          "group": "meteor",
          "module": "injected",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "meteor",
          "module": "scripts",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.70"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macosx-universal"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macosx-universal"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-x64"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-arm64"
            }
          }
        }
      ],
      "files": [
        {
          "name": "client-1.5.2-1.jar",
          "url": "client-1.5.2-1.jar",
          "size": 8374797,
          "sha512": "ea55ef1e57d1aa3215a83b90578275472f30656f48cfaf7461a3d847dc25dcf5be38e026bbc76b04fec6d729aa8bc437ebf588a0d203623ca9eaa302666d6408",
          "sha256": "53dd99d975c22720dfe44628baf361f9cdd881deaf66a0d0db8db363ce400e10",
          "sha1": "f456d4f90ca2c1cb1ae978af108efa343c60d310",
          "md5": "33755c78929f1be9b7ede409ed6d64b6"
        }
      ]
    }
  ]
}
