{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.15.jar",
          "url": "annotations-1.6.15.jar",
          "size": 8843,
          "sha512": "9abf6b2f6635606569eea43f08d69503c12ebb469866e20b234c9a616b76f5e1008d233f317a2e3cef30d96c08e06368b5d92556659ec649c9efdbda42159ed8",
          "sha256": "d74ed6abfa2ee3980fe2510f445d1edf4b5076e1458ee9d7c6b1d8ff50d55313",
          "sha1": "8383e0a97169c7436f74634925ccc7051bfb61b6",
          "md5": "8a5291142172521585af74acaf8c1cd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.15.jar",
          "url": "annotations-1.6.15.jar",
          "size": 8843,
          "sha512": "9abf6b2f6635606569eea43f08d69503c12ebb469866e20b234c9a616b76f5e1008d233f317a2e3cef30d96c08e06368b5d92556659ec649c9efdbda42159ed8",
          "sha256": "d74ed6abfa2ee3980fe2510f445d1edf4b5076e1458ee9d7c6b1d8ff50d55313",
          "sha1": "8383e0a97169c7436f74634925ccc7051bfb61b6",
          "md5": "8a5291142172521585af74acaf8c1cd5"
        }
      ]
    }
  ]
}
