{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-4.0.0.jar",
          "url": "api-4.0.0.jar",
          "size": 1337402,
          "sha512": "d89b00f45b490cb53e92cd33d17c20fcd17d7b324fec7cf114cd4d52e51bd03315e361792e884dd99a740d616303dc1e872b4a41bb1437ce588d6c308ccf4470",
          "sha256": "62a022018fc833b379132daef8eb0a4f8bc9916d0971f3d67fdcfbb4fabf2bd4",
          "sha1": "3de43bd15016cef51f66894516c0708ec3921a71",
          "md5": "00020ae72965e0b46d68887f6119ba10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-4.0.0.jar",
          "url": "api-4.0.0.jar",
          "size": 1337402,
          "sha512": "d89b00f45b490cb53e92cd33d17c20fcd17d7b324fec7cf114cd4d52e51bd03315e361792e884dd99a740d616303dc1e872b4a41bb1437ce588d6c308ccf4470",
          "sha256": "62a022018fc833b379132daef8eb0a4f8bc9916d0971f3d67fdcfbb4fabf2bd4",
          "sha1": "3de43bd15016cef51f66894516c0708ec3921a71",
          "md5": "00020ae72965e0b46d68887f6119ba10"
        }
      ]
    }
  ]
}
