{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.13.jar",
          "url": "annotations-1.6.13.jar",
          "size": 8843,
          "sha512": "5d464450e3fa76bed3c95510a11b5783ec67f4ab9749eb70b86cced26d9ff5e27780a6969930edefc6afb9ff5ea2d4e1a84f1c3447e71069f465f95018e3cfe1",
          "sha256": "358b50d47d51a8619d263722459c3d6747b90f31d07ec5cacc9cdbe64b01c571",
          "sha1": "d941c157d1c7526bc2cc6ce9fde29b66c8f46b90",
          "md5": "0469d4102a93106c8922cc020da7e71e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.13.jar",
          "url": "annotations-1.6.13.jar",
          "size": 8843,
          "sha512": "5d464450e3fa76bed3c95510a11b5783ec67f4ab9749eb70b86cced26d9ff5e27780a6969930edefc6afb9ff5ea2d4e1a84f1c3447e71069f465f95018e3cfe1",
          "sha256": "358b50d47d51a8619d263722459c3d6747b90f31d07ec5cacc9cdbe64b01c571",
          "sha1": "d941c157d1c7526bc2cc6ce9fde29b66c8f46b90",
          "md5": "0469d4102a93106c8922cc020da7e71e"
        }
      ]
    }
  ]
}
