{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-0.0.0.jar",
          "url": "annotations-0.0.0.jar",
          "size": 8843,
          "sha512": "54080fd4610072d4fea2e865ddd0e644136bacb3a2693c55db467179416aee123e5c95a80e0b24d33c23459e601cb02000df3f9df79c342e45d264ac8468fb3c",
          "sha256": "d3e4509684d52cdba5bcc16976caa8f748d30e285716ee068931d35e1efd6ab0",
          "sha1": "cab17da1e632695b7889e86d857536c415f6a023",
          "md5": "51a0232dded2ae5742b9357a40e21333"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-0.0.0.jar",
          "url": "annotations-0.0.0.jar",
          "size": 8843,
          "sha512": "54080fd4610072d4fea2e865ddd0e644136bacb3a2693c55db467179416aee123e5c95a80e0b24d33c23459e601cb02000df3f9df79c342e45d264ac8468fb3c",
          "sha256": "d3e4509684d52cdba5bcc16976caa8f748d30e285716ee068931d35e1efd6ab0",
          "sha1": "cab17da1e632695b7889e86d857536c415f6a023",
          "md5": "51a0232dded2ae5742b9357a40e21333"
        }
      ]
    }
  ]
}
