{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.4.jar",
          "url": "api-1.5.4.jar",
          "size": 1338171,
          "sha512": "f897e30661434372aff3dc3651c559c0b3538b991505bfc83e9f777f796cc46a336b1605aad7c381693c3d7cf1ea50ab79b93a186926480f5052c8ba8b73c2e3",
          "sha256": "37f4500a745d304a6f7abbfd5e92cac9380336135f5ddffb76bc67b1083dcff7",
          "sha1": "9843c93fcf8e05b1f5ece81333d73667ea3e163a",
          "md5": "3ed1aa33dfef0322229dcbb36b74132b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.5.4.jar",
          "url": "api-1.5.4.jar",
          "size": 1338171,
          "sha512": "f897e30661434372aff3dc3651c559c0b3538b991505bfc83e9f777f796cc46a336b1605aad7c381693c3d7cf1ea50ab79b93a186926480f5052c8ba8b73c2e3",
          "sha256": "37f4500a745d304a6f7abbfd5e92cac9380336135f5ddffb76bc67b1083dcff7",
          "sha1": "9843c93fcf8e05b1f5ece81333d73667ea3e163a",
          "md5": "3ed1aa33dfef0322229dcbb36b74132b"
        }
      ]
    }
  ]
}
