{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.1.8.jar",
          "url": "scripts-1.1.8.jar",
          "size": 31053,
          "sha512": "1beb642f784e227ee2eed98f869addeceec7cb7bfce09176f6fd74cb5d3a3d4f72a27698b21ce89a6580b97b4ac4d07d646b32579a7531a58599a6b744fb601c",
          "sha256": "b26b230a5059f0781532b124ece6ece7137fe89e0c2efb358cc6e23de52e15f9",
          "sha1": "0fd80fd7c60d3f581ff6782d855708b18b407086",
          "md5": "841343abdaad64a00feb69fbd2f4cdc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.1.8.jar",
          "url": "scripts-1.1.8.jar",
          "size": 31053,
          "sha512": "1beb642f784e227ee2eed98f869addeceec7cb7bfce09176f6fd74cb5d3a3d4f72a27698b21ce89a6580b97b4ac4d07d646b32579a7531a58599a6b744fb601c",
          "sha256": "b26b230a5059f0781532b124ece6ece7137fe89e0c2efb358cc6e23de52e15f9",
          "sha1": "0fd80fd7c60d3f581ff6782d855708b18b407086",
          "md5": "841343abdaad64a00feb69fbd2f4cdc9"
        }
      ]
    }
  ]
}
