{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.0.1.jar",
          "url": "annotations-1.0.1.jar",
          "size": 7290,
          "sha512": "c78d2bfa097ca79888332e599c1494316249d2dba358c5e7f21c8adcb81ef2a368c775666e3b49c38633fd93a20b582a23f702abb5d416deaac8fc2aac1be238",
          "sha256": "69f8a8abf9db8ee8a55a46b5f3f2281a6d787cee9272e707d19f0c829b57f917",
          "sha1": "46bfad78ecdb10172e47b416e5bcc44233461c54",
          "md5": "02c52f9ff820c55f0ef39139e5e6a52a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.1.jar",
          "url": "annotations-1.0.1.jar",
          "size": 7290,
          "sha512": "c78d2bfa097ca79888332e599c1494316249d2dba358c5e7f21c8adcb81ef2a368c775666e3b49c38633fd93a20b582a23f702abb5d416deaac8fc2aac1be238",
          "sha256": "69f8a8abf9db8ee8a55a46b5f3f2281a6d787cee9272e707d19f0c829b57f917",
          "sha1": "46bfad78ecdb10172e47b416e5bcc44233461c54",
          "md5": "02c52f9ff820c55f0ef39139e5e6a52a"
        }
      ]
    }
  ]
}
