{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.2.jar",
          "url": "annotations-1.6.2.jar",
          "size": 8843,
          "sha512": "1bcd6e66e4a3c032860fb24d9e0b0e1d9ad78db7bc966458b39b94409d2d7f4ee952491c48ed0c5b6b2d47fe346db2d0c90f4485d1b0c197b71f05c2d1d0fce9",
          "sha256": "949bf1536a5c975558c07cfd7dc78a6dd2bc328a11069e446da3fbabddb44b5d",
          "sha1": "829cd892681d01f6f07ad0ffa1d5abe2a7fb822d",
          "md5": "67ed8add6af743a023c28a3c8739bcb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.2.jar",
          "url": "annotations-1.6.2.jar",
          "size": 8843,
          "sha512": "1bcd6e66e4a3c032860fb24d9e0b0e1d9ad78db7bc966458b39b94409d2d7f4ee952491c48ed0c5b6b2d47fe346db2d0c90f4485d1b0c197b71f05c2d1d0fce9",
          "sha256": "949bf1536a5c975558c07cfd7dc78a6dd2bc328a11069e446da3fbabddb44b5d",
          "sha1": "829cd892681d01f6f07ad0ffa1d5abe2a7fb822d",
          "md5": "67ed8add6af743a023c28a3c8739bcb0"
        }
      ]
    }
  ]
}
