{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.2.jar",
          "url": "annotations-1.6.2.jar",
          "size": 8843,
          "sha512": "afcfbeba5ec6cf8d614dec4bbc5b1967766d07603970ed209607af8a3302ce4587b1df40858740d61365aeb83f57cf3e0d6a1eccbd3f8323a7dae153b6753720",
          "sha256": "c884b453107614e926b21991c3adaad18f8d45a7f2b484d3e009cd348d1ad67b",
          "sha1": "792354c5dfb3b291fc2e2f8232a5ba852e4ed55c",
          "md5": "e36acb2481434d1d3e0f7254f329f763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.2.jar",
          "url": "annotations-1.6.2.jar",
          "size": 8843,
          "sha512": "afcfbeba5ec6cf8d614dec4bbc5b1967766d07603970ed209607af8a3302ce4587b1df40858740d61365aeb83f57cf3e0d6a1eccbd3f8323a7dae153b6753720",
          "sha256": "c884b453107614e926b21991c3adaad18f8d45a7f2b484d3e009cd348d1ad67b",
          "sha1": "792354c5dfb3b291fc2e2f8232a5ba852e4ed55c",
          "md5": "e36acb2481434d1d3e0f7254f329f763"
        }
      ]
    }
  ]
}
