{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.2.jar",
          "url": "http-1.6.2.jar",
          "size": 104648,
          "sha512": "2b403e2e110ae3311fd866cf639dd5f735db0db4fdb6987acd39a47a9c4f85e471eea4b2af06bf76c75035ea2df70ef2f35433f51a2955c876128e9095b60ff7",
          "sha256": "897878dfd08d62ca52fb09ee492650c8db5926baa67d8ea95aff38ea1a866dfb",
          "sha1": "00236e5b1687f568a7b969c404847d8aa301af4d",
          "md5": "f4983176b3d3b1d979e131184e18d026"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.2.jar",
          "url": "http-1.6.2.jar",
          "size": 104648,
          "sha512": "2b403e2e110ae3311fd866cf639dd5f735db0db4fdb6987acd39a47a9c4f85e471eea4b2af06bf76c75035ea2df70ef2f35433f51a2955c876128e9095b60ff7",
          "sha256": "897878dfd08d62ca52fb09ee492650c8db5926baa67d8ea95aff38ea1a866dfb",
          "sha1": "00236e5b1687f568a7b969c404847d8aa301af4d",
          "md5": "f4983176b3d3b1d979e131184e18d026"
        }
      ]
    }
  ]
}
