{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.2.jar",
          "url": "http-1.6.2.jar",
          "size": 104648,
          "sha512": "db70095afbafb5ed353943c6ee3031d9c4d8d7606bb87c2bd43f407d479eef551d58b1132e1be6db3e2319dae4e9755f8c26df4cfd4e84d6ca73cb8146c0e778",
          "sha256": "8c7a9ef50a19d603720c91c90b31d8114f31cea1c81e8239ccc099b167c87e63",
          "sha1": "1a52f7759521ee8d19f2822fe07f060693e2b378",
          "md5": "294b056990ee92b47b5e170331d17f4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.2.jar",
          "url": "http-1.6.2.jar",
          "size": 104648,
          "sha512": "db70095afbafb5ed353943c6ee3031d9c4d8d7606bb87c2bd43f407d479eef551d58b1132e1be6db3e2319dae4e9755f8c26df4cfd4e84d6ca73cb8146c0e778",
          "sha256": "8c7a9ef50a19d603720c91c90b31d8114f31cea1c81e8239ccc099b167c87e63",
          "sha1": "1a52f7759521ee8d19f2822fe07f060693e2b378",
          "md5": "294b056990ee92b47b5e170331d17f4d"
        }
      ]
    }
  ]
}
