{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.15.jar",
          "url": "http-1.6.15.jar",
          "size": 104688,
          "sha512": "abf3022cb8ef8c2e52dc2a2e82a5d60b4e8f2d0d5290f98c2d494b73fb4fe4b3db1c9bb34fc02767ee87d461a185700a05a96f5be3a982fef127d669fbd95c5f",
          "sha256": "36137a47203921a63bc04a2f34f123a0ece8d2c1f8cd194355c9e26faf748080",
          "sha1": "2232a10ddac5bdca8482ecb67dbd3a4b81804e9e",
          "md5": "bed93650c62137adc9be7158d51a30f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.15"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.15"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.15.jar",
          "url": "http-1.6.15.jar",
          "size": 104688,
          "sha512": "abf3022cb8ef8c2e52dc2a2e82a5d60b4e8f2d0d5290f98c2d494b73fb4fe4b3db1c9bb34fc02767ee87d461a185700a05a96f5be3a982fef127d669fbd95c5f",
          "sha256": "36137a47203921a63bc04a2f34f123a0ece8d2c1f8cd194355c9e26faf748080",
          "sha1": "2232a10ddac5bdca8482ecb67dbd3a4b81804e9e",
          "md5": "bed93650c62137adc9be7158d51a30f8"
        }
      ]
    }
  ]
}
