{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.6.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.6.6.jar",
          "url": "annotations-1.6.6.jar",
          "size": 8843,
          "sha512": "bbacd0e3b24b6af59f79c5224a971c7c0ccbcafc05efb33c740636590ae5e75b5e6cd91862c08e7f9d15806feb2138b0cd9cedda50822667d7fb74b836211b83",
          "sha256": "e440b54568ec4263ddd8349a33c99b7fd49ea80b49633ac3baeb92bd70297488",
          "sha1": "09ca8c68795077bb70608585061a9ef363a36bed",
          "md5": "dd388eb85a5b171c3bd92bb463f94891"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.6.6.jar",
          "url": "annotations-1.6.6.jar",
          "size": 8843,
          "sha512": "bbacd0e3b24b6af59f79c5224a971c7c0ccbcafc05efb33c740636590ae5e75b5e6cd91862c08e7f9d15806feb2138b0cd9cedda50822667d7fb74b836211b83",
          "sha256": "e440b54568ec4263ddd8349a33c99b7fd49ea80b49633ac3baeb92bd70297488",
          "sha1": "09ca8c68795077bb70608585061a9ef363a36bed",
          "md5": "dd388eb85a5b171c3bd92bb463f94891"
        }
      ]
    }
  ]
}
