{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.4.0.jar",
          "url": "logger-1.4.0.jar",
          "size": 8658,
          "sha512": "1c3f388c49a38b11479f90a5076515580b2ba44d52df5747ea9e476b912a1170b0dbda779df6671bc08b107d6118d9bee5c13adb318ab840db14707532e6a094",
          "sha256": "52a51f95e262d5f3b43d729ed1f9aa8ecb69de83898d502cc0eeef137ddb6abd",
          "sha1": "0af358073bb1e6641fb566859094dc74abd35aa8",
          "md5": "474d6ec415b269b326fd7cf80979ac89"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.4.0.jar",
          "url": "logger-1.4.0.jar",
          "size": 8658,
          "sha512": "1c3f388c49a38b11479f90a5076515580b2ba44d52df5747ea9e476b912a1170b0dbda779df6671bc08b107d6118d9bee5c13adb318ab840db14707532e6a094",
          "sha256": "52a51f95e262d5f3b43d729ed1f9aa8ecb69de83898d502cc0eeef137ddb6abd",
          "sha1": "0af358073bb1e6641fb566859094dc74abd35aa8",
          "md5": "474d6ec415b269b326fd7cf80979ac89"
        }
      ]
    }
  ]
}
