{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.7.jar",
          "url": "api-1.2.7.jar",
          "size": 1340031,
          "sha512": "f70ea6905d861bcfc640cd0c797fec535b51ceb75129da3e8a31f5b463322eb974f90d7d0d1fab7d2418c1fdb6e70e2115d0f2e950adacebb80b5bbbb66a213e",
          "sha256": "9a77463303cd9931c255458ef2730d837c59249e09f935b5fc861855f44a9535",
          "sha1": "41e912ea73aca4e54df9e7fbd353f9416bc5b3d4",
          "md5": "ead487819a8eaaf38b0c4d5d2898c2e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.7"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.7.jar",
          "url": "api-1.2.7.jar",
          "size": 1340031,
          "sha512": "f70ea6905d861bcfc640cd0c797fec535b51ceb75129da3e8a31f5b463322eb974f90d7d0d1fab7d2418c1fdb6e70e2115d0f2e950adacebb80b5bbbb66a213e",
          "sha256": "9a77463303cd9931c255458ef2730d837c59249e09f935b5fc861855f44a9535",
          "sha1": "41e912ea73aca4e54df9e7fbd353f9416bc5b3d4",
          "md5": "ead487819a8eaaf38b0c4d5d2898c2e0"
        }
      ]
    }
  ]
}
