{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.0.jar",
          "url": "api-1.4.0.jar",
          "size": 1338056,
          "sha512": "31a1440ce1ebe322af2567ad3a964cb8c48235d70a096bc87bd5d7b2eef1e9e8311e999580155bfdf6807e0be20b3670dd0575d60d0ba4c64f66ab004d5c3ee1",
          "sha256": "bfd02704ca1c27d29fc13ff8ad5787b731ab47a68b5204a115034c78fb374687",
          "sha1": "165864d61aee1d3676efacd2eceb203737439e5f",
          "md5": "c5f7ca082e71fcdd04ff81e64f5adeb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.0.jar",
          "url": "api-1.4.0.jar",
          "size": 1338056,
          "sha512": "31a1440ce1ebe322af2567ad3a964cb8c48235d70a096bc87bd5d7b2eef1e9e8311e999580155bfdf6807e0be20b3670dd0575d60d0ba4c64f66ab004d5c3ee1",
          "sha256": "bfd02704ca1c27d29fc13ff8ad5787b731ab47a68b5204a115034c78fb374687",
          "sha1": "165864d61aee1d3676efacd2eceb203737439e5f",
          "md5": "c5f7ca082e71fcdd04ff81e64f5adeb3"
        }
      ]
    }
  ]
}
