{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.0.jar",
          "url": "api-1.4.0.jar",
          "size": 1338053,
          "sha512": "a218e21c425b1ba1130798b59dc26120f2e9968d61c97befeda1b43a33d8b6e819f7673a95dcb9a2aa42c4981db591f93fdd54ef7379296d7ebffad4a20c6cee",
          "sha256": "8d3b14b6b262578d1ce5cd2594a25adeecf1ce587ad7f9f02395b557d058c2a0",
          "sha1": "de2ca71d4daf9d7e00e5bac13dcec5a50d6ffd3d",
          "md5": "45a2586ee916bfffe43958685fed9f35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.0.jar",
          "url": "api-1.4.0.jar",
          "size": 1338053,
          "sha512": "a218e21c425b1ba1130798b59dc26120f2e9968d61c97befeda1b43a33d8b6e819f7673a95dcb9a2aa42c4981db591f93fdd54ef7379296d7ebffad4a20c6cee",
          "sha256": "8d3b14b6b262578d1ce5cd2594a25adeecf1ce587ad7f9f02395b557d058c2a0",
          "sha1": "de2ca71d4daf9d7e00e5bac13dcec5a50d6ffd3d",
          "md5": "45a2586ee916bfffe43958685fed9f35"
        }
      ]
    }
  ]
}
