{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.0.jar",
          "url": "api-1.4.0.jar",
          "size": 1338056,
          "sha512": "aa8cb04dc61b30afe49d838774c73082c8ca489ecc5c30f4de91ff72b3b209c1c04eb46abc449970bb3ea67b33c154e664906f90993c998cebefb2bdbe0759da",
          "sha256": "7f100793bc33974b1900bdaa9f214a647125b8138f43082624ba388570508b4a",
          "sha1": "d0883afed2bdb9af6c9327c4a7dcae253b133c02",
          "md5": "87d23c7b16a9b962d4696f4e5f30c458"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.0.jar",
          "url": "api-1.4.0.jar",
          "size": 1338056,
          "sha512": "aa8cb04dc61b30afe49d838774c73082c8ca489ecc5c30f4de91ff72b3b209c1c04eb46abc449970bb3ea67b33c154e664906f90993c998cebefb2bdbe0759da",
          "sha256": "7f100793bc33974b1900bdaa9f214a647125b8138f43082624ba388570508b4a",
          "sha1": "d0883afed2bdb9af6c9327c4a7dcae253b133c02",
          "md5": "87d23c7b16a9b962d4696f4e5f30c458"
        }
      ]
    }
  ]
}
