{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.6.jar",
          "url": "api-1.4.6.jar",
          "size": 1338053,
          "sha512": "1f8ad588438a77cd65b385f03a9f93d16c5d850df62c0c37df48195e1fa818fa6ea05248f9bfc05e2c69ee48b7b6f5e23f7f01eb668c28d6a484e187eabab13f",
          "sha256": "0c0e470b034c6ec6c7ec48e41009c9254cfc8246d9c07d65f65f6ef8a25bc775",
          "sha1": "6e2d664f375ba5eb994653dc2f3f85ed56fb13bc",
          "md5": "099ba436d06b4c82d6f7b06b79396a9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.4.6.jar",
          "url": "api-1.4.6.jar",
          "size": 1338053,
          "sha512": "1f8ad588438a77cd65b385f03a9f93d16c5d850df62c0c37df48195e1fa818fa6ea05248f9bfc05e2c69ee48b7b6f5e23f7f01eb668c28d6a484e187eabab13f",
          "sha256": "0c0e470b034c6ec6c7ec48e41009c9254cfc8246d9c07d65f65f6ef8a25bc775",
          "sha1": "6e2d664f375ba5eb994653dc2f3f85ed56fb13bc",
          "md5": "099ba436d06b4c82d6f7b06b79396a9d"
        }
      ]
    }
  ]
}
