{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.8.jar",
          "url": "api-1.1.8.jar",
          "size": 1339177,
          "sha512": "e6eabc1bbdab63d5057805f0895e3bc4ee245e34a71c340fa36ea98771072a629e91acc735d5d23e110e7b6f7978b01f72666ad7277e547dc055642a097e9101",
          "sha256": "568012c10f16b30dfdd0950d02552eb04551c7215e3b745a860652d3fe40343b",
          "sha1": "0d1c5eea61ac90c9e7e557175d1edbb3f2e98fa2",
          "md5": "a4c947ef110ffae7583c7ec0a282f12a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.8.jar",
          "url": "api-1.1.8.jar",
          "size": 1339177,
          "sha512": "e6eabc1bbdab63d5057805f0895e3bc4ee245e34a71c340fa36ea98771072a629e91acc735d5d23e110e7b6f7978b01f72666ad7277e547dc055642a097e9101",
          "sha256": "568012c10f16b30dfdd0950d02552eb04551c7215e3b745a860652d3fe40343b",
          "sha1": "0d1c5eea61ac90c9e7e557175d1edbb3f2e98fa2",
          "md5": "a4c947ef110ffae7583c7ec0a282f12a"
        }
      ]
    }
  ]
}
