{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.8.jar",
          "url": "api-1.1.8.jar",
          "size": 1339151,
          "sha512": "830e27f882d99cb4aa1a78ed113db37dc58f84f0ed5b73348782671fbe05bf83367370cb283f752fd4e5dfbd6915cd07d2ea1cd9ce1687a7b515f441a85c6bcb",
          "sha256": "a56ac7e3adcbf2d40810d90c3582770a282980efe975c43532a524a7970bc703",
          "sha1": "d7bb2c69b567dc6ba6220da1d572d301cdee4cb8",
          "md5": "92a785bf30755a9054634287db938ba2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.1.8.jar",
          "url": "api-1.1.8.jar",
          "size": 1339151,
          "sha512": "830e27f882d99cb4aa1a78ed113db37dc58f84f0ed5b73348782671fbe05bf83367370cb283f752fd4e5dfbd6915cd07d2ea1cd9ce1687a7b515f441a85c6bcb",
          "sha256": "a56ac7e3adcbf2d40810d90c3582770a282980efe975c43532a524a7970bc703",
          "sha1": "d7bb2c69b567dc6ba6220da1d572d301cdee4cb8",
          "md5": "92a785bf30755a9054634287db938ba2"
        }
      ]
    }
  ]
}
