{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.13.jar",
          "url": "api-1.6.13.jar",
          "size": 1367603,
          "sha512": "d37d8fb98d50d7280b6707d512537b1fb0b44b8a5a0e6f5fd7511053653a94ea8b9b1aac94a427a83093c9d94adf284c72e7e6017e1c2abc7bcdf07aed6adacd",
          "sha256": "283afc2916feff4d91dd300559508d69f4939356af98868975e9966e8eb2a781",
          "sha1": "78c403e637e6d7cba15cc1a8637a26ab7588f242",
          "md5": "57a8a25e1cd6145053ec5006f2aa702e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.13"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.13"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.13.jar",
          "url": "api-1.6.13.jar",
          "size": 1367603,
          "sha512": "d37d8fb98d50d7280b6707d512537b1fb0b44b8a5a0e6f5fd7511053653a94ea8b9b1aac94a427a83093c9d94adf284c72e7e6017e1c2abc7bcdf07aed6adacd",
          "sha256": "283afc2916feff4d91dd300559508d69f4939356af98868975e9966e8eb2a781",
          "sha1": "78c403e637e6d7cba15cc1a8637a26ab7588f242",
          "md5": "57a8a25e1cd6145053ec5006f2aa702e"
        }
      ]
    }
  ]
}
