{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.9.jar",
          "url": "logger-1.2.9.jar",
          "size": 8658,
          "sha512": "bebda2c50077921973b121ff608f4e79e8e44827a0b7d327a296b1ffe8bff4f4235b1b172b439a76657c5fb09731b4e7b7a2a9968c16a67be2c9c7c1f5e3296c",
          "sha256": "8fb3dd46763d51fcac40614239397da05ee83ec60c0664a42f47c3b5508ae670",
          "sha1": "dbdbcd688384695eee358418b4063e49abaa5142",
          "md5": "d7477ae1b87a550b108f9f393ab132a9"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.9.jar",
          "url": "logger-1.2.9.jar",
          "size": 8658,
          "sha512": "bebda2c50077921973b121ff608f4e79e8e44827a0b7d327a296b1ffe8bff4f4235b1b172b439a76657c5fb09731b4e7b7a2a9968c16a67be2c9c7c1f5e3296c",
          "sha256": "8fb3dd46763d51fcac40614239397da05ee83ec60c0664a42f47c3b5508ae670",
          "sha1": "dbdbcd688384695eee358418b4063e49abaa5142",
          "md5": "d7477ae1b87a550b108f9f393ab132a9"
        }
      ]
    }
  ]
}
