{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "logger",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.2.jar",
          "url": "logger-1.2.2.jar",
          "size": 8662,
          "sha512": "c9fe7fcf39132d42ba5969094fb3db69c107daa5c694dcd9f78becf2ac9b30c5c913b616c35fd1e144c239430e30824f6ac3bb3c0b85610f32f286c4b8868f3c",
          "sha256": "64cd1315183283589d92c36e2315a3aa2a5573bb3ae9bb520a2fc6ad4c0d4d19",
          "sha1": "ae829e0494bd0e66f1ec27e19b4a71ea16029099",
          "md5": "eb9fc1c96b13b48a4d9a91270b187ae3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "logger-1.2.2.jar",
          "url": "logger-1.2.2.jar",
          "size": 8662,
          "sha512": "c9fe7fcf39132d42ba5969094fb3db69c107daa5c694dcd9f78becf2ac9b30c5c913b616c35fd1e144c239430e30824f6ac3bb3c0b85610f32f286c4b8868f3c",
          "sha256": "64cd1315183283589d92c36e2315a3aa2a5573bb3ae9bb520a2fc6ad4c0d4d19",
          "sha1": "ae829e0494bd0e66f1ec27e19b4a71ea16029099",
          "md5": "eb9fc1c96b13b48a4d9a91270b187ae3"
        }
      ]
    }
  ]
}
