{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.2.jar",
          "url": "api-1.2.2.jar",
          "size": 1339145,
          "sha512": "492cd0ce4d492f7295ffdb78ad0500c299d1ea06cf7453ad656977d85c3e5fa894352af0fd61fc79cdc9ad9c79d09c4671ab3b98fed2ad8b9a3cfa6e581a003a",
          "sha256": "c7dab20ee3a7fb30fe8bfff8ed93c2f68e9363d3a9509ae038301136e0dd4068",
          "sha1": "86d5ba8517964bfe60fca70b93954aa7fe85f5c2",
          "md5": "96001a911238eaea25b59f8fa8fc30dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.2.jar",
          "url": "api-1.2.2.jar",
          "size": 1339145,
          "sha512": "492cd0ce4d492f7295ffdb78ad0500c299d1ea06cf7453ad656977d85c3e5fa894352af0fd61fc79cdc9ad9c79d09c4671ab3b98fed2ad8b9a3cfa6e581a003a",
          "sha256": "c7dab20ee3a7fb30fe8bfff8ed93c2f68e9363d3a9509ae038301136e0dd4068",
          "sha1": "86d5ba8517964bfe60fca70b93954aa7fe85f5c2",
          "md5": "96001a911238eaea25b59f8fa8fc30dc"
        }
      ]
    }
  ]
}
