{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.6.3.jar",
          "url": "http-1.6.3.jar",
          "size": 104648,
          "sha512": "38b2f3a58d00ca3dcddce6378074ac630f76ca8f996585e6a11c91e4950a81997cf623e0af30610bd261cf7004d87f33a34ec1b577394889a532023bcb6c5bb4",
          "sha256": "7a51d3b18ebcb63de428e94a8a375f52f43f9b8f2010c757d64696415c9ebf9e",
          "sha1": "d5083c512283ab8e54d705cad9c32609dddad260",
          "md5": "454732f93fae6301ea784ec0ffa40699"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.6.3.jar",
          "url": "http-1.6.3.jar",
          "size": 104648,
          "sha512": "38b2f3a58d00ca3dcddce6378074ac630f76ca8f996585e6a11c91e4950a81997cf623e0af30610bd261cf7004d87f33a34ec1b577394889a532023bcb6c5bb4",
          "sha256": "7a51d3b18ebcb63de428e94a8a375f52f43f9b8f2010c757d64696415c9ebf9e",
          "sha1": "d5083c512283ab8e54d705cad9c32609dddad260",
          "md5": "454732f93fae6301ea784ec0ffa40699"
        }
      ]
    }
  ]
}
