{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.4.1.jar",
          "url": "scripts-1.4.1.jar",
          "size": 31877,
          "sha512": "87fdeaf1f0fc75a0172920e1a33faea9f121c1a122f6e6b8b43194c66e10d21d55b8fca275890a4c747b6139dffba21d24badb322209b047ad40bcb7999dee81",
          "sha256": "f6b7dba2d0df82e571686fc37bff7f1f7ee788ab988351e2004272b72d93eb09",
          "sha1": "f3f68b5d829a42533b8296d15a127263a11b5f9d",
          "md5": "3447ec425144b67718157af63026410e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.4.1.jar",
          "url": "scripts-1.4.1.jar",
          "size": 31877,
          "sha512": "87fdeaf1f0fc75a0172920e1a33faea9f121c1a122f6e6b8b43194c66e10d21d55b8fca275890a4c747b6139dffba21d24badb322209b047ad40bcb7999dee81",
          "sha256": "f6b7dba2d0df82e571686fc37bff7f1f7ee788ab988351e2004272b72d93eb09",
          "sha1": "f3f68b5d829a42533b8296d15a127263a11b5f9d",
          "md5": "3447ec425144b67718157af63026410e"
        }
      ]
    }
  ]
}
