{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.4.1.jar",
          "url": "api-rs-1.4.1.jar",
          "size": 122412,
          "sha512": "d850961a6a2198a208f119ab5501fce4e488939b99f5e82dccec00fb5c84e975340f6fab9d372524d5baffdbb4e81da13aa05221641b39d02d8540fc235ba50e",
          "sha256": "de4e8f84618d9ed3ac990d27ce7b245d09399997c29fdfe2bf2be8fb4cb98152",
          "sha1": "9089e8f4aab8c23afb48e897b2e8909adc57af1b",
          "md5": "a6b91cbd1d5151402d9b09beff14a63b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.4.1.jar",
          "url": "api-rs-1.4.1.jar",
          "size": 122412,
          "sha512": "d850961a6a2198a208f119ab5501fce4e488939b99f5e82dccec00fb5c84e975340f6fab9d372524d5baffdbb4e81da13aa05221641b39d02d8540fc235ba50e",
          "sha256": "de4e8f84618d9ed3ac990d27ce7b245d09399997c29fdfe2bf2be8fb4cb98152",
          "sha1": "9089e8f4aab8c23afb48e897b2e8909adc57af1b",
          "md5": "a6b91cbd1d5151402d9b09beff14a63b"
        }
      ]
    }
  ]
}
