{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.10.jar",
          "url": "api-1.2.10.jar",
          "size": 1338451,
          "sha512": "5fd105c6290b28c77a8e6a750ed8018922fe60e7133982863b522a76434d418a981e0bac3c4e64ba2c9a57f74aae8c00ee64353fb396c0dae3090c9a0a674b56",
          "sha256": "5d7bf437b1fdf4f70f5471d07454d9515f98fad274545030077403e59fceb568",
          "sha1": "a4389aae96fe12e7a05ada57f870e553049e42cd",
          "md5": "511a6ec2a5cb10758b988808d1e3c56a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.2.10"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.2.10.jar",
          "url": "api-1.2.10.jar",
          "size": 1338451,
          "sha512": "5fd105c6290b28c77a8e6a750ed8018922fe60e7133982863b522a76434d418a981e0bac3c4e64ba2c9a57f74aae8c00ee64353fb396c0dae3090c9a0a674b56",
          "sha256": "5d7bf437b1fdf4f70f5471d07454d9515f98fad274545030077403e59fceb568",
          "sha1": "a4389aae96fe12e7a05ada57f870e553049e42cd",
          "md5": "511a6ec2a5cb10758b988808d1e3c56a"
        }
      ]
    }
  ]
}
