{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-3.0.0.jar",
          "url": "annotations-3.0.0.jar",
          "size": 8843,
          "sha512": "41357f6686f7da191b909a9a643fc3e647af52798b76b15d7d016d2ccfa6c40ed8b60b634aab23059e3ec9cf36f6964c8d127e675e8d4f6ec24065270c5dc7ef",
          "sha256": "76dbb07bcc98e46f06f838f3557519dc353ed58a39639f0bbed8d3327f012222",
          "sha1": "9fb84e1633b996cf53866711ae28bfb8ea53ea98",
          "md5": "a64137d6ff7dfe80fb1448542187078a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-3.0.0.jar",
          "url": "annotations-3.0.0.jar",
          "size": 8843,
          "sha512": "41357f6686f7da191b909a9a643fc3e647af52798b76b15d7d016d2ccfa6c40ed8b60b634aab23059e3ec9cf36f6964c8d127e675e8d4f6ec24065270c5dc7ef",
          "sha256": "76dbb07bcc98e46f06f838f3557519dc353ed58a39639f0bbed8d3327f012222",
          "sha1": "9fb84e1633b996cf53866711ae28bfb8ea53ea98",
          "md5": "a64137d6ff7dfe80fb1448542187078a"
        }
      ]
    }
  ]
}
