{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.5.0.jar",
          "url": "annotations-1.5.0.jar",
          "size": 8843,
          "sha512": "f5363a87a234bbb05e0cfa688f794916dd43ce8e306f564d896f85485cbf3a5023e87007958de68ff62e2f0bac908711b3d1dfd321f6ef7bef9e3a1f3b18cacb",
          "sha256": "68191531a255ab47e3c25f11eb71ff69f84233a58e847d7fa53d3ef6fee6e0e5",
          "sha1": "204517fbba56e0f902c454bd74df027e8ac6d011",
          "md5": "c7cd7d53a7e74cb69ddd7d0af118cec4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.5.0.jar",
          "url": "annotations-1.5.0.jar",
          "size": 8843,
          "sha512": "f5363a87a234bbb05e0cfa688f794916dd43ce8e306f564d896f85485cbf3a5023e87007958de68ff62e2f0bac908711b3d1dfd321f6ef7bef9e3a1f3b18cacb",
          "sha256": "68191531a255ab47e3c25f11eb71ff69f84233a58e847d7fa53d3ef6fee6e0e5",
          "sha1": "204517fbba56e0f902c454bd74df027e8ac6d011",
          "md5": "c7cd7d53a7e74cb69ddd7d0af118cec4"
        }
      ]
    }
  ]
}
