{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.4.6.jar",
          "url": "scripts-1.4.6.jar",
          "size": 31877,
          "sha512": "6357dfa83dd7e230aa13b6e0b60bd9e83c8dc599c70d7506ae940b6611e23b63501ee0a2eb648b25601ba37315f1618af0d3e14d19e0897d1dc8255763cd2fa8",
          "sha256": "782a3e89cd72104f3a1aa3442529fe4bfb636fbd0cd2b8340871b9f3fc78f643",
          "sha1": "d14d0d2216ca87caf68b50997ceb9bbd7ce2de47",
          "md5": "eaf9fbafc140d03a9c06165007a06767"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.4.6.jar",
          "url": "scripts-1.4.6.jar",
          "size": 31877,
          "sha512": "6357dfa83dd7e230aa13b6e0b60bd9e83c8dc599c70d7506ae940b6611e23b63501ee0a2eb648b25601ba37315f1618af0d3e14d19e0897d1dc8255763cd2fa8",
          "sha256": "782a3e89cd72104f3a1aa3442529fe4bfb636fbd0cd2b8340871b9f3fc78f643",
          "sha1": "d14d0d2216ca87caf68b50997ceb9bbd7ce2de47",
          "md5": "eaf9fbafc140d03a9c06165007a06767"
        }
      ]
    }
  ]
}
