{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "http",
    "version": "1.4.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-1.4.8.jar",
          "url": "http-1.4.8.jar",
          "size": 104410,
          "sha512": "e359957bd406647de0a345bb4595ea6667dd5c0bbe79fc190838b7b12a5ae2910d52a834a7cdc829508416e52713a496e63252fdef245e8e9223a985ad39f854",
          "sha256": "503dfddaedf3d9c34f5f2ea5137e2922a035f5a373c54c83b4bd7540e81c472f",
          "sha1": "bc628aa4ee19277f10cdd649e8e30f57a19c94e4",
          "md5": "7e4177537960ea1b448997bb5f1042e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.4.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.7.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.4"
          }
        }
      ],
      "files": [
        {
          "name": "http-1.4.8.jar",
          "url": "http-1.4.8.jar",
          "size": 104410,
          "sha512": "e359957bd406647de0a345bb4595ea6667dd5c0bbe79fc190838b7b12a5ae2910d52a834a7cdc829508416e52713a496e63252fdef245e8e9223a985ad39f854",
          "sha256": "503dfddaedf3d9c34f5f2ea5137e2922a035f5a373c54c83b4bd7540e81c472f",
          "sha1": "bc628aa4ee19277f10cdd649e8e30f57a19c94e4",
          "md5": "7e4177537960ea1b448997bb5f1042e8"
        }
      ]
    }
  ]
}
