{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "runescape-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "runescape-api-1.0.0.jar",
          "url": "runescape-api-1.0.0.jar",
          "size": 116641,
          "sha512": "d83c0156f02b067f975ad02daeb60eea941ba9760e640edebf6b4db78b7d57e8af1c95a29dad1c9b097c7640667f115c5f20c89e5d989afa49f4a243c2ad13ea",
          "sha256": "cff989b4326bc6b5ffbda86e4a1b26ac403e5f11d04b4f266137fb959ce7e9d0",
          "sha1": "ac9ad9d592d7c00b2242132455d212acc2026e94",
          "md5": "7f09f671b42f21873bd4dec28afda4a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "meteor",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.0.jar",
          "url": "runescape-api-1.0.0.jar",
          "size": 116641,
          "sha512": "d83c0156f02b067f975ad02daeb60eea941ba9760e640edebf6b4db78b7d57e8af1c95a29dad1c9b097c7640667f115c5f20c89e5d989afa49f4a243c2ad13ea",
          "sha256": "cff989b4326bc6b5ffbda86e4a1b26ac403e5f11d04b4f266137fb959ce7e9d0",
          "sha1": "ac9ad9d592d7c00b2242132455d212acc2026e94",
          "md5": "7f09f671b42f21873bd4dec28afda4a3"
        }
      ]
    }
  ]
}
