{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "annotations",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-1.0.10.jar",
          "url": "annotations-1.0.10.jar",
          "size": 7290,
          "sha512": "7def6d7c6a6bdb763a73edd616793f800b2d038f93a66c139d680a78a0b3ae5e34e167a2beb3d697ee2bf5b190205d37e21fbe5b1bb237e537ae4f2c6e9ece40",
          "sha256": "eaf81261ef3136446584cdbc024517952ed098fbe9fb4553c66804fa326a52df",
          "sha1": "aeb76ad8acbf19b1b768eb79a66577934fd745e7",
          "md5": "81634a56aa5016374b760d0be4de7cea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-1.0.10.jar",
          "url": "annotations-1.0.10.jar",
          "size": 7290,
          "sha512": "7def6d7c6a6bdb763a73edd616793f800b2d038f93a66c139d680a78a0b3ae5e34e167a2beb3d697ee2bf5b190205d37e21fbe5b1bb237e537ae4f2c6e9ece40",
          "sha256": "eaf81261ef3136446584cdbc024517952ed098fbe9fb4553c66804fa326a52df",
          "sha1": "aeb76ad8acbf19b1b768eb79a66577934fd745e7",
          "md5": "81634a56aa5016374b760d0be4de7cea"
        }
      ]
    }
  ]
}
