{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.13.jar",
          "url": "scripts-1.6.13.jar",
          "size": 28428,
          "sha512": "8918af033375e67aaa5992bc29c73af1f8bea49de1a183d63c7751b22a683415d525b45f7b3f8e0a9de266582ff0d509f87eca3bc39b828a654a1281c5c2144b",
          "sha256": "b88959673165633c5df2539cbf6c0638371a4b8182dd62513fad9e7e845a2aa6",
          "sha1": "7a1f67fa2fb255ddebac521fd598a4bcedff81a8",
          "md5": "1de72ed89290eef492eeaaf4e3b92754"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.13.jar",
          "url": "scripts-1.6.13.jar",
          "size": 28428,
          "sha512": "8918af033375e67aaa5992bc29c73af1f8bea49de1a183d63c7751b22a683415d525b45f7b3f8e0a9de266582ff0d509f87eca3bc39b828a654a1281c5c2144b",
          "sha256": "b88959673165633c5df2539cbf6c0638371a4b8182dd62513fad9e7e845a2aa6",
          "sha1": "7a1f67fa2fb255ddebac521fd598a4bcedff81a8",
          "md5": "1de72ed89290eef492eeaaf4e3b92754"
        }
      ]
    }
  ]
}
