{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.13.jar",
          "url": "scripts-1.6.13.jar",
          "size": 28428,
          "sha512": "7668b97acc3aa4d3a6cdaaea045ef1453a1361e7f3e7a09b53fc1090273e9a7f0f2175e206bdfe57384fc587981e3bb45d018704cfa77cab59433124bb750083",
          "sha256": "94f55d532a0de90b2c1bbf2b0bb818d3e2e68a441eb784bf3091aa868ec79a3c",
          "sha1": "dbde43045de9cf842945f798d6222686553a13ee",
          "md5": "fb9cf1a05a5ea71c16103107fa28315a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.13.jar",
          "url": "scripts-1.6.13.jar",
          "size": 28428,
          "sha512": "7668b97acc3aa4d3a6cdaaea045ef1453a1361e7f3e7a09b53fc1090273e9a7f0f2175e206bdfe57384fc587981e3bb45d018704cfa77cab59433124bb750083",
          "sha256": "94f55d532a0de90b2c1bbf2b0bb818d3e2e68a441eb784bf3091aa868ec79a3c",
          "sha1": "dbde43045de9cf842945f798d6222686553a13ee",
          "md5": "fb9cf1a05a5ea71c16103107fa28315a"
        }
      ]
    }
  ]
}
