{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.4.jar",
          "url": "api-1.0.4.jar",
          "size": 1399954,
          "sha512": "fddc6bf70f1705bc0c93532ce1156110ba78c2cc46dceb7d34524450b606c525219d4c49fe40a8b6b66ab6615748bdfafe44de8dc1e8ed8be34b40b709452cbf",
          "sha256": "570725da77711a2c09c560f151d1405f3e581ee7ad2df4312870f8d9f5ddba00",
          "sha1": "76b6f35d8a8b7ac9cec0c43fa8b81e91ecaef547",
          "md5": "9dbfde2115bd5e484c75fb7ad2f2dc58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.0.4.jar",
          "url": "api-1.0.4.jar",
          "size": 1399954,
          "sha512": "fddc6bf70f1705bc0c93532ce1156110ba78c2cc46dceb7d34524450b606c525219d4c49fe40a8b6b66ab6615748bdfafe44de8dc1e8ed8be34b40b709452cbf",
          "sha256": "570725da77711a2c09c560f151d1405f3e581ee7ad2df4312870f8d9f5ddba00",
          "sha1": "76b6f35d8a8b7ac9cec0c43fa8b81e91ecaef547",
          "md5": "9dbfde2115bd5e484c75fb7ad2f2dc58"
        }
      ]
    }
  ]
}
