{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.6.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.6.13.jar",
          "url": "api-rs-1.6.13.jar",
          "size": 123892,
          "sha512": "b260520786549afa97f90aee680921466c23ff43498473027933c499abc79588d9bf6010792b8457c496a15544cf42fe4e206b43d4fffe579030d18161792527",
          "sha256": "546fa5e70b555b4713671b22af37af445cad11e375ded5af39c9fce885a81f0d",
          "sha1": "94ae5edee9c21c983351d61b0d4b074198fa34fe",
          "md5": "21a2aee80355d0df832db73936e0882d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.13"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.6.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.6.13.jar",
          "url": "api-rs-1.6.13.jar",
          "size": 123892,
          "sha512": "b260520786549afa97f90aee680921466c23ff43498473027933c499abc79588d9bf6010792b8457c496a15544cf42fe4e206b43d4fffe579030d18161792527",
          "sha256": "546fa5e70b555b4713671b22af37af445cad11e375ded5af39c9fce885a81f0d",
          "sha1": "94ae5edee9c21c983351d61b0d4b074198fa34fe",
          "md5": "21a2aee80355d0df832db73936e0882d"
        }
      ]
    }
  ]
}
