{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api",
    "version": "1.6.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.10.jar",
          "url": "api-1.6.10.jar",
          "size": 1341833,
          "sha512": "cc0f5fb9d7d006ef593fb57590dbe674ac861b21140ab70853234689ba0c88e20aaa32de35478771745aeb5273519b4d52112b1434d666e82f49f58400a8e6d6",
          "sha256": "1977400cf31566be94f5019c1e244a9e96cd6f35de4b8609ec17f44c70129a99",
          "sha1": "0c183cd6ec0a45208e3db0606ddb9116957194ea",
          "md5": "b722c856a30402643abc9c551fde1825"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "meteor",
          "module": "logger",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "23.2-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "api-1.6.10.jar",
          "url": "api-1.6.10.jar",
          "size": 1341833,
          "sha512": "cc0f5fb9d7d006ef593fb57590dbe674ac861b21140ab70853234689ba0c88e20aaa32de35478771745aeb5273519b4d52112b1434d666e82f49f58400a8e6d6",
          "sha256": "1977400cf31566be94f5019c1e244a9e96cd6f35de4b8609ec17f44c70129a99",
          "sha1": "0c183cd6ec0a45208e3db0606ddb9116957194ea",
          "md5": "b722c856a30402643abc9c551fde1825"
        }
      ]
    }
  ]
}
