{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "api-rs",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-rs-1.5.4.jar",
          "url": "api-rs-1.5.4.jar",
          "size": 122758,
          "sha512": "aeb94790d4974a4110b17d11fb6091d2ec87aa0b9bdfbca0339a9e875d34703547eba7defc7eaac1b6562dbfa68f4ef94fb6edc449fa156167168a969b1bfdab",
          "sha256": "0170ac5df039459df8b590ea515fcba76b587ab7b32dd292db5e81d2f11795c2",
          "sha1": "069059b31203f6d9fcd20de72815cf030b67f694",
          "md5": "7ac5cadd1984457f682f9b2bf7872d71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "meteor",
          "module": "annotations",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "meteor",
          "module": "api",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "files": [
        {
          "name": "api-rs-1.5.4.jar",
          "url": "api-rs-1.5.4.jar",
          "size": 122758,
          "sha512": "aeb94790d4974a4110b17d11fb6091d2ec87aa0b9bdfbca0339a9e875d34703547eba7defc7eaac1b6562dbfa68f4ef94fb6edc449fa156167168a969b1bfdab",
          "sha256": "0170ac5df039459df8b590ea515fcba76b587ab7b32dd292db5e81d2f11795c2",
          "sha1": "069059b31203f6d9fcd20de72815cf030b67f694",
          "md5": "7ac5cadd1984457f682f9b2bf7872d71"
        }
      ]
    }
  ]
}
