{
  "formatVersion": "1.1",
  "component": {
    "group": "meteor",
    "module": "scripts",
    "version": "1.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "scripts-1.6.7.jar",
          "url": "scripts-1.6.7.jar",
          "size": 28428,
          "sha512": "35a0fa3155d94ba71896ceed770c19b3937ec832fe76cb1a6169f9b2521a9f72ba7fcb38ffb584ae8a479405a8d7aa275def3206c319e5936ff72cfe5e25e4cd",
          "sha256": "84bde186b2c30f8357c71abaa53fd71d9c7ad395dca36f4e9412587750197aba",
          "sha1": "e1dee51a8921d5b37c2c67ea5698b769c9175f50",
          "md5": "045d1a6ae32739c6e81723a30f16a50c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "scripts-1.6.7.jar",
          "url": "scripts-1.6.7.jar",
          "size": 28428,
          "sha512": "35a0fa3155d94ba71896ceed770c19b3937ec832fe76cb1a6169f9b2521a9f72ba7fcb38ffb584ae8a479405a8d7aa275def3206c319e5936ff72cfe5e25e4cd",
          "sha256": "84bde186b2c30f8357c71abaa53fd71d9c7ad395dca36f4e9412587750197aba",
          "sha1": "e1dee51a8921d5b37c2c67ea5698b769c9175f50",
          "md5": "045d1a6ae32739c6e81723a30f16a50c"
        }
      ]
    }
  ]
}
